<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 12 ANOVA | WBS MRes: Learning From Data</title>
  <meta name="description" content="This book contains the examples and notes for the WBS MRes Learning From Data Course." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 12 ANOVA | WBS MRes: Learning From Data" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This book contains the examples and notes for the WBS MRes Learning From Data Course." />
  <meta name="github-repo" content="profnicklee/MRes_LFD_Book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 12 ANOVA | WBS MRes: Learning From Data" />
  
  <meta name="twitter:description" content="This book contains the examples and notes for the WBS MRes Learning From Data Course." />
  

<meta name="author" content="Professor Nick Lee" />


<meta name="date" content="2026-09-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="H-testing.html"/>
<link rel="next" href="Issues.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">WBS MRes: Learning From Data</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction and Orientation</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Describing the World With Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#summarizing-data-with-numbers"><i class="fa fa-check"></i><b>2.1</b> Summarizing Data with Numbers</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#box-plots"><i class="fa fa-check"></i><b>2.2</b> Box Plots</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#violin-plots-and-ridge-plots"><i class="fa fa-check"></i><b>2.3</b> Violin Plots and Ridge Plots</a></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#transformations"><i class="fa fa-check"></i><b>2.4</b> Transformations</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="norm-dist.html"><a href="norm-dist.html"><i class="fa fa-check"></i><b>3</b> The Normal Distribution</a>
<ul>
<li class="chapter" data-level="3.1" data-path="norm-dist.html"><a href="norm-dist.html#a-simple-demonstration-of-the-normal-distribution"><i class="fa fa-check"></i><b>3.1</b> A Simple Demonstration of the Normal Distribution</a></li>
<li class="chapter" data-level="3.2" data-path="norm-dist.html"><a href="norm-dist.html#what-actually-is-a-normal-distribution"><i class="fa fa-check"></i><b>3.2</b> What Actually is a Normal Distribution?</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="causation.html"><a href="causation.html"><i class="fa fa-check"></i><b>4</b> Causation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="causation.html"><a href="causation.html#confounding"><i class="fa fa-check"></i><b>4.1</b> Confounding</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="causation.html"><a href="causation.html#the-cornfield-test"><i class="fa fa-check"></i><b>4.1.1</b> The Cornfield Test</a></li>
<li class="chapter" data-level="4.1.2" data-path="causation.html"><a href="causation.html#the-everyday-version"><i class="fa fa-check"></i><b>4.1.2</b> The Everyday Version</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="causation.html"><a href="causation.html#selection-bias"><i class="fa fa-check"></i><b>4.2</b> Selection Bias</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="causation.html"><a href="causation.html#all-the-data-isnt-all-the-data"><i class="fa fa-check"></i><b>4.2.1</b> All the Data Isn’t All the Data</a></li>
<li class="chapter" data-level="4.2.2" data-path="causation.html"><a href="causation.html#manufacturing-a-relationship-from-nothing"><i class="fa fa-check"></i><b>4.2.2</b> Manufacturing a Relationship from Nothing</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="causation.html"><a href="causation.html#endogeneity"><i class="fa fa-check"></i><b>4.3</b> Endogeneity</a></li>
<li class="chapter" data-level="4.4" data-path="causation.html"><a href="causation.html#randomisation"><i class="fa fa-check"></i><b>4.4</b> Randomisation</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="assoc-rel.html"><a href="assoc-rel.html"><i class="fa fa-check"></i><b>5</b> Associations and Relationships</a>
<ul>
<li class="chapter" data-level="5.1" data-path="assoc-rel.html"><a href="assoc-rel.html#correlations-and-associations"><i class="fa fa-check"></i><b>5.1</b> Correlations and Associations</a></li>
<li class="chapter" data-level="5.2" data-path="assoc-rel.html"><a href="assoc-rel.html#introducing-nonlinear-associations"><i class="fa fa-check"></i><b>5.2</b> Introducing Nonlinear Associations</a></li>
<li class="chapter" data-level="5.3" data-path="assoc-rel.html"><a href="assoc-rel.html#regression"><i class="fa fa-check"></i><b>5.3</b> Regression</a></li>
<li class="chapter" data-level="5.4" data-path="assoc-rel.html"><a href="assoc-rel.html#multiple-regression"><i class="fa fa-check"></i><b>5.4</b> Multiple Regression</a></li>
<li class="chapter" data-level="5.5" data-path="assoc-rel.html"><a href="assoc-rel.html#visualizing-multiple-regression"><i class="fa fa-check"></i><b>5.5</b> Visualizing Multiple Regression</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="uncertainty.html"><a href="uncertainty.html"><i class="fa fa-check"></i><b>6</b> Beginning to Understand Uncertainty</a>
<ul>
<li class="chapter" data-level="6.1" data-path="uncertainty.html"><a href="uncertainty.html#demonstration-sampling-from-a-known-population"><i class="fa fa-check"></i><b>6.1</b> Demonstration: Sampling from a ‘Known’ Population</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="bootstrap.html"><a href="bootstrap.html"><i class="fa fa-check"></i><b>7</b> Introduction to Bootstrapping</a>
<ul>
<li class="chapter" data-level="7.1" data-path="bootstrap.html"><a href="bootstrap.html#bootstrapping-in-the-context-of-previous-examples"><i class="fa fa-check"></i><b>7.1</b> Bootstrapping in the Context of Previous Examples</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="bootstrap.html"><a href="bootstrap.html#bootstrapping-the-original-sample"><i class="fa fa-check"></i><b>7.1.1</b> Bootstrapping the Original Sample</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="bootstrap.html"><a href="bootstrap.html#bootstrapping-other-stuff"><i class="fa fa-check"></i><b>7.2</b> Bootstrapping Other Stuff…</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="bootstrap.html"><a href="bootstrap.html#correlations"><i class="fa fa-check"></i><b>7.2.1</b> Correlations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="t-test.html"><a href="t-test.html"><i class="fa fa-check"></i><b>8</b> T-Tests for Means</a>
<ul>
<li class="chapter" data-level="8.1" data-path="t-test.html"><a href="t-test.html#the-christmas-music-study"><i class="fa fa-check"></i><b>8.1</b> The Christmas Music Study</a></li>
<li class="chapter" data-level="8.2" data-path="t-test.html"><a href="t-test.html#independent-samples-t-test"><i class="fa fa-check"></i><b>8.2</b> Independent-Samples T-Test</a></li>
<li class="chapter" data-level="8.3" data-path="t-test.html"><a href="t-test.html#paired-sample-t-test"><i class="fa fa-check"></i><b>8.3</b> Paired-Sample T-test</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>9</b> Introduction to Probability</a>
<ul>
<li class="chapter" data-level="9.1" data-path="probability.html"><a href="probability.html#simulating-coin-flips"><i class="fa fa-check"></i><b>9.1</b> Simulating Coin Flips</a></li>
<li class="chapter" data-level="9.2" data-path="probability.html"><a href="probability.html#premier-league-goals-and-the-poisson-distribution"><i class="fa fa-check"></i><b>9.2</b> Premier League Goals and the Poisson Distribution</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="probability.html"><a href="probability.html#update"><i class="fa fa-check"></i><b>9.2.1</b> 2023 Update</a></li>
<li class="chapter" data-level="9.2.2" data-path="probability.html"><a href="probability.html#update-1"><i class="fa fa-check"></i><b>9.2.2</b> 2024 Update</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="statistics.html"><a href="statistics.html"><i class="fa fa-check"></i><b>10</b> Introduction to Statistics</a>
<ul>
<li class="chapter" data-level="10.1" data-path="statistics.html"><a href="statistics.html#the-distribution-of-sample-means-and-the-central-limit-theorem"><i class="fa fa-check"></i><b>10.1</b> The Distribution of Sample Means, and the Central Limit Theorem</a></li>
<li class="chapter" data-level="10.2" data-path="statistics.html"><a href="statistics.html#conf"><i class="fa fa-check"></i><b>10.2</b> Demonstrating Confidence Intervals</a></li>
<li class="chapter" data-level="10.3" data-path="statistics.html"><a href="statistics.html#rate-of-change-in-football-goals-per-season"><i class="fa fa-check"></i><b>10.3</b> Rate of Change in Football Goals per Season</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="H-testing.html"><a href="H-testing.html"><i class="fa fa-check"></i><b>11</b> Classical Statistical Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="11.1" data-path="H-testing.html"><a href="H-testing.html#salary-ztest"><i class="fa fa-check"></i><b>11.1</b> Testing a Real Hypothesis: Are WBS PhD Salaries Different?</a></li>
<li class="chapter" data-level="11.2" data-path="H-testing.html"><a href="H-testing.html#premier-league-goals-and-the-poisson-distribution-1"><i class="fa fa-check"></i><b>11.2</b> Premier League Goals and the Poisson Distribution</a></li>
<li class="chapter" data-level="11.3" data-path="H-testing.html"><a href="H-testing.html#correlation-significance-tests"><i class="fa fa-check"></i><b>11.3</b> Correlation Significance Tests</a></li>
<li class="chapter" data-level="11.4" data-path="H-testing.html"><a href="H-testing.html#regression-significance-tests"><i class="fa fa-check"></i><b>11.4</b> Regression Significance Tests</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ANOVA.html"><a href="ANOVA.html"><i class="fa fa-check"></i><b>12</b> ANOVA</a>
<ul>
<li class="chapter" data-level="12.1" data-path="ANOVA.html"><a href="ANOVA.html#post-hoc-testing"><i class="fa fa-check"></i><b>12.1</b> Post-Hoc Testing</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="Issues.html"><a href="Issues.html"><i class="fa fa-check"></i><b>13</b> Issues with Significance Testing</a>
<ul>
<li class="chapter" data-level="13.1" data-path="Issues.html"><a href="Issues.html#more-on-the-multiple-comparisons-problem"><i class="fa fa-check"></i><b>13.1</b> More on the Multiple Comparisons Problem</a></li>
<li class="chapter" data-level="13.2" data-path="Issues.html"><a href="Issues.html#the-bonferroni-correction-rate-of-change-in-football-goals-per-season"><i class="fa fa-check"></i><b>13.2</b> The Bonferroni Correction: Rate of Change in Football Goals per Season</a></li>
<li class="chapter" data-level="13.3" data-path="Issues.html"><a href="Issues.html#statistical-power-brief-demonstration"><i class="fa fa-check"></i><b>13.3</b> Statistical Power: Brief Demonstration</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">WBS MRes: Learning From Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ANOVA" class="section level1 hasAnchor" number="12">
<h1><span class="header-section-number">Chapter 12</span> ANOVA<a href="ANOVA.html#ANOVA" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This Chapter provides analysis and examples related to the second part of Lecture 8.</p>
<p>Let’s pick up exactly where Chapter <a href="t-test.html#t-test">8</a> left off. That chapter showed that people who did a boring proofreading task with Christmas music playing ended up more irritated than people who did the identical task in silence — but it couldn’t tell us whether that was really about <em>Christmas</em> music, or just about having background music of any kind playing while you’re bored. Silence was the only comparison available, so the design couldn’t separate the two explanations.</p>
<p>Study 2 fixes that by adding a third group: people who did the same task with background music that wasn’t Christmas music, but was matched to it on tempo and familiarity, so it isn’t a softer comparison to beat just because it’s blander. Now there are three groups — Silence, Other (music), and Christmas — which finally lets us ask the question Chapter <a href="t-test.html#t-test">8</a> left hanging: is it Christmas music specifically that’s the problem, or just having something playing in the background at all? Randomly assigning people to one of the three groups is exactly the confound-neutralising move from Chapter <a href="causation.html#causation">4</a> — it’s what lets this design pull the two explanations apart at all.</p>
<p>With three groups instead of two, running three separate t-tests would walk straight into the multiple comparisons problem (more on that in the next chapter). ANOVA instead tests whether there’s a difference among all three groups with a single significance test, which is where we’ll start.</p>
<pre><code>##        ID           GROUP    IRRIT_IRRITATED IRRIT_ANNOYED    IRRIT_TENSE   
##  Min.   : 1   Silence  :15   Min.   :1.000   Min.   :2.000   Min.   :2.000  
##  1st Qu.:12   Other    :15   1st Qu.:3.000   1st Qu.:3.000   1st Qu.:3.000  
##  Median :23   Christmas:15   Median :4.000   Median :4.000   Median :4.000  
##  Mean   :23                  Mean   :4.133   Mean   :3.978   Mean   :4.111  
##  3rd Qu.:34                  3rd Qu.:5.000   3rd Qu.:5.000   3rd Qu.:5.000  
##  Max.   :45                  Max.   :7.000   Max.   :7.000   Max.   :7.000  
##   IRRIT_ONEDGE       IRRIT      
##  Min.   :1.000   Min.   :1.500  
##  1st Qu.:3.000   1st Qu.:3.500  
##  Median :4.000   Median :4.000  
##  Mean   :3.756   Mean   :3.994  
##  3rd Qu.:5.000   3rd Qu.:4.750  
##  Max.   :6.000   Max.   :6.250</code></pre>
<pre><code>## # A tibble: 6 × 7
##      ID GROUP   IRRIT_IRRITATED IRRIT_ANNOYED IRRIT_TENSE IRRIT_ONEDGE IRRIT
##   &lt;dbl&gt; &lt;fct&gt;             &lt;dbl&gt;         &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt;
## 1     1 Silence               3             4           2            5  3.5 
## 2     2 Silence               3             3           4            3  3.25
## 3     3 Silence               3             3           3            3  3   
## 4     4 Silence               5             4           4            4  4.25
## 5     5 Silence               4             2           4            3  3.25
## 6     6 Silence               3             2           3            3  2.75</code></pre>
<p>Let’s create a quick table of the group means, and visualize it with a simple boxplot of the groups.</p>
<pre><code>## # A tibble: 3 × 5
##   GROUP     variable     n  mean    sd
##   &lt;fct&gt;     &lt;fct&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Silence   IRRIT       15  3.28 0.807
## 2 Other     IRRIT       15  3.87 0.661
## 3 Christmas IRRIT       15  4.83 0.88</code></pre>
<p><img src="LFD_files/figure-html/unnamed-chunk-162-1.png" alt="" width="672" /></p>
<p>Interesting picture. Silence is our baseline, Other is the matched background music without any Christmas content, and Christmas is, well, Christmas music. This is what we might call ‘model-free’ analysis. We are just looking at the data to see if intuitively it looks like we expect it to.</p>
<p>Let’s run an ANOVA now, which places a statistical model on it, and tests whether or not the data supports the model.</p>
<pre><code>## ANOVA Table (type II tests)
## 
##   Effect DFn DFd      F        p p&lt;.05   ges
## 1  GROUP   2  42 14.822 1.35e-05     * 0.414</code></pre>
<p>Results here suggest there is a significant effect (p-value is very small). We also have an <em>effect size</em> measure (‘ges’, or generalized eta-squared) which is very useful to us, and suggests the effect is quite large. This can be interpreted similarly to a regression coefficient (which is also an effect size measure), and is the amount of variance in the dependent variable (irritation) that is explained by group membership.</p>
<p>However, ANOVA only tests the <em>general effect</em> of the treatment / group. We don’t know whether this is because of the difference between <strong>all of the groups</strong>, or only <strong>some</strong>. If it’s background music <em>in general</em> that’s irritating, we’d expect Silence to differ from both Other and Christmas, but Other and Christmas to look much the same as each other. If it’s <em>Christmas music specifically</em>, we’d expect the opposite pattern: Christmas differs from both Silence and Other, but Silence and Other look much the same as each other. Only a post-hoc comparison of every pair can tell us which of these it actually is.</p>
<div id="post-hoc-testing" class="section level2 hasAnchor" number="12.1">
<h2><span class="header-section-number">12.1</span> Post-Hoc Testing<a href="ANOVA.html#post-hoc-testing" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can investigate this using <strong>post-hoc tests</strong>, which compare the difference between each pair of groups. There are many different types of post-hoc test for ANOVA, but the most typical one to use is the Tukey’s test, which is what we will do here.</p>
<pre><code>## # A tibble: 3 × 9
##   term  group1  group2    null.value estimate conf.low conf.high      p.adj
## * &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
## 1 GROUP Silence Other              0    0.583   -0.115      1.28 0.118     
## 2 GROUP Silence Christmas          0    1.55     0.851      2.25 0.00000878
## 3 GROUP Other   Christmas          0    0.967    0.268      1.67 0.00464   
## # ℹ 1 more variable: p.adj.signif &lt;chr&gt;</code></pre>
<p>We can actually plot these results in a really effective way:</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-165-1.png" alt="" width="672" /></p>
<p>This is the <em>Christmas-specifically</em> pattern from a moment ago: Christmas differs clearly from both Silence and Other, and Silence and Other don’t differ significantly from each other (p = .118). Taken at face value, that looks like a clean answer — it really is something about Christmas music, not background music in general.</p>
<p>But look at the Silence-vs-Other comparison a bit more carefully, because this is exactly the case that a bare significant/not-significant reading undersells. Its 95% confidence interval is -0.12 to 1.28. That interval <em>only just</em> crosses zero — the lower bound is a hair’s breadth into negative territory. Reading “not significant” as “proven: no difference” throws away exactly the information the interval is offering, which is that the data are entirely compatible with a real, positive difference too; there just isn’t enough precision at n = 15 per group to rule zero out. A p-value collapses that whole interval down to one bit of information, pass or fail, and right at a boundary this close, that’s precisely where the collapse costs you the most. I’d want a bigger sample before I’d rule out <em>any</em> effect of background music in general — this result argues for “Christmas specifically, at least as far as we can tell from here,” not “definitely, only Christmas, case closed.”</p>
<p>However, this type of post-hoc analysis has the potential for what is known as a <em>multiple comparisons problem</em>, which we might need to deal with.</p>
<p>Let’s take a look <strong>back in the slide deck…</strong></p>
<p>Remember, there are many other things that if we were doing ANOVA that we would also look to deal with - such as the various assumptions required of ANOVA, and so forth. But, they are beyond our scope in this class. Suffice to say that this has only scratched the surface of ANOVA so far.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="H-testing.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="Issues.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/profnicklee/MRes_LFD_Book/edit/main/11-ANOVA.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["LFD.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
