<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Describing the World With Data | WBS MRes: Learning From Data</title>
  <meta name="description" content="This book contains the examples and notes for the WBS MRes Learning From Data Course." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Describing the World With Data | WBS MRes: Learning From Data" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This book contains the examples and notes for the WBS MRes Learning From Data Course." />
  <meta name="github-repo" content="profnicklee/MRes_LFD_Book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Describing the World With Data | WBS MRes: Learning From Data" />
  
  <meta name="twitter:description" content="This book contains the examples and notes for the WBS MRes Learning From Data Course." />
  

<meta name="author" content="Professor Nick Lee" />


<meta name="date" content="2026-09-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="norm-dist.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">WBS MRes: Learning From Data</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction and Orientation</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Describing the World With Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#risk"><i class="fa fa-check"></i><b>2.1</b> When the numbers mislead: relative and absolute risk</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#summarizing-data-with-numbers"><i class="fa fa-check"></i><b>2.2</b> Summarizing Data with Numbers</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#box-plots"><i class="fa fa-check"></i><b>2.3</b> Box Plots</a></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#violin-plots-and-ridge-plots"><i class="fa fa-check"></i><b>2.4</b> Violin Plots and Ridge Plots</a></li>
<li class="chapter" data-level="2.5" data-path="intro.html"><a href="intro.html#transformations"><i class="fa fa-check"></i><b>2.5</b> Transformations</a></li>
<li class="chapter" data-level="2.6" data-path="intro.html"><a href="intro.html#intro-reading"><i class="fa fa-check"></i><b>2.6</b> Reading the literature</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="intro.html"><a href="intro.html#where-youll-meet-this"><i class="fa fa-check"></i><b>2.6.1</b> Where you’ll meet this</a></li>
<li class="chapter" data-level="2.6.2" data-path="intro.html"><a href="intro.html#the-connection-back"><i class="fa fa-check"></i><b>2.6.2</b> The connection back</a></li>
<li class="chapter" data-level="2.6.3" data-path="intro.html"><a href="intro.html#questions-worth-asking"><i class="fa fa-check"></i><b>2.6.3</b> Questions worth asking</a></li>
<li class="chapter" data-level="2.6.4" data-path="intro.html"><a href="intro.html#one-red-flag"><i class="fa fa-check"></i><b>2.6.4</b> One red flag</a></li>
<li class="chapter" data-level="2.6.5" data-path="intro.html"><a href="intro.html#if-you-want-to-read-more"><i class="fa fa-check"></i><b>2.6.5</b> If you want to read more</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="norm-dist.html"><a href="norm-dist.html"><i class="fa fa-check"></i><b>3</b> The Normal Distribution</a>
<ul>
<li class="chapter" data-level="3.1" data-path="norm-dist.html"><a href="norm-dist.html#a-simple-demonstration-of-the-normal-distribution"><i class="fa fa-check"></i><b>3.1</b> A Simple Demonstration of the Normal Distribution</a></li>
<li class="chapter" data-level="3.2" data-path="norm-dist.html"><a href="norm-dist.html#what-actually-is-a-normal-distribution"><i class="fa fa-check"></i><b>3.2</b> What Actually is a Normal Distribution?</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="causation.html"><a href="causation.html"><i class="fa fa-check"></i><b>4</b> Causation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="causation.html"><a href="causation.html#confounding"><i class="fa fa-check"></i><b>4.1</b> Confounding</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="causation.html"><a href="causation.html#the-cornfield-test"><i class="fa fa-check"></i><b>4.1.1</b> The Cornfield Test</a></li>
<li class="chapter" data-level="4.1.2" data-path="causation.html"><a href="causation.html#confounding-demo"><i class="fa fa-check"></i><b>4.1.2</b> The Everyday Version</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="causation.html"><a href="causation.html#selection-bias"><i class="fa fa-check"></i><b>4.2</b> Selection Bias</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="causation.html"><a href="causation.html#all-the-data-isnt-all-the-data"><i class="fa fa-check"></i><b>4.2.1</b> All the Data Isn’t All the Data</a></li>
<li class="chapter" data-level="4.2.2" data-path="causation.html"><a href="causation.html#manufacturing-a-relationship-from-nothing"><i class="fa fa-check"></i><b>4.2.2</b> Manufacturing a Relationship from Nothing</a></li>
<li class="chapter" data-level="4.2.3" data-path="causation.html"><a href="causation.html#selection-feels-different"><i class="fa fa-check"></i><b>4.2.3</b> Why selection feels different</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="causation.html"><a href="causation.html#endogeneity"><i class="fa fa-check"></i><b>4.3</b> Endogeneity</a></li>
<li class="chapter" data-level="4.4" data-path="causation.html"><a href="causation.html#the-power-of-randomisation"><i class="fa fa-check"></i><b>4.4</b> The Power of Randomisation</a></li>
<li class="chapter" data-level="4.5" data-path="causation.html"><a href="causation.html#causation-reading"><i class="fa fa-check"></i><b>4.5</b> Reading the literature</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="causation.html"><a href="causation.html#where-youll-meet-this-1"><i class="fa fa-check"></i><b>4.5.1</b> Where you’ll meet this</a></li>
<li class="chapter" data-level="4.5.2" data-path="causation.html"><a href="causation.html#the-connection-back-1"><i class="fa fa-check"></i><b>4.5.2</b> The connection back</a></li>
<li class="chapter" data-level="4.5.3" data-path="causation.html"><a href="causation.html#questions-worth-asking-1"><i class="fa fa-check"></i><b>4.5.3</b> Questions worth asking</a></li>
<li class="chapter" data-level="4.5.4" data-path="causation.html"><a href="causation.html#one-red-flag-1"><i class="fa fa-check"></i><b>4.5.4</b> One red flag</a></li>
<li class="chapter" data-level="4.5.5" data-path="causation.html"><a href="causation.html#if-you-want-to-read-more-1"><i class="fa fa-check"></i><b>4.5.5</b> If you want to read more</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="assoc-rel.html"><a href="assoc-rel.html"><i class="fa fa-check"></i><b>5</b> Associations and Relationships</a>
<ul>
<li class="chapter" data-level="5.1" data-path="assoc-rel.html"><a href="assoc-rel.html#correlations-and-associations"><i class="fa fa-check"></i><b>5.1</b> Correlations and Associations</a></li>
<li class="chapter" data-level="5.2" data-path="assoc-rel.html"><a href="assoc-rel.html#introducing-nonlinear-associations"><i class="fa fa-check"></i><b>5.2</b> Introducing Nonlinear Associations</a></li>
<li class="chapter" data-level="5.3" data-path="assoc-rel.html"><a href="assoc-rel.html#regression"><i class="fa fa-check"></i><b>5.3</b> Regression</a></li>
<li class="chapter" data-level="5.4" data-path="assoc-rel.html"><a href="assoc-rel.html#multiple-regression"><i class="fa fa-check"></i><b>5.4</b> Multiple Regression</a></li>
<li class="chapter" data-level="5.5" data-path="assoc-rel.html"><a href="assoc-rel.html#visualizing-multiple-regression"><i class="fa fa-check"></i><b>5.5</b> Visualizing Multiple Regression</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="uncertainty.html"><a href="uncertainty.html"><i class="fa fa-check"></i><b>6</b> Beginning to Understand Uncertainty</a>
<ul>
<li class="chapter" data-level="6.1" data-path="uncertainty.html"><a href="uncertainty.html#demonstration-sampling-from-a-known-population"><i class="fa fa-check"></i><b>6.1</b> Demonstration: Sampling from a ‘Known’ Population</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="bootstrap.html"><a href="bootstrap.html"><i class="fa fa-check"></i><b>7</b> Introduction to Bootstrapping</a>
<ul>
<li class="chapter" data-level="7.1" data-path="bootstrap.html"><a href="bootstrap.html#bootstrapping-in-the-context-of-previous-examples"><i class="fa fa-check"></i><b>7.1</b> Bootstrapping in the Context of Previous Examples</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="bootstrap.html"><a href="bootstrap.html#bootstrapping-the-original-sample"><i class="fa fa-check"></i><b>7.1.1</b> Bootstrapping the Original Sample</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="bootstrap.html"><a href="bootstrap.html#bootstrapping-other-stuff"><i class="fa fa-check"></i><b>7.2</b> Bootstrapping Other Stuff…</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="bootstrap.html"><a href="bootstrap.html#correlations"><i class="fa fa-check"></i><b>7.2.1</b> Correlations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="t-test.html"><a href="t-test.html"><i class="fa fa-check"></i><b>8</b> T-Tests for Means</a>
<ul>
<li class="chapter" data-level="8.1" data-path="t-test.html"><a href="t-test.html#the-christmas-music-study"><i class="fa fa-check"></i><b>8.1</b> The Christmas Music Study</a></li>
<li class="chapter" data-level="8.2" data-path="t-test.html"><a href="t-test.html#independent-samples-t-test"><i class="fa fa-check"></i><b>8.2</b> Independent-Samples T-Test</a></li>
<li class="chapter" data-level="8.3" data-path="t-test.html"><a href="t-test.html#paired-sample-t-test"><i class="fa fa-check"></i><b>8.3</b> Paired-Sample T-test</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>9</b> Introduction to Probability</a>
<ul>
<li class="chapter" data-level="9.1" data-path="probability.html"><a href="probability.html#simulating-coin-flips"><i class="fa fa-check"></i><b>9.1</b> Simulating Coin Flips</a></li>
<li class="chapter" data-level="9.2" data-path="probability.html"><a href="probability.html#premier-league-goals-and-the-poisson-distribution"><i class="fa fa-check"></i><b>9.2</b> Premier League Goals and the Poisson Distribution</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="probability.html"><a href="probability.html#update"><i class="fa fa-check"></i><b>9.2.1</b> 2023 Update</a></li>
<li class="chapter" data-level="9.2.2" data-path="probability.html"><a href="probability.html#update-1"><i class="fa fa-check"></i><b>9.2.2</b> 2024 Update</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="statistics.html"><a href="statistics.html"><i class="fa fa-check"></i><b>10</b> Introduction to Statistics</a>
<ul>
<li class="chapter" data-level="10.1" data-path="statistics.html"><a href="statistics.html#the-distribution-of-sample-means-and-the-central-limit-theorem"><i class="fa fa-check"></i><b>10.1</b> The Distribution of Sample Means, and the Central Limit Theorem</a></li>
<li class="chapter" data-level="10.2" data-path="statistics.html"><a href="statistics.html#conf"><i class="fa fa-check"></i><b>10.2</b> Demonstrating Confidence Intervals</a></li>
<li class="chapter" data-level="10.3" data-path="statistics.html"><a href="statistics.html#rate-of-change-in-football-goals-per-season"><i class="fa fa-check"></i><b>10.3</b> Rate of Change in Football Goals per Season</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="H-testing.html"><a href="H-testing.html"><i class="fa fa-check"></i><b>11</b> Classical Statistical Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="11.1" data-path="H-testing.html"><a href="H-testing.html#salary-ztest"><i class="fa fa-check"></i><b>11.1</b> Testing a Real Hypothesis: Are WBS PhD Salaries Different?</a></li>
<li class="chapter" data-level="11.2" data-path="H-testing.html"><a href="H-testing.html#premier-league-goals-and-the-poisson-distribution-1"><i class="fa fa-check"></i><b>11.2</b> Premier League Goals and the Poisson Distribution</a></li>
<li class="chapter" data-level="11.3" data-path="H-testing.html"><a href="H-testing.html#correlation-significance-tests"><i class="fa fa-check"></i><b>11.3</b> Correlation Significance Tests</a></li>
<li class="chapter" data-level="11.4" data-path="H-testing.html"><a href="H-testing.html#regression-significance-tests"><i class="fa fa-check"></i><b>11.4</b> Regression Significance Tests</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ANOVA.html"><a href="ANOVA.html"><i class="fa fa-check"></i><b>12</b> ANOVA</a>
<ul>
<li class="chapter" data-level="12.1" data-path="ANOVA.html"><a href="ANOVA.html#post-hoc-testing"><i class="fa fa-check"></i><b>12.1</b> Post-Hoc Testing</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="Issues.html"><a href="Issues.html"><i class="fa fa-check"></i><b>13</b> Issues with Significance Testing</a>
<ul>
<li class="chapter" data-level="13.1" data-path="Issues.html"><a href="Issues.html#more-on-the-multiple-comparisons-problem"><i class="fa fa-check"></i><b>13.1</b> More on the Multiple Comparisons Problem</a></li>
<li class="chapter" data-level="13.2" data-path="Issues.html"><a href="Issues.html#the-bonferroni-correction-rate-of-change-in-football-goals-per-season"><i class="fa fa-check"></i><b>13.2</b> The Bonferroni Correction: Rate of Change in Football Goals per Season</a></li>
<li class="chapter" data-level="13.3" data-path="Issues.html"><a href="Issues.html#statistical-power-brief-demonstration"><i class="fa fa-check"></i><b>13.3</b> Statistical Power: Brief Demonstration</a></li>
<li class="chapter" data-level="13.4" data-path="Issues.html"><a href="Issues.html#p-hacking-sim"><i class="fa fa-check"></i><b>13.4</b> How to find an effect that isn’t there</a></li>
<li class="chapter" data-level="13.5" data-path="Issues.html"><a href="Issues.html#issues-reading"><i class="fa fa-check"></i><b>13.5</b> Reading the literature</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="Issues.html"><a href="Issues.html#where-youll-meet-this-2"><i class="fa fa-check"></i><b>13.5.1</b> Where you’ll meet this</a></li>
<li class="chapter" data-level="13.5.2" data-path="Issues.html"><a href="Issues.html#the-connection-back-2"><i class="fa fa-check"></i><b>13.5.2</b> The connection back</a></li>
<li class="chapter" data-level="13.5.3" data-path="Issues.html"><a href="Issues.html#questions-worth-asking-2"><i class="fa fa-check"></i><b>13.5.3</b> Questions worth asking</a></li>
<li class="chapter" data-level="13.5.4" data-path="Issues.html"><a href="Issues.html#one-red-flag-2"><i class="fa fa-check"></i><b>13.5.4</b> One red flag</a></li>
<li class="chapter" data-level="13.5.5" data-path="Issues.html"><a href="Issues.html#if-you-want-to-read-more-2"><i class="fa fa-check"></i><b>13.5.5</b> If you want to read more</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">WBS MRes: Learning From Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="intro" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Describing the World With Data<a href="intro.html#intro" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This Chapter is designed to work with Lecture 2.</p>
<p>Here, I will demonstrate a number of important concepts about data displays and descriptions.</p>
<p>First, let’s find some data to play with. In the following examples I will use some data from the Johns Hopkins Coronavirus Resource Center as at April 26 2022, which contains data by country about cases, deaths, and mortality for COVID.</p>
<p><a href="https://coronavirus.jhu.edu/" class="uri">https://coronavirus.jhu.edu/</a></p>
<p>However, as of 2023, the JHCRC ceased collecting data, and their archival data is available on their github:</p>
<p><a href="https://github.com/CSSEGISandData/COVID-19" class="uri">https://github.com/CSSEGISandData/COVID-19</a></p>
<p>However, I do think it would be quite hard to recreate the exact snapshot in time of the data set we are using here.</p>
<p>I’m going to use the top 20 countries in terms of raw number of cases</p>
<p>To demonstrate how we can easily change people’s views of a data set, let’s run some bar charts:</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-4-1.png" alt="" width="672" /></p>
<p>One thing we could do is change the orientation of the bars…</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-5-1.png" alt="" width="672" /></p>
<p>That’s nice. The basic conclusion we can draw is everyone is pretty much the same in terms of survival rate, although Mexico is a bit down.</p>
<p>Interestingly, it seems to me that the variation is more pronounced in this presentation where you look ‘down’ a line of results, than above where you look across. I’m not aware of any theory behind why, or even if anyone has ever noted that before, but it’s definitely something I noticed here.</p>
<p>Either way, if I wanted to make everyone think that COVID survival rates were really different, there’s a simple trick I could use:</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-6-1.png" alt="" width="672" /></p>
<p>Wow, how do you like that! What’s different?</p>
<p>Changing the scale of the y-axis is an old trick, and when used to manipulate opinion it’s a bad thing. However, there is a case to say we need to know what we want to say, before we decide how to say it. When does ‘making sure we see the right message’ move into ‘outright manipulation / misrepresentation?’.</p>
<p>Here’s another common way this type of data is presented in media and non-scientific reports:</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-7-1.png" alt="" width="672" /></p>
<p>or a variant:</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-8-1.png" alt="" width="672" /></p>
<p>Technically, it’s wrong to present this data in a line chart, because it is discrete values and does not represent a trend, but it is surprisingly common - probably because it ‘looks more sciency’…</p>
<p>Ironically, there is some logic behind using line charts with this sort of data, depending on what you are trying to get across - let’s move to excel to demonstrate…</p>
<p>While we’re at it, we’ll also look at pie charts…</p>
<p><strong><em>Quick transition to MS Excel, then back to the slides…</em></strong></p>
<div id="risk" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> When the numbers mislead: relative and absolute risk<a href="intro.html#risk" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Everything so far in this chapter has been about pictures that mislead: axes that start in the wrong place, baselines chosen to flatter. The same trick works with numbers alone, and it’s arguably more dangerous, because a number feels more objective than a picture. The example I use in the lecture is one I have a personal stake in.</p>
<p>A few years ago a set of headlines did the rounds suggesting that bacon, ham and sausages belonged in the same bracket as cigarettes. The research behind the most recent wave was a good study, in a good journal, using the UK Biobank, a huge and genuinely excellent dataset <span class="citation">(<a href="#ref-bradbury2020diet">Bradbury et al. 2020</a>)</span>. Its headline finding was that each extra 25 grams of processed meat a day was associated with a 19 percent higher risk of bowel (colorectal) cancer. I ate a ham sandwich pretty much every day for years, and as a parent I wanted to know whether I should care what my kids ate. So I did what I think anyone reading research should do, and worked through it step by step.</p>
<p><strong>First, is the amount realistic?</strong> The authors helpfully translate 25 grams into about one rasher of bacon or one slice of ham. That’s not an absurd dose like the ones behind some food scares. Plenty of people eat that much, so this is worth taking seriously.</p>
<p><strong>Second, is it causal?</strong> This is a correlational study, and Chapter <a href="causation.html#causation">4</a> will give you a whole toolkit for worrying about that. Maybe heavy processed-meat eaters also drink more, or move less, or eat fewer vegetables. The authors adjusted for a long list of such factors, and the association survived. More importantly, it sits within a much larger body of evidence that led the International Agency for Research on Cancer to classify processed meat as a cause of bowel cancer <span class="citation">(<a href="#ref-bouvard2015carcinogenicity"><span class="nocase">Bouvard et al.</span> 2015</a>)</span>. So let’s accept that the link is probably real.</p>
<p><strong>Third, 19 percent of what?</strong> This is the question the headlines skipped. A 19 percent increase is a <em>relative</em> risk: it tells you how much your existing risk goes up, not what your risk is. To turn it into something you can use, you need the <em>base rate</em>. In the UK, roughly 1 in 17 men and 1 in 20 women will be diagnosed with bowel cancer in their lifetime <span class="citation">(<a href="#ref-cruk2026bowel">Cancer Research UK 2026</a>)</span>, so call it about 6 in every 100 people. Add 19 percent to 6 and you get a little over 7. In <em>absolute</em> terms, then, the extra daily slice moves you from about 6 in 100 to about 7 in 100, as Figure <a href="intro.html#fig:risk-icon-array">2.1</a> shows.</p>
<div class="figure"><span style="display:block;" id="fig:risk-icon-array"></span>
<img src="LFD_files/figure-html/risk-icon-array-1.png" alt="The same result in absolute terms. Each dot is one person. A 19 percent increase in relative risk moves bowel cancer from about 6 in 100 people to about 7 in 100: one extra case (orange). Figures are rounded; see text." width="768" />
<p class="caption">
Figure 2.1: The same result in absolute terms. Each dot is one person. A 19 percent increase in relative risk moves bowel cancer from about 6 in 100 people to about 7 in 100: one extra case (orange). Figures are rounded; see text.
</p>
</div>
<p>Notice the language trap here. The risk went up by 19 <em>percent</em>, but by only about one <em>percentage point</em>. Both statements are true. Mixing them up is one of the most common errors in the whole of quantitative reporting, and you’ll see it made by journalists, managers, and, I’m sorry to say, academics.</p>
<p>Another way to say the same thing is this. If about 90 people each ate an extra slice of ham every day for the rest of their lives, we’d expect roughly one extra case of bowel cancer among them. That’s a rough translation. It stretches a result from about six years of follow-up across a lifetime, and it treats the population’s average risk as everyone’s starting point. But it is the right order of magnitude, and it tells you far more than “19 percent” does.</p>
<p><strong>Fourth, why the comparison with cigarettes?</strong> Processed meat and tobacco sit in the same IARC category. But that category describes how <em>strong the evidence</em> is that something causes cancer, not how <em>large</em> the risk is <span class="citation">(<a href="#ref-iarc2015qa">International Agency for Research on Cancer 2015</a>)</span>. For smoking, the numbers are in a different universe. Roughly 1 in 100 lifelong non-smokers in the UK will get lung cancer, compared with more than 20 in 100 people who smoke a pack a day <span class="citation">(<a href="#ref-smc2015expert">Science Media Centre 2015</a>)</span>. That’s a relative risk of around 20, which, as you’ll see in Chapter <a href="causation.html#causation">4</a>, is the kind of number that is very hard to explain away by confounding. Nineteen percent is a relative risk of 1.19.</p>
<p><strong>Finally, whose risk is it?</strong> Here it’s worth holding two ideas at once. For me, one extra case per 90 or so lifelong ham-eaters is a small risk, and I’m entitled to weigh it against how much I like a ham sandwich. The numbers can’t tell me how to make that trade. But across a whole country, small individual risks add up: Cancer Research UK estimates that around 13 percent of UK bowel cancer cases are caused by eating processed meat <span class="citation">(<a href="#ref-cruk2026bowel">Cancer Research UK 2026</a>)</span>. “Trivial for me” and “important for public health” can both be true, and a lot of confused arguments come from people talking about one while the other person is thinking about the other.</p>
<p>It’s also worth knowing that an average can hide a lot. In the Biobank study, the association with processed meat showed up in men but not in women. A single headline number describes a population, not a person, and certainly not you.</p>
</div>
<div id="summarizing-data-with-numbers" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Summarizing Data with Numbers<a href="intro.html#summarizing-data-with-numbers" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Above, we simply plotted a single variable of interest, and showed that some very basic changes to how it was displayed had the potential to ‘lead’ the reader to different conclusions. Even that simple tweaking is a powerful way to change opinion, and used in the wrong way can be very misleading.</p>
<p>Now, let’s think about the idea of an <em>even simpler</em> way to describe data - by summarizing it with just some numbers.</p>
<p>For this example, I am going to use data on GDP per head in 2020 for each nation, from the World Bank.</p>
<p>Before I do anything else, I’m going to graph it again. This time I will use a histogram, which is similar to a bar chart, but not the same thing.</p>
<p>Specifically, a bar chart is used when we are displaying discrete categories. So, above, we had 20 countries, and a single bar for each country.</p>
<p>A histogram is instead when we divide our data into ‘groups’ of similar values, which are called ‘bins’. Thus, each ‘bar’ on a histogram represents the number of elements (in this case, countries) which fall in that bin. So, in this case, we can divide the GDP variable into bins.</p>
<p>As an example, we can divide GDP per head into ‘bins’ of US$10000, and plot a histogram</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-10-1.png" alt="" width="672" /></p>
<p>As you can see, there are nearly 120 countries in the first bin, which you can also see runs from -5000 to 5000 dollars. Of course, we know there are no countries with negative GDP per head, but this is just an artefact of the binning process.</p>
<p>This sort of chart gives us something very different to a bar chart. Instead, it is really a <strong>frequency distribution</strong>, and it charts the frequency of values of a given variable - in this case GDP per head.</p>
<p>So, here we have some idea of the <strong>distribution</strong> of the variable. It’s clearly skewed quite heavily, with some outliers at the high end.</p>
<p>Let’s move on to summarize this variable with some numbers:</p>
<pre><code>## 
##                     GDP2020
## --------------- -----------
##            Mean    15162.61
##         Std.Dev    22146.53
##             Min      233.84
##          Median     6117.49
##             Max   173688.19
##         N.Valid      251.00
##               N      266.00
##       Pct.Valid       94.36</code></pre>
<p>What we have here are the classic ‘summary statistics’ for 2020 GDP per head.</p>
<p>One thing missing - which admittedly is not very useful in this case, is the Mode, or the ‘most frequent’ value.</p>
<pre><code>## [1] 1875.441</code></pre>
<p>There you have it, the mode is 1875.441.</p>
<p>One important thing to note here is that the word <strong>average</strong> is badly misused when talking about data. Specifically, the <em>mean</em>, <em>median</em>, and <em>mode</em> can all at one time or the other be referred to as the <strong>average</strong> value of a given variable. But, as you can see, they are all different numbers! The word ‘average’ is a very vague word to use in this context, so do be careful about when you use it. You should always default to using the specific term you are talking about.</p>
<p>A few other summary statistics are calculated for 2020 GDPph below</p>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA&#39;s 
##    233.8   2127.5   6117.5  15162.6  18072.4 173688.2       15</code></pre>
<pre><code>## [1] 15944.94</code></pre>
<pre><code>## [1] 173454.4</code></pre>
<p>What we have here now includes the range (173454.4) and the interquartile range (15944.94), which are both useful measures of how ‘spread out’ the data is.</p>
<p>Each of the summary numbers above has strengths and weaknesses when describing different types of data. Here, we will mainly talk about the sensistivity to outliers.</p>
<p>Specifically, the <strong>median</strong> and <strong>interquartile range</strong> are less sensitive to outliers as measures of central tendency and range respectively than their counterparts the <strong>mean</strong> and the <strong>range</strong>. So, that’s why you commonly see the median used so frequently in these sorts of situations.</p>
<p>But, what do we mean by outliers? Let’s look at this in the context of another graphical display, the <strong>box plot</strong>.</p>
</div>
<div id="box-plots" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Box Plots<a href="intro.html#box-plots" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The box plot (and the other displays below) are criminally underused in my opinion. Most of us calculate a box plot at school, and then never again. But, it’s a really useful way to understand a data set.</p>
<p>Let’s do a boxplot for the 2020 GDPph data:</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-14-1.png" alt="" width="672" /></p>
<p>A box plot presents a lot of information very efficiently. The <strong>median</strong> is the thick horizontal, the white rectangle is bounded by the <strong>interquartile range</strong>, and outliers are represented as dots.</p>
<p>We can see here that the data is very skewed, and there are some very significant outliers at the high end (no prizes for guessing which countries they are).</p>
<p>A weakness of a box plot is that it doesn’t actually show the distribution of the data. One way to do this is to add what is called <em>jitter</em>, which actually plots the values of each case, with a ‘jitter’ to avoid overlapping identical values.</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-15-1.png" alt="" width="672" /></p>
<p>So, we can see here that most of the data is clustered towards the bottom of the range - i.e. very low GDPph. This is of course the same conclusion as the historgram allowed us to draw. But, the box plot also gives us plenty of <em>other</em> information about the variable.</p>
<p>Even so, while box plots are nice, they can also obscure important facts about the distribution. Adding the jitter helps, but there are other ways to display this type of data that make the distribution more obvious.</p>
</div>
<div id="violin-plots-and-ridge-plots" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Violin Plots and Ridge Plots<a href="intro.html#violin-plots-and-ridge-plots" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Here, I’m going to give you a set of <em>even more underused</em> data displays, which can show some powerful things about variables.</p>
<p>In order to do so, I am going to simulate some data, to make sure it has exactly the features I want to show.</p>
<p>First, let’s create the data and use box plots to display it, such as you are already experienced with above.</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-16-1.png" alt="" width="672" /></p>
<p>That’s all very well, but as we know, this can obsure the distribution. So, let’s add jitter:</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-17-1.png" alt="" width="672" /></p>
<p>Well, look at that. B has what is called a <em>bimodal</em> distribution.</p>
<p>Lets look at what is called a <strong>violin plot</strong> to emphasize this:</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-18-1.png" alt="" width="672" /></p>
<p>Neat! You can see how the violin plot really emphasizes the differences in the distributions, which are totally obscured by the box plots, and only partially shown by adding the jitter.</p>
<p>Another way to visualize this is with <strong>ridges</strong>, which basically compare the distributions of variables together:</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-19-1.png" alt="" width="672" /></p>
<p>These are really cool in my view. And, if you are asking me, my preference in this type of situation would be to combine jittered box plots, which show the basics, and emphasize the outliers and summary numbers, with ridge plots, which show a really nice visualization of the distributions of each variable. Taken together, these plots allow us to understand a surprisingly large amount of important information about variables.</p>
<p>OK, let’s move back to the slides to discuss another crucially important concept related to data distributions: <strong>transformations</strong>.</p>
<p><strong><em>Back to slide deck</em></strong></p>
</div>
<div id="transformations" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Transformations<a href="intro.html#transformations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="LFD_files/figure-html/unnamed-chunk-20-1.png" alt="" width="672" /></p>
<p>As you can see, the data is heavily skewed, or ‘squished’ towards the bottom. This makes it hard to see any patterns by eye.</p>
<p>We can make it easier to interpret by <em>transforming the variable</em>. Here, using a logarithmic transform.</p>
<p>Let’s run the box again:</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-22-1.png" alt="" width="672" /></p>
<p>Nice, see how the spread is easier to interpret here? Log transforms are essentially ‘inverse exponentials’, so what they do is bring down extreme high outliers.</p>
<p>Let’s see this in some more plots:</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-23-1.png" alt="" width="672" /></p>
<p><img src="LFD_files/figure-html/unnamed-chunk-24-1.png" alt="" width="672" /></p>
<p>Compare the violin of the log transformed variable with the original:</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-25-1.png" alt="" width="672" /></p>
<p>In fact, we can use the log transform to revisit some of our COVID data back in EXCEL…</p>
<p><strong><em>Quick transition to MS Excel, then back to slides…</em></strong></p>
</div>
<div id="intro-reading" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Reading the literature<a href="intro.html#intro-reading" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The bacon example comes from medicine, but the trap it illustrates is everywhere in management research. Almost every effect you’ll read about is reported <em>relative to something</em>, and the something is often left out, buried in a table, or never mentioned at all.</p>
<div id="where-youll-meet-this" class="section level3 hasAnchor" number="2.6.1">
<h3><span class="header-section-number">2.6.1</span> Where you’ll meet this<a href="intro.html#where-youll-meet-this" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Ratios.</strong> Relative risks, <em>odds ratios</em> and <em>hazard ratios</em> all appear in management papers, usually from models predicting whether something happens: an employee leaves, a firm adopts a practice, a customer churns. Every one of them is a relative number, so every one of them needs a base rate before it means anything. A hazard ratio of 1.5 for employee turnover means one thing if the baseline is 30 percent a year and something much smaller if it’s 1 percent.</p>
<p>Odds ratios need extra care. When the outcome is rare, an odds ratio and a relative risk are almost the same, which is why people swap them freely. When the outcome is common, which many management outcomes are, the odds ratio exaggerates. Suppose turnover is 40 percent in one group and 50 percent in another. The relative risk is 1.25: the second group is a quarter more likely to leave. The odds ratio is 1.5. Same data, and the number that sounds 50 percent bigger is the one that gets reported <span class="citation">(<a href="#ref-zhang1998relative">Zhang and Yu 1998</a>)</span>.</p>
<p><strong>Percent versus percentage points.</strong> Conversion rates, response rates, market shares and turnover rates are all percentages already, so changes in them can be described either way. A conversion rate going from 2 to 3 percent is a one-point increase and a 50 percent increase. Both are true, and a paper (or a consultant’s slide deck) will usually pick whichever sounds better for the argument being made.</p>
<p><strong>Percentage effects from models.</strong> When a model uses the logarithm of an outcome such as sales or salary, its coefficients are usually read as percentage changes. They’re relative by construction, so the same question applies: a percentage of what? A 10 percent sales uplift means something very different for a corner shop than for a supermarket chain.</p>
<p><strong>Standardised effect sizes.</strong> Cohen’s <em>d</em> and standardised regression coefficients express an effect relative to the spread of the data rather than in its natural units. They have real uses, and you’ll meet them properly in Chapter <a href="t-test.html#t-test">8</a>. But they share the weakness of all relative numbers: a “medium” standardised effect can be large or trivial in pounds, days or customers. Good papers translate back into natural units. It’s worth noticing when they don’t.</p>
<p><strong>Pictures in papers.</strong> Everything earlier in this chapter applies to journal figures too. Watch especially for bar charts of means on a 1-to-7 rating scale whose axis starts at 4, and for interaction plots where two lines diverge dramatically across a range of barely a scale point.</p>
</div>
<div id="the-connection-back" class="section level3 hasAnchor" number="2.6.2">
<h3><span class="header-section-number">2.6.2</span> The connection back<a href="intro.html#the-connection-back" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A truncated axis and a relative risk are the same trick. Each shows you a comparison with its anchor removed. The axis hides where zero is, and the relative risk hides the base rate. The defence is identical in both cases: go and find the anchor before you decide how impressed to be.</p>
</div>
<div id="questions-worth-asking" class="section level3 hasAnchor" number="2.6.3">
<h3><span class="header-section-number">2.6.3</span> Questions worth asking<a href="intro.html#questions-worth-asking" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><strong>Is this a relative or an absolute number?</strong> If it’s relative, where is the base rate?</li>
<li><strong>Percent or percentage points?</strong> Which one did the authors choose to put in the abstract, and why?</li>
<li><strong>Is it an odds ratio for a common outcome?</strong> If so, the effect is probably smaller than it sounds.</li>
<li><strong>What does it mean in natural units?</strong> Pounds, days, people, customers. If the authors never say, can you work it out from their descriptives table?</li>
<li><strong>Whose risk is this?</strong> An average across a population can hide groups where the effect is much larger, and groups where it’s absent. And a small effect on each person can still add up to a large effect across a population, or the other way round.</li>
</ol>
</div>
<div id="one-red-flag" class="section level3 hasAnchor" number="2.6.4">
<h3><span class="header-section-number">2.6.4</span> One red flag<a href="intro.html#one-red-flag" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The abstract that reports only the relative effect: “increased the likelihood of turnover by 50 percent,” with the base rate nowhere in sight. It’s not always an attempt to mislead, since journal word limits are real. But authors know which framing sounds more impressive, and a paper whose headline number only works without its anchor is telling you something. Go to the descriptives, find the base rate, and do the arithmetic from this chapter yourself. It rarely takes more than a minute.</p>
</div>
<div id="if-you-want-to-read-more" class="section level3 hasAnchor" number="2.6.5">
<h3><span class="header-section-number">2.6.5</span> If you want to read more<a href="intro.html#if-you-want-to-read-more" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>David Spiegelhalter’s <em>The Art of Statistics</em> <span class="citation">(<a href="#ref-spiegelhalter2019art">Spiegelhalter 2019</a>)</span> is the best general book I know on reading numbers sensibly, and it was Spiegelhalter’s explanation of the bacon story that first got me thinking about it properly. Gerd Gigerenzer’s <em>Reckoning with Risk</em> <span class="citation">(<a href="#ref-gigerenzer2002reckoning">Gigerenzer 2002</a>)</span> is older but still the classic on why relative risks mislead, and on how much clearer things get once you switch to natural frequencies like “7 in 100.”</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-bouvard2015carcinogenicity" class="csl-entry">
<span class="nocase">Bouvard, Véronique, Dana Loomis, Kathryn Z. Guyton, et al.</span> 2015. <span>“Carcinogenicity of Consumption of Red and Processed Meat.”</span> <em>The Lancet Oncology</em> 16 (16): 1599–600.
</div>
<div id="ref-bradbury2020diet" class="csl-entry">
Bradbury, Kathryn E., Neil Murphy, and Timothy J. Key. 2020. <span>“Diet and Colorectal Cancer in <span>UK Biobank</span>: A Prospective Study.”</span> <em>International Journal of Epidemiology</em> 49 (1): 246–58. <a href="https://doi.org/10.1093/ije/dyz064">https://doi.org/10.1093/ije/dyz064</a>.
</div>
<div id="ref-cruk2026bowel" class="csl-entry">
Cancer Research UK. 2026. <em>Bowel Cancer Risk</em>. <a href="https://www.cancerresearchuk.org/health-professional/cancer-statistics/statistics-by-cancer-type/bowel-cancer/risk-factors" class="uri">Https://www.cancerresearchuk.org/health-professional/cancer-statistics/statistics-by-cancer-type/bowel-cancer/risk-factors</a>.
</div>
<div id="ref-gigerenzer2002reckoning" class="csl-entry">
Gigerenzer, Gerd. 2002. <em>Reckoning with Risk: Learning to Live with Uncertainty</em>. Allen Lane.
</div>
<div id="ref-iarc2015qa" class="csl-entry">
International Agency for Research on Cancer. 2015. <em>Cancer: Carcinogenicity of the Consumption of Red Meat and Processed Meat</em>. <a href="https://www.who.int/news-room/questions-and-answers/item/cancer-carcinogenicity-of-the-consumption-of-red-meat-and-processed-meat" class="uri">Https://www.who.int/news-room/questions-and-answers/item/cancer-carcinogenicity-of-the-consumption-of-red-meat-and-processed-meat</a>.
</div>
<div id="ref-smc2015expert" class="csl-entry">
Science Media Centre. 2015. <em>Expert Reaction to <span>IARC</span> Classification of Processed Meat as <span>“Carcinogenic to Humans”</span> and Red Meat as <span>“Probably Carcinogenic to Humans”</span></em>. <a href="https://www.sciencemediacentre.org/xpert-reaction-to-iarc-classification-of-processed-meat-as-carcinogenic-to-humans-group-1-and-red-meat-as-probably-carcinogenic-to-humans-group-2a/" class="uri">Https://www.sciencemediacentre.org/xpert-reaction-to-iarc-classification-of-processed-meat-as-carcinogenic-to-humans-group-1-and-red-meat-as-probably-carcinogenic-to-humans-group-2a/</a>.
</div>
<div id="ref-spiegelhalter2019art" class="csl-entry">
Spiegelhalter, David. 2019. <em>The Art of Statistics: Learning from Data</em>. Pelican.
</div>
<div id="ref-zhang1998relative" class="csl-entry">
Zhang, Jun, and Kai F. Yu. 1998. <span>“What’s the Relative Risk? <span>A</span> Method of Correcting the Odds Ratio in Cohort Studies of Common Outcomes.”</span> <em>JAMA</em> 280 (19): 1690–91.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="norm-dist.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/profnicklee/MRes_LFD_Book/edit/main/01-intro.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["LFD.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
