% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{book}
\usepackage{xcolor}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage[]{natbib}
\bibliographystyle{apalike}
\usepackage{booktabs}
\usepackage{amsthm}
\makeatletter
\def\thm@space@setup{%
  \thm@preskip=8pt plus 2pt minus 4pt
  \thm@postskip=\thm@preskip
}
\makeatother

% Copyright footer on every page. Patching the book class's own page
% styles (\ps@headings / \ps@plain) was tried first and didn't work --
% this template's running headers don't route through the \ps@ macros
% book.cls normally uses, so overriding them had no visible effect (a
% forced huge test string never appeared). eso-pic stamps text directly
% onto every shipped-out page at the physical layer, independent of
% whatever page style is active, which sidesteps that entirely.
\usepackage{eso-pic}
\AddToShipoutPictureBG{%
  \AtPageLowerLeft{%
    \hspace{0.5\paperwidth}%
    \raisebox{1.2cm}{%
      \makebox[0pt][c]{\small \copyright\ Nick Lee --- \textit{Learning From Data (and) Science}}%
    }%
  }%
}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
% fallback for those not using the hyperref driver hyperxmp:
\makeatletter
\@ifundefined{xmpquote}{\newcommand{\xmpquote}[1]{#1}}{}
\makeatother
\hypersetup{
  pdftitle={WBS MRes: Learning From Data},
  pdfauthor={Professor Nick Lee},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{WBS MRes: Learning From Data}
\author{Professor Nick Lee}
\date{2026-09-14}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\chapter{Introduction and Orientation}\label{introduction-and-orientation}

This is an online course book, designed for students on the Warwick Business School MRes Programme, who are taking the module `Learning from Data (and) Science'. The module consists of a set of in-person lectures, linked with these examples and additional expositions.

You can see to the left a list of the contents of the book. However, please note that these `chapter numbers' do not refer to the specific lectures. Not all of the lectures use quantitative examples.

It is important to note that this module is not designed to teach you how to use R. The objective of the module is to help you learn how to use and interpret the results of quantitative social science research, understand the core principles of excellent quantitative social science, and also how to apply key principles of quantitative and scientific thinking into your own life and (where relevant) work.

This book is written in \textbf{Markdown}, using R and the \textbf{bookdown} package, and published online in HTML format. A full archive of all the R Code and data for the individual chapters from the book is available from Professor Lee on request, once the book is completed for the year.

This book is essentially a `live' document, meaning that it is finalised for each year just before the module runs, but then modified for future runnings.

The current year is 2026, and the book is currently \emph{in progress for 2026.}

Please enjoy the book, and learn from it.

Feel free to email me with any questions or comments: \href{mailto:nick.lee@wbs.ac.uk}{\nolinkurl{nick.lee@wbs.ac.uk}}

\chapter{Describing the World With Data}\label{intro}

This Chapter is designed to work with Lecture 2.

Here, I will demonstrate a number of important concepts about data displays and descriptions.

First, let's find some data to play with. In the following examples I will use some data from the Johns Hopkins Coronavirus Resource Center as at April 26 2022, which contains data by country about cases, deaths, and mortality for COVID.

\url{https://coronavirus.jhu.edu/}

However, as of 2023, the JHCRC ceased collecting data, and their archival data is available on their github:

\url{https://github.com/CSSEGISandData/COVID-19}

However, I do think it would be quite hard to recreate the exact snapshot in time of the data set we are using here.

I'm going to use the top 20 countries in terms of raw number of cases

To demonstrate how we can easily change people's views of a data set, let's run some bar charts:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-4-1.pdf}}

One thing we could do is change the orientation of the bars\ldots{}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-5-1.pdf}}

That's nice. The basic conclusion we can draw is everyone is pretty much the same in terms of survival rate, although Mexico is a bit down.

Interestingly, it seems to me that the variation is more pronounced in this presentation where you look `down' a line of results, than above where you look across. I'm not aware of any theory behind why, or even if anyone has ever noted that before, but it's definitely something I noticed here.

Either way, if I wanted to make everyone think that COVID survival rates were really different, there's a simple trick I could use:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-6-1.pdf}}

Wow, how do you like that! What's different?

Changing the scale of the y-axis is an old trick, and when used to manipulate opinion it's a bad thing. However, there is a case to say we need to know what we want to say, before we decide how to say it. When does `making sure we see the right message' move into `outright manipulation / misrepresentation?'.

Here's another common way this type of data is presented in media and non-scientific reports:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-7-1.pdf}}

or a variant:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-8-1.pdf}}

Technically, it's wrong to present this data in a line chart, because it is discrete values and does not represent a trend, but it is surprisingly common - probably because it `looks more sciency'\ldots{}

Ironically, there is some logic behind using line charts with this sort of data, depending on what you are trying to get across - let's move to excel to demonstrate\ldots{}

While we're at it, we'll also look at pie charts\ldots{}

\textbf{\emph{Quick transition to MS Excel, then back to the slides\ldots{}}}

\section{Summarizing Data with Numbers}\label{summarizing-data-with-numbers}

Above, we simply plotted a single variable of interest, and showed that some very basic changes to how it was displayed had the potential to `lead' the reader to different conclusions. Even that simple tweaking is a powerful way to change opinion, and used in the wrong way can be very misleading.

Now, let's think about the idea of an \emph{even simpler} way to describe data - by summarizing it with just some numbers.

For this example, I am going to use data on GDP per head in 2020 for each nation, from the World Bank.

Before I do anything else, I'm going to graph it again. This time I will use a histogram, which is similar to a bar chart, but not the same thing.

Specifically, a bar chart is used when we are displaying discrete categories. So, above, we had 20 countries, and a single bar for each country.

A histogram is instead when we divide our data into `groups' of similar values, which are called `bins'. Thus, each `bar' on a histogram represents the number of elements (in this case, countries) which fall in that bin. So, in this case, we can divide the GDP variable into bins.

As an example, we can divide GDP per head into `bins' of US\$10000, and plot a histogram

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-10-1.pdf}}

As you can see, there are nearly 120 countries in the first bin, which you can also see runs from -5000 to 5000 dollars. Of course, we know there are no countries with negative GDP per head, but this is just an artefact of the binning process.

This sort of chart gives us something very different to a bar chart. Instead, it is really a \textbf{frequency distribution}, and it charts the frequency of values of a given variable - in this case GDP per head.

So, here we have some idea of the \textbf{distribution} of the variable. It's clearly skewed quite heavily, with some outliers at the high end.

Let's move on to summarize this variable with some numbers:

\begin{verbatim}
## 
##                     GDP2020
## --------------- -----------
##            Mean    15162.61
##         Std.Dev    22146.53
##             Min      233.84
##          Median     6117.49
##             Max   173688.19
##         N.Valid      251.00
##               N      266.00
##       Pct.Valid       94.36
\end{verbatim}

What we have here are the classic `summary statistics' for 2020 GDP per head.

One thing missing - which admittedly is not very useful in this case, is the Mode, or the `most frequent' value.

\begin{verbatim}
## [1] 1875.441
\end{verbatim}

There you have it, the mode is 1875.441.

One important thing to note here is that the word \textbf{average} is badly misused when talking about data. Specifically, the \emph{mean}, \emph{median}, and \emph{mode} can all at one time or the other be referred to as the \textbf{average} value of a given variable. But, as you can see, they are all different numbers! The word `average' is a very vague word to use in this context, so do be careful about when you use it. You should always default to using the specific term you are talking about.

A few other summary statistics are calculated for 2020 GDPph below

\begin{verbatim}
##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's 
##    233.8   2127.5   6117.5  15162.6  18072.4 173688.2       15
\end{verbatim}

\begin{verbatim}
## [1] 15944.94
\end{verbatim}

\begin{verbatim}
## [1] 173454.4
\end{verbatim}

What we have here now includes the range (173454.4) and the interquartile range (15944.94), which are both useful measures of how `spread out' the data is.

Each of the summary numbers above has strengths and weaknesses when describing different types of data. Here, we will mainly talk about the sensistivity to outliers.

Specifically, the \textbf{median} and \textbf{interquartile range} are less sensitive to outliers as measures of central tendency and range respectively than their counterparts the \textbf{mean} and the \textbf{range}. So, that's why you commonly see the median used so frequently in these sorts of situations.

But, what do we mean by outliers? Let's look at this in the context of another graphical display, the \textbf{box plot}.

\section{Box Plots}\label{box-plots}

The box plot (and the other displays below) are criminally underused in my opinion. Most of us calculate a box plot at school, and then never again. But, it's a really useful way to understand a data set.

Let's do a boxplot for the 2020 GDPph data:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-14-1.pdf}}

A box plot presents a lot of information very efficiently. The \textbf{median} is the thick horizontal, the white rectangle is bounded by the \textbf{interquartile range}, and outliers are represented as dots.

We can see here that the data is very skewed, and there are some very significant outliers at the high end (no prizes for guessing which countries they are).

A weakness of a box plot is that it doesn't actually show the distribution of the data. One way to do this is to add what is called \emph{jitter}, which actually plots the values of each case, with a `jitter' to avoid overlapping identical values.

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-15-1.pdf}}

So, we can see here that most of the data is clustered towards the bottom of the range - i.e.~very low GDPph. This is of course the same conclusion as the historgram allowed us to draw. But, the box plot also gives us plenty of \emph{other} information about the variable.

Even so, while box plots are nice, they can also obscure important facts about the distribution. Adding the jitter helps, but there are other ways to display this type of data that make the distribution more obvious.

\section{Violin Plots and Ridge Plots}\label{violin-plots-and-ridge-plots}

Here, I'm going to give you a set of \emph{even more underused} data displays, which can show some powerful things about variables.

In order to do so, I am going to simulate some data, to make sure it has exactly the features I want to show.

First, let's create the data and use box plots to display it, such as you are already experienced with above.

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-16-1.pdf}}

That's all very well, but as we know, this can obsure the distribution. So, let's add jitter:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-17-1.pdf}}

Well, look at that. B has what is called a \emph{bimodal} distribution.

Lets look at what is called a \textbf{violin plot} to emphasize this:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-18-1.pdf}}

Neat! You can see how the violin plot really emphasizes the differences in the distributions, which are totally obscured by the box plots, and only partially shown by adding the jitter.

Another way to visualize this is with \textbf{ridges}, which basically compare the distributions of variables together:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-19-1.pdf}}

These are really cool in my view. And, if you are asking me, my preference in this type of situation would be to combine jittered box plots, which show the basics, and emphasize the outliers and summary numbers, with ridge plots, which show a really nice visualization of the distributions of each variable. Taken together, these plots allow us to understand a surprisingly large amount of important information about variables.

OK, let's move back to the slides to discuss another crucially important concept related to data distributions: \textbf{transformations}.

\textbf{\emph{Back to slide deck}}

\section{Transformations}\label{transformations}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-20-1.pdf}}

As you can see, the data is heavily skewed, or `squished' towards the bottom. This makes it hard to see any patterns by eye.

We can make it easier to interpret by \emph{transforming the variable}. Here, using a logarithmic transform.

Let's run the box again:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-22-1.pdf}}

Nice, see how the spread is easier to interpret here? Log transforms are essentially `inverse exponentials', so what they do is bring down extreme high outliers.

Let's see this in some more plots:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-23-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-24-1.pdf}}

Compare the violin of the log transformed variable with the original:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-25-1.pdf}}

In fact, we can use the log transform to revisit some of our COVID data back in EXCEL\ldots{}

\textbf{\emph{Quick transition to MS Excel, then back to slides\ldots{}}}

\chapter{The Normal Distribution}\label{norm-dist}

This chapter supplements the content in Lecture 3.

\section{A Simple Demonstration of the Normal Distribution}\label{a-simple-demonstration-of-the-normal-distribution}

First, let's consider the `empirical distribution', which is the pattern your data set makes.

Let's consider UK births in 2020 for our example, since they're a subject close to my heart (my first child was born in 2020).

Looking online, one can pull down the distribution of UK birthweights in 2020, available from the UK ONS website, and which are reported in 500g `bins'.

Source: \url{https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/livebirths/bulletins/birthsummarytablesenglandandwales/2020\#births-data}

We can use these numbers to create a chart

(please note, the code I use for the demonstrations in this lesson is mostly modified from David Spiegelhalter's originals, available on his Github page, with some of my own bits and bobs and new data\ldots)

Spiegelhalter's Github can be found here: \url{https://github.com/dspiegel29/ArtofStatistics}

The first thing I want to do is create a data set that accurately reflects the ONS distribution of UK birthweights in 2020. To do that, I use the following code, which in this instance I will display below, with annotations.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{weights}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\DecValTok{1500}\NormalTok{, }\DecValTok{2000}\NormalTok{, }\DecValTok{2500}\NormalTok{, }\DecValTok{3000}\NormalTok{, }\DecValTok{3500}\NormalTok{, }\DecValTok{4000}\NormalTok{, }\DecValTok{4500}\NormalTok{,}\DecValTok{5000}\NormalTok{,}\DecValTok{5500}\NormalTok{) }\CommentTok{\#modified}
\CommentTok{\#categories from 2020 UK Data}
\NormalTok{mids}\OtherTok{=}\NormalTok{weights}\DecValTok{{-}250} \CommentTok{\# Note the DS original is +250, but this does not work for UK}
\CommentTok{\#data as the numbered is the UPPER bound of the weight category in the ONS stats.}
\CommentTok{\#So the babies in the \textquotesingle{}2000\textquotesingle{} bin weigh 1500{-}1999, so the midpoint is 1750, not}
\CommentTok{\#2250}
\NormalTok{n}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\DecValTok{5015}\NormalTok{, }\DecValTok{7103}\NormalTok{, }\DecValTok{27554}\NormalTok{, }\DecValTok{99220}\NormalTok{, }\DecValTok{218442}\NormalTok{, }\DecValTok{179088}\NormalTok{, }\DecValTok{53530}\NormalTok{,}\DecValTok{6952}\NormalTok{,}\DecValTok{635}\NormalTok{) }\CommentTok{\# numbers in each}
\CommentTok{\#bin, UK2020}
\NormalTok{N}\OtherTok{=}\FunctionTok{sum}\NormalTok{(n)  }\CommentTok{\# total number of babies}
\NormalTok{area}\OtherTok{=}\NormalTok{N}\SpecialCharTok{*}\DecValTok{500}  \CommentTok{\# number * binwidth = total area of histogram}

\CommentTok{\#I think lbw should be sum of groups 1{-}3 not 1{-}2 as in the book code. Using 1{-}3}
\CommentTok{\#gives a result for the UK of 6.6\% which tallies with the official stat given}
\CommentTok{\#that I remove the \textquotesingle{}no recorded weight\textquotesingle{} and \textquotesingle{}implausible\textquotesingle{} categories\textquotesingle{}. I imagine}
\CommentTok{\#that the DS book data has categories which may be the lower bound not the upper}
\CommentTok{\#as in the UK data table.}

\NormalTok{lbw   }\OtherTok{=} \FunctionTok{sum}\NormalTok{(n[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{])   }\CommentTok{\# number with low birth weight (less than 2500)}
\NormalTok{lbw.percent}\OtherTok{=}\DecValTok{100}\SpecialCharTok{*}\NormalTok{lbw}\SpecialCharTok{/}\NormalTok{N  }\CommentTok{\# \% low birth weight}
\CommentTok{\# 6.6\% which tallies with Nuffield stat for 2020.}
\end{Highlighting}
\end{Shaded}

Remember though, the above just sets up the numbers required to recreate the empirical distribution, it isn't analysis itself.

Next, I want to summarize the distribution I just created and a few important numbers regarding Low Birthweight that we will need to use for our later discussion.

Displayed below are the total N for the distribution, the number of low birthweight (LBW) babies born, the percentage of LBW babies, the mean, the standard deviation, the skewness, and kurtosis.

\begin{verbatim}
## [1] 597539
\end{verbatim}

\begin{verbatim}
## [1] 39672
\end{verbatim}

\begin{verbatim}
## [1] 6.639232
\end{verbatim}

\begin{verbatim}
## [1] 3345.263
\end{verbatim}

\begin{verbatim}
## [1] 577.7594
\end{verbatim}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{verbatim}
## [1] 1.77
\end{verbatim}

Next, I will calculate the estimated proportion of low birthweight babies using a normal distribution approximation, and see if it tallies OK with the figure that is taken from the distribution of 6.6\%

\begin{verbatim}
## [1] 7.173338
\end{verbatim}

I will also calculate the middle birthweight proportion as a sense check - should be very close to 50\%!

\begin{verbatim}
## [1] 49.98182
\end{verbatim}

For our reference, we will calculate the 25th, 50th, 75th percentiles

\begin{verbatim}
## [1] 2955.57
\end{verbatim}

\begin{verbatim}
## [1] 3345.263
\end{verbatim}

\begin{verbatim}
## [1] 3734.956
\end{verbatim}

Next I want to calculate the birthweight percentile of Monty, my son.

\begin{verbatim}
## [1] 0.8366843
\end{verbatim}

Now, at last, we can do some plots!

First let's set up the histogram and overlay a normal distribution on to it.

The weight of Monty is overlaid as a red line. We can estimate if this is `unusual' or not by how far away it is from the mean of the distribution.

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-34-1.pdf}}

\section{What Actually is a Normal Distribution?}\label{what-actually-is-a-normal-distribution}

Below, I will chart the normal distribution with Standard Deviations.

Mathematically, around 95\% of the area under the chart is between -2 and +2 SDs, and 99.8\% between -3 and +3 SDs

Now, another way to think about this is that the area under the normal curve represents 100\% of the probability of a given value (here, weight) occuring. So, you could say that it is around 95\% probable that any given birthweight (randomly sampled) will occur between -2 and +2 SDs of the mean.

We can calculate this easily, given that the mean is 3345.263, and the SD is 577.7594

So, it is 95\% probable that a random baby born in the UK in 2020 will weigh between 2189.745 and 4500.781g

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-35-1.pdf}}

We can calculate how many SDs Monty's weight was above the mean by calculating the z-score for his weight of 3912g.

To do so, let's return to the slide deck and see the calculation.

\textbf{\emph{Move back to the slides\ldots{}}}

Next, we can overlay percentiles in 5\% increments on the chart, which are also useful ways to describe a distribution like the Normal.

50th is of course the median, and the 25th and 75th percentilies are the quartiles.

Here, the same things we have previously discussed in relation to samples are applied to populations

We can also see that Monty lies on the 83rd percentile, that is 83\% of babies born in 2020 weighed less. This tallies with what we were told at the time, and then things are monitored quite closely from that time on in terms of percentiles.

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-36-1.pdf}}

Moving to a discussion of low birthweight. It is medically defined as low if below 2500g. Nuffield reports that 6.6\% of babies in 2020 were born at low birthweight, which is fairly good.

This tallies fairly well with the predicted proportion from the normal distribution of 7.2\%

What we gain from the grey shaded area is the proportion of the population which is expected to be born at low birthweight, but also an indication of the probability that a randomly-chosen baby born in 2020 would be of low weight.

This concept can easily be transferred to other weights in this population (and by extension to other variables and populations distributed like this)

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-37-1.pdf}}

\chapter{Associations and Relationships}\label{assoc-rel}

This chapter supplements the content in Lecture 5.

\section{Correlations and Associations}\label{correlations-and-associations}

First, let's look at the basic concepts of correlation, using some data from the World Happiness Report, and GDP from the World Bank, all put together by the team at Our World in Data.

You can explore their work here: \url{https://ourworldindata.org/}

First, I can just double check the data by describing it.

\begin{verbatim}
##           vars   n        mean           sd     median     trimmed        mad
## Country*     1 249      125.00        72.02     125.00      125.00      91.92
## Happiness    2 153        5.49         1.12       5.53        5.52       1.16
## GDPpc        3 197    20463.88     20717.34   12655.00    17037.01   13338.95
## Pop          4 242 59178643.60 331869505.09 5596196.00 12318073.38 8185922.38
##             min          max        range  skew kurtosis          se
## Country*    1.0 2.490000e+02 2.480000e+02  0.00    -1.21        4.56
## Happiness   2.4 7.820000e+00 5.420000e+00 -0.26    -0.38        0.09
## GDPpc     731.0 1.125570e+05 1.118260e+05  1.58     2.55     1476.05
## Pop       809.0 4.663087e+09 4.663086e+09 11.65   152.44 21333379.77
\end{verbatim}

We've got 249 countries, with population, GDP per capita, and Happiness. There's a fair bit of missing data, which you can see by looking at the numbers in the \emph{n} column. That's ok for now, as long as we are aware of it.

Let's plot this data using a very basic scatterplot.

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-42-1.pdf}}

Interpretation: there's seemingly an association here. As one variable increases, the other does too.

It's worth noting that I have chosen to put GDPpc on the x-axis, which \emph{implies} that the driver of Happiness is GDP. This replicates the way that most of the media articles that are regularly written on this kind of topic do it.

Nevertheless, this is just a scatterplot, so there is no real requirement to put any particular one of the variables on the x-axis, because it's important that you do \textbf{NOT} draw any causal conclusion from this very basic scatterplot. Simple associations are \emph{not} in any way conclusive evidence of any causality in the relationship, since there are many other things which could be going on that are impossible to tease out simply with a bivariate association seen on a scatterplot. For example, there could be a spurious relationship - what could cause \emph{both} happiness and GDPpc to increase?

Ideas? Could it simply be something like `political stability'? Or something else?

Either way, all we have here is a basic data display. While, as I showed previously, simply displaying data can be very powerful, it is still only essentially an `eyeball' analysis, and different people might draw different conclusions here (we'll discuss that later on).

What we want to do, is have some sort of objective \textbf{metric} for the relationship, and for this, we have the \textbf{correlation} statistic.

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  Happy$Happiness and Happy$GDPpc
## t = 13.502, df = 146, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6636288 0.8092331
## sample estimates:
##      cor 
## 0.745184
\end{verbatim}

Here, we can see that the correlation is 0.75

But what does that mean? We can \textbf{return to the slides for some explanation}.

\section{Introducing Nonlinear Associations}\label{introducing-nonlinear-associations}

Let's return to the scatterplot of GDPpc and Happiness

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-44-1.pdf}}

As the \emph{Economist} analysis discussed in the lectures suggests, this association also looks kind of \emph{nonlinear}.

However, unlike the \emph{Economist}, we can also say that there are multiple ways to look at this:

First, you could take the \emph{Economist's} view that this is probably a \textbf{nonlinear relationship.} Indeed, we can check this out by \emph{transforming} GDPpc and comparing the results between transformed and non-transformed data.

Let's have a try at that. What we will do is transform the GDPpc variable using a log transform (i.e.~multiplying GDPpc by the natural logarithm).

\begin{verbatim}
##           vars   n        mean           sd     median     trimmed        mad
## Country*     1 249      125.00        72.02     125.00      125.00      91.92
## Happiness    2 153        5.49         1.12       5.53        5.52       1.16
## GDPpc        3 197    20463.88     20717.34   12655.00    17037.01   13338.95
## Pop          4 242 59178643.60 331869505.09 5596196.00 12318073.38 8185922.38
## GDPpc_log    5 197        9.38         1.14       9.45        9.41       1.33
##              min          max        range  skew kurtosis          se
## Country*    1.00 2.490000e+02 2.480000e+02  0.00    -1.21        4.56
## Happiness   2.40 7.820000e+00 5.420000e+00 -0.26    -0.38        0.09
## GDPpc     731.00 1.125570e+05 1.118260e+05  1.58     2.55     1476.05
## Pop       809.00 4.663087e+09 4.663086e+09 11.65   152.44 21333379.77
## GDPpc_log   6.59 1.163000e+01 5.040000e+00 -0.25    -0.79        0.08
\end{verbatim}

We can see there is a new variable now, GDPpc\_log, which is the log transformed GDPpc variable - basically the original GDPpc variable multiplied by the natural logarithm.

Of course, there are many other possible transforms. I touched on them earlier, in Chapter 2, and I'll elaborate a little more on it below, for now let's rerun the plot using GDPpc\_log

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-46-1.pdf}}

That relationship definitely looks more linear, and if that was my only criteria for deciding what to do with the data, I would definitely now run with this idea, as the \emph{Economist} did in their article

With that in mind, let's take a quick look at the correlations for these variables. First the original GDPpc, and then the log transformed one.

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  Happy$Happiness and Happy$GDPpc
## t = 13.502, df = 146, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6636288 0.8092331
## sample estimates:
##      cor 
## 0.745184
\end{verbatim}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  Happy$Happiness and Happy$GDPpc_log
## t = 15.916, df = 146, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.7287785 0.8487456
## sample estimates:
##       cor 
## 0.7964703
\end{verbatim}

We can see that the association is stronger (the correlation is higher) for the log GDPpc variable, although to be honest, it is not a very big difference here, compared to other data sets that I have seen discussed in the media. That's interesting in itself (note we are using 2020 data, so maybe the pandemic has something to do with it?)

However, \textbf{transformations} of data are kind of a complicated topic though. In essence, what we are doing is changing the distribution of one (or more) of the variables, in a systematic way, in order to convert a non-linear relationship (which may be unable to be tested with methods like correlation and regression) into a linear one.

There are many different types of transformations available to you, and the one you choose depends on the form of the nonlinearity. A \textbf{log} transform converts an exponential (or similar) relation into a linear one. But, there are specific transforms for many different forms. Oftentimes, it's not always obvious what exactly to do, and people often default to transforming \textbf{any} nonlinear-looking relationship, or highly skewed variable, using log or maybe the quadratic (squaring). It's not really that simple though, and I think we need to be a bit more logical and theory-driven on \textbf{why} we transform variables.

In this case, I admit that the logic makes sense, that there is still a relationship between GDPpc and happiness at the top end, but you just have to increase GDPpc by a \textbf{lot more} to get the same change in happiness, compared to the change needed at the lower end of GDPpc. And, making that transform to come to that conclusion actually makes a difference to how we think of the influence of GDPpc on happiness, and could concievably lead to policy changes compared to the prior non-transformed analysis.

\textbf{Even so}, I have always had a slightly different possibility on my mind. In fact, it may be that there are \textbf{two groups} of country, low and high income, and different \textbf{linear} associations within those groups. That's a similar-ish idea to the nonlinear one, but it is a bit different, and I actually prefer that idea. A nice challenge would be to work out a way to test which of the two alternative explanations is actually better supported by the data\ldots{}

Maybe I'll leave that for another day though.

We can \textbf{return to the slides} for a bit more discussion.

\section{Regression}\label{regression}

We can add a \textbf{regression line} to the GDPpc / Happiness scatterplot, for some extra information over the correlation.

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-48-1.pdf}}

We can also do this with the log GDPpc to compare.

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-49-1.pdf}}

You can see that using the log GDPpc variable does improve things, but not by that much in my view. That said, it's clear that the line is a bit more `precise' (the errors are lower which can be seen by the narrower shaded regions). So, if we are looking for the `best' model, it's pretty clear that the log GDPpc model is better than the simple GDPpc model.

Either way, the regression line adds a layer of information on to the correlation, which allows us to predict \emph{y} from \emph{x}.

How so? Well, let's add the regression equation to the chart to see:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-50-1.pdf}}

This adds an \emph{intercept}, and with that plus the coefficient we have all that we need to plot a straight line, which we can \emph{extrapolate} to higher values of GDPpc (although remember this is the logged GDP variable) and predict what the happiness scores would be.

This is obviously viable to the extent we can justify the relationship, and also within the parameters of our variables, and how confident we are that the relationship is consistent at all levels of the variables.

\textbf{return to the slides}

\section{Multiple Regression}\label{multiple-regression}

Here, we will use a simple three-variable set of simulated data, which represents rates of smoking, rates of cycling, and heart disease incidence. This data is available from: \url{https://www.scribbr.com/statistics/linear-regression-in-r/}

Remember, this is \textbf{simulated data} not real data.

\begin{verbatim}
##               vars   n   mean     sd median trimmed    mad  min    max  range
## ...1             1 498 249.50 143.90 249.50  249.50 184.58 1.00 498.00 497.00
## biking           2 498  37.79  21.48  35.82   37.71  27.51 1.12  74.91  73.79
## smoking          3 498  15.44   8.29  15.81   15.47  10.86 0.53  29.95  29.42
## heart.disease    4 498  10.17   4.57  10.39   10.18   5.42 0.55  20.45  19.90
##                skew kurtosis   se
## ...1           0.00    -1.21 6.45
## biking         0.07    -1.22 0.96
## smoking       -0.04    -1.12 0.37
## heart.disease -0.03    -0.93 0.20
\end{verbatim}

Next, let's run three simple regressions among the three variables

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-52-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-53-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-54-1.pdf}}

Remember, these are \emph{simple} regression lines, with bivariate scatterplots. What I mean, is the effect of biking on heart disease does not take account of the effect of smoking on heart disease. What we need to do is run a model which takes account of \emph{both} the predictors, as \textbf{we can explain on the slide-deck\ldots{}}

Now we can run the Multiple Regression Model

\begin{verbatim}
## 
## Call:
## lm(formula = heart.disease ~ biking + smoking, data = Heart)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.1789 -0.4463  0.0362  0.4422  1.9331 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 14.984658   0.080137  186.99   <2e-16 ***
## biking      -0.200133   0.001366 -146.53   <2e-16 ***
## smoking      0.178334   0.003539   50.39   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.654 on 495 degrees of freedom
## Multiple R-squared:  0.9796, Adjusted R-squared:  0.9795 
## F-statistic: 1.19e+04 on 2 and 495 DF,  p-value: < 2.2e-16
\end{verbatim}

First, we look at the R2, or more accurately the Adjusted R2, which takes account of the number of variables (they are usually very similar). The R2 essentially measures how much variation in your Dependent Variable is explained by your model (i.e.~your regression predictors). It ranges from 0 to 1, and higher means more variance explained. Here we see a very high AdjR2 of 0.98, almost 1. This is simulated data of course, and it is quite rare to see such high R2s in real data. For the most part, you want R2 to be high, but if it gets too high (say above 0.8 but this is not a `rule') you might start to get worried about whether your IVs and DVs are actually distinct things. Apart from that, standards of what makes an acceptable R2 are highly dependent on the context and field you are working in, and you'll no doubt see lots of different ideas throughout your career on what is acceptable. Of course, that only scratches the surface of this issue, and I'll say more in the lecture slides.

Next, we look at the coefficients, and they can be interpreted as follows:

A 1 unit increase in biking will on average lead to a 0.2 unit decrease in heart disease A 1 unit increase in smoking will on average lead to a 0.17 unit increase in heart disease.

Of course, what these `units' refer to depends on what you have measured them with of course. But, the unarguable interpretation is that the effect is strong.

However, because the \emph{scales of the variables} are different, its not really possible to compare the sizes of the effects. So to some extent we don't know which of the two variables has the `bigger' effect here, relatively at least.

To do that, we need to standardize the coeffiecients, which basically means putting all the variables on the \textbf{same scale}. Beforehand, they all were on different scales, which you can see by going back up and looking at the range, mean, and standard deviation of the original variables. You can see for yourself they are all different.

We can solve this issue by creating a new set of standardized data, and running the model on that, as follows:

\begin{verbatim}
##               vars   n mean sd median trimmed  mad   min  max range  skew
## ...1             1 498    0  1   0.00       0 1.28 -1.73 1.73  3.45  0.00
## biking           2 498    0  1  -0.09       0 1.28 -1.71 1.73  3.43  0.07
## smoking          3 498    0  1   0.05       0 1.31 -1.80 1.75  3.55 -0.04
## heart.disease    4 498    0  1   0.05       0 1.19 -2.10 2.25  4.35 -0.03
##               kurtosis   se
## ...1             -1.21 0.04
## biking           -1.22 0.04
## smoking          -1.12 0.04
## heart.disease    -0.93 0.04
\end{verbatim}

You know these variables are standardized as they now all have a mean of 0 and a standard deviation of 1. Now, let's run our model on this standardized data set.

\begin{verbatim}
## 
## Call:
## lm(formula = heart.disease ~ biking + smoking, data = std_Heart)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.47658 -0.09762  0.00792  0.09671  0.42283 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -8.205e-16  6.410e-03    0.00        1    
## biking      -9.403e-01  6.418e-03 -146.53   <2e-16 ***
## smoking      3.234e-01  6.418e-03   50.39   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.1431 on 495 degrees of freedom
## Multiple R-squared:  0.9796, Adjusted R-squared:  0.9795 
## F-statistic: 1.19e+04 on 2 and 495 DF,  p-value: < 2.2e-16
\end{verbatim}

You can see the things that have changed are the `Estimates', which are now standardized.

In decimal, they are -0.94 for biking and 0.32 for Smoking.

The correct interpretation of these standardized effects is that for every 1SD increase in biking, you expect a 0.94SD decrease in heart disease, and for every 1SD increase in smoking, you would expect a 0.32 increase in heart disease.

So, we can see that actually biking has a much \textbf{higher} relative effect on heart disease than smoking (although in the opposite direction). That said, this assumes that both the two IVs have similar standard deviations, and distributions, and we didn't check that in this example.

\section{Visualizing Multiple Regression}\label{visualizing-multiple-regression}

There are loads of different ways to visualize multiple regression. It's not trivial, because we have more than two variables, so we can't use the techniques we used already.

Some people like to use 3D-style plots, which look cool, but are not always easy to interpret, and take quite a lot of extra work, for what I would say is not that much payoff (if any).

In this case, we can use a pretty simple visualization, where we could plot the relationship of biking to heart disease at different levels of smoking.

This would be a fairly typical way to do things if we thought the relationship between biking and heart disease changed according to the level of smoking, in which case it would be a moderator. Here, it doesn't really work that way, but it's a cool visualization regardless. It does require some data prep, but not that much, and I took the basic idea from the website where I sourced the data: \url{https://www.scribbr.com/statistics/linear-regression-in-r/}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-58-1.pdf}}

Here, we can see that the effect of smoking is really just to raise the likelihood of heart disease, however much biking you do.

So, for a given person who bikes a given amount, if they smoke more they will have a higher risk than a person who bikes the same amount but smokes less.

But, \emph{for a given smoker}, the more they bike, the lower their risk of heart disease, to the extent that if a heavy smoker bikes enough, their actual risk of heart disease could even be lower than a non-smoker who does not bike at all.

Don't forget, this is not real data, but the point stands. Get on your bike.

\chapter{Beginning to Understand Uncertainty}\label{uncertainty}

This Chapter relates to the first part of lecture 6. Here, I'll introduce core concepts around \textbf{uncertainty} in our results. Understanding that the results of our analysis always contain some level of uncertainty is probably the most critical concept to get our heads around as quantitative social scientists. Most of our job is not really coming up with the actual \emph{statistics}, such as the correlation coefficient, or regression beta, but is more about understanding how to interpret and use those results - i.e.~\textbf{what they mean}. And, fundamental to that is understanding their uncertainty.

Again, to reiterate the message I sent in class, many of the examples in this Chapter, and later ones, involve \textbf{randomness}. This means that the results here may be slightly different numerically to the results in the slides. And, if you were to run these examples yourself, you would also get slightly different results. This is nothing to worry about, because the meaning of the results does not change.

So, to start the journey, let's grab some data.

Here, we will again use the simple three-variable set of simulated data from the demonstration of multiple regression, which represents rates of smoking, rates of cycling, and heart disease incidence.

\begin{verbatim}
## # A tibble: 6 x 4
##    ...1 biking smoking heart.disease
##   <dbl>  <dbl>   <dbl>         <dbl>
## 1     1  30.8    10.9          11.8 
## 2     2  65.1     2.22          2.85
## 3     3   1.96   17.6          17.2 
## 4     4  44.8     2.80          6.82
## 5     5  69.4    16.0           4.06
## 6     6  54.4    29.3           9.55
\end{verbatim}

Rather than do the full `describe' as I did in the last chapter, I have simply above looked at what is called the `head' of the data set or the first few rows. This is because all I want to do here is double check that I have the data, and what variables are there.

Let's calculate some simple summary statistics from this data set to build on. For example, what is the mean and median for `smoking'?

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.5259  8.2798 15.8146 15.4350 22.5689 29.9467
\end{verbatim}

Now, we know this is \textbf{really} simulated data, but let's \textbf{imagine} for now that it was actually obtained by an organization like the Office for National Statistics in the UK, using a survey. We can presume the study was done well, and thus it is based on a true random sampling method, and we assume that the study population matches whatever target population we have in mind (remember the `inference gaps' discussed in class).

What we really want to know is, how close are these statistics (i.e.~the mean and median) to the \emph{true population values} that we would have found if we could survey the entire target population?

Let's begin to think about this by starting to build a table using these statistics, \textbf{by going back to the slide deck\ldots{}}

\section{Demonstration: Sampling from a `Known' Population}\label{demonstration-sampling-from-a-known-population}

Now, let's go back \textbf{one more step}, and demonstrate the uncertainty inherent to sample statistics by way of example.

Let's \emph{now} assume that this sample of 498 people actually \emph{is} the population we are interested in.

What \textbf{this} means is, we can actually \emph{draw a sample from this population of 498} and see what happens.

First, let's present the distribution for the entire `population' of 498.

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-63-1.pdf}}

Now, let's literally take a \emph{sample} of 10 random cases from that population of 498. Here, we are \textbf{sampling without replacement}, and are thus essentially doing exactly what a hypothetical `researcher' would do if they drew a random sample of 10 people to complete their survey, from the population of 498.

\begin{verbatim}
## # A tibble: 10 x 4
##     ...1 biking smoking heart.disease
##    <dbl>  <dbl>   <dbl>         <dbl>
##  1   149  40.0    7.81           7.66
##  2   292  47.7   28.4           10.2 
##  3   198  16.0   19.9           15.4 
##  4    58  27.6    4.39          10.9 
##  5   237  39.2   17.6           10.7 
##  6   189   5.51  17.9           16.0 
##  7   111  15.2   14.5           14.6 
##  8   461  71.4   12.8            3.26
##  9   398  58.4    0.734          3.23
## 10   395  60.6    6.47           3.35
\end{verbatim}

Next, let's look at the relevant statistics (median and then mean) and distribution of this sample of 10:

\begin{verbatim}
## [1] 13.68265
\end{verbatim}

\begin{verbatim}
## [1] 13.04942
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-66-1.pdf}}

We can do the same for successively larger samples, say 50, and 200:

\begin{verbatim}
## # A tibble: 50 x 4
##     ...1 biking smoking heart.disease
##    <dbl>  <dbl>   <dbl>         <dbl>
##  1   225  59.5   18.8           5.69 
##  2   303  33.7   14.1          10.2  
##  3   464  73.8    0.642         0.552
##  4   161  30.5    2.53          8.94 
##  5   485  22.7    1.02         10.9  
##  6    44  23.9    4.19         10.9  
##  7   344   8.63   4.38         14.5  
##  8   496   8.28   6.42         13.5  
##  9   429  35.7    9.40          9.57 
## 10   195  33.8    0.965         6.94 
## # i 40 more rows
\end{verbatim}

\begin{verbatim}
## [1] 15.16514
\end{verbatim}

\begin{verbatim}
## [1] 13.84031
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-67-1.pdf}}

\begin{verbatim}
## # A tibble: 200 x 4
##     ...1 biking smoking heart.disease
##    <dbl>  <dbl>   <dbl>         <dbl>
##  1    99   67.5  27.0            6.58
##  2    47   20.8  19.5           14.4 
##  3   226   31.7  23.2           12.5 
##  4   252   35.9  18.5           11.4 
##  5   349   68.0  13.3            4.07
##  6   489   41.6   0.533          5.93
##  7   162   22.3  23.2           15.9 
##  8   263   67.1   8.48           3.12
##  9   214   70.1  10.4            2.24
## 10    37   67.4  23.9            5.28
## # i 190 more rows
\end{verbatim}

\begin{verbatim}
## [1] 16.58324
\end{verbatim}

\begin{verbatim}
## [1] 16.58324
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-68-1.pdf}}

As you can see, the distributions of the smaller samples are more peaky and bumpy, because they are very sensitive to individual data points. As the sample gets larger, it starts to look more like the population right?

We can complete our table now in the slides of the sample statistics (median and mean) showing that in general, as we get closer to the population size, the statistics generally get closer too. To do so, let's go \textbf{back to the slides\ldots{}}

\chapter{Introduction to Bootstrapping}\label{bootstrap}

This Chapter relates to the second part of Lecture 6.In this chapter, you will learn the core concepts of bootstrapping. That is, creating synthetic sampling distributions through multiple resampling (with replacement) of a single sample.

The basic process is fairly simple, once you have your original sample, and has the following characteristics:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  A bootstrap sample has an equal probability of randomly drawing any of the original sample elements (data points).
\item
  Each element can be selected more than once - because the sample is done \textbf{with replacement}.
\item
  Each resampled data set (the new sample) is the same size as the original one.
\end{enumerate}

First, I will demonstrate the basic principle.

Recall from the last chapter that there was a simulated data set of 498 people, with variables representing smoking, biking, and heart disease.

We treated this as \textbf{the population} and then sampled from it to demonstrate uncertainty at different sample sizes.

So, let's take the sample of \textbf{50} that we drew from that `population' of 498, and imagine that we got this sample by (for example) doing a survey of the population (of 498), and this is our data set for analysis.

First we will remind ourselves of the properties and distribution of our sample, the median, mean, and distribution:

\begin{verbatim}
## [1] 15.16514
\end{verbatim}

\begin{verbatim}
## [1] 13.84031
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-71-1.pdf}}

Ok, there we go. Remember, this sample is our `data set' for analysis. Remember, it represents a \textbf{sample of 50 cases} from a \textbf{population of 498}.

We know the median and mean, but we have no real indication of the uncertainty in those estimates. What I mean is, without information about the population mean and median (which of course we would not have in a real-life sampling situation), we cannot know how close the sample median and mean are to the population mean and median.

In order to estimate that information, we will eventually use the bootstrap method. For now, we are just going to demonstrate the basic idea.

So, what we do now is draw \emph{another random sample of 50}. However, we don't draw it from the population, we instad draw the new sample of 50 \textbf{from our existing sample of 50}.

That sounds weird to many people, and at first they often say `but how can it be different from your original 50??'. The trick is that each time we draw a data point, we \emph{replace} it back, so we are always drawing our sample from the full 50. This is called \emph{sampling with replacement}.

In this way, the new sample can \textbf{only contain values which were in the original sample}, but can contain different frequencies of those values. Or in other words, each value can occur many different times, and that number of times may be different to the original sample. So the \emph{distribution of values} in this new sample will be different to the original sample, and the statistics will therefore also be different.

Let's draw this new sample, take the median and mean of the sample, and plot it:

\begin{verbatim}
## # A tibble: 50 x 4
##     ...1 biking smoking heart.disease
##    <dbl>  <dbl>   <dbl>         <dbl>
##  1   200   12.9  25.2          16.3  
##  2   267   70.3   6.42          1.10 
##  3    49   28.6  12.5          11.4  
##  4    17   61.7  16.8           5.44 
##  5   416   38.1  17.0           8.35 
##  6   464   73.8   0.642         0.552
##  7   200   12.9  25.2          16.3  
##  8   324   34.5  16.8          10.7  
##  9    84   30.5  29.9          14.3  
## 10   267   70.3   6.42          1.10 
## # i 40 more rows
\end{verbatim}

\begin{verbatim}
## [1] 16.76755
\end{verbatim}

\begin{verbatim}
## [1] 14.29855
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-72-1.pdf}}

Marvelous! Now, for the purpose of example, let's draw two more of these resamples from the original 50, take their median and mean, and plot the distributions\ldots{}

\begin{verbatim}
## # A tibble: 50 x 4
##     ...1 biking smoking heart.disease
##    <dbl>  <dbl>   <dbl>         <dbl>
##  1   496   8.28    6.42         13.5 
##  2    44  23.9     4.19         10.9 
##  3   203  20.6    15.4          14.6 
##  4   364  29.6    18.8          11.8 
##  5   267  70.3     6.42          1.10
##  6   394  22.4    21.7          15.0 
##  7    66   1.12   19.6          17.7 
##  8   439  63.8     9.91          3.40
##  9   276  67.8    15.2           4.68
## 10   265  17.5     4.76         11.9 
## # i 40 more rows
\end{verbatim}

\begin{verbatim}
## [1] 15.16514
\end{verbatim}

\begin{verbatim}
## [1] 14.24392
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-73-1.pdf}}

\begin{verbatim}
## # A tibble: 50 x 4
##     ...1 biking smoking heart.disease
##    <dbl>  <dbl>   <dbl>         <dbl>
##  1   267  70.3    6.42          1.10 
##  2   203  20.6   15.4          14.6  
##  3   394  22.4   21.7          15.0  
##  4   354   2.98   3.84         15.2  
##  5   265  17.5    4.76         11.9  
##  6    39  14.0   21.0          16.0  
##  7   342  33.3   17.3          11.3  
##  8   140  16.3    3.46         13.6  
##  9   464  73.8    0.642         0.552
## 10   333  74.0   18.9           3.30 
## # i 40 more rows
\end{verbatim}

\begin{verbatim}
## [1] 8.164991
\end{verbatim}

\begin{verbatim}
## [1] 10.84916
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-74-1.pdf}}

Now, if we \textbf{return to the slides}, we can build a table using these mean and median values. Of course, the slide deck will have slightly different values, since it's based on a different run of the resampling process, but the principle is the same.

So, this is the basic idea of bootstrapping. We sample with replacement from our original sample, many many times. We did 3 here manually, but we generally use a program to do this many more times, such as a thousand or more.

\section{Bootstrapping in the Context of Previous Examples}\label{bootstrapping-in-the-context-of-previous-examples}

To further reinforce the point, let's now place ourselves in the position of three different researchers, each of varying levels of enthusiasm, and all three are researching the \textbf{same population of 498 people} that we have already explored in the last few examples.

Researcher 1 is a little like me as a Ph.D.~student, and maybe more interested in `experiencing life'. So, he has little time to actually collect data, and not much more enthusiasm for it. In the end, he manages to take a sample of 10 people from the population of 498.

Researcher 2 is a bit more enthusiastic, and gets a sample of 50.

Researcher 3 is fairly conscientious, and takes a sample of 200 from the population of 498.

Now, what we can do, is run 1000 bootstrap replications of each of these varying-sized subsamples of the population, to see what might happen:

First, the 10:

\begin{verbatim}
## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = sub.10, statistic = f1, R = 1000)
## 
## 
## Bootstrap Statistics :
##     original    bias    std. error
## t1* 13.04942 0.0981507    2.567608
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-75-1.pdf}}

\begin{verbatim}
## BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
## Based on 1000 bootstrap replicates
## 
## CALL : 
## boot.ci(boot.out = results, type = "norm")
## 
## Intervals : 
## Level      Normal        
## 95%   ( 7.92, 17.98 )  
## Calculations and Intervals on Original Scale
\end{verbatim}

Now let's do it for the other two subsamples of n=50, and n=200

\begin{verbatim}
## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = sub.50, statistic = f1, R = 1000)
## 
## 
## Bootstrap Statistics :
##     original     bias    std. error
## t1* 13.84031 0.04731962     1.20233
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-76-1.pdf}}

\begin{verbatim}
## BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
## Based on 1000 bootstrap replicates
## 
## CALL : 
## boot.ci(boot.out = results, type = "norm")
## 
## Intervals : 
## Level      Normal        
## 95%   (11.44, 16.15 )  
## Calculations and Intervals on Original Scale
\end{verbatim}

\begin{verbatim}
## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = sub.200, statistic = f1, R = 1000)
## 
## 
## Bootstrap Statistics :
##     original       bias    std. error
## t1*  15.9127 -0.000645856   0.5816302
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-77-1.pdf}}

\begin{verbatim}
## BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
## Based on 1000 bootstrap replicates
## 
## CALL : 
## boot.ci(boot.out = results, type = "norm")
## 
## Intervals : 
## Level      Normal        
## 95%   (14.77, 17.05 )  
## Calculations and Intervals on Original Scale
\end{verbatim}

We'll now build a table with these values \emph{back in the slide deck}. Again, remember the values in the slide deck will differ from these due to the randomness of the process.

\subsection{Bootstrapping the Original Sample}\label{bootstrapping-the-original-sample}

Now, let's shift our minds a bit, and consider that the data set of 498 actually represents \textbf{a sample of a larger population} (remember from the last chapter, it's simulated, but meant to represent a sample from the population).

So, let's bring in Researcher 4, the most conscientious of all. She is the one who manages to take a sample of 498 people from the population. And, \emph{finally}, we can bootstrap the original full sample of 498:

\begin{verbatim}
## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = Heart, statistic = f1, R = 1000)
## 
## 
## Bootstrap Statistics :
##     original      bias    std. error
## t1* 15.43503 0.001437866    0.359051
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-78-1.pdf}}

\begin{verbatim}
## BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
## Based on 1000 bootstrap replicates
## 
## CALL : 
## boot.ci(boot.out = results, type = "norm")
## 
## Intervals : 
## Level      Normal        
## 95%   (14.73, 16.14 )  
## Calculations and Intervals on Original Scale
\end{verbatim}

This is a very nice set of results, which can tell us many interesting things. \emph{So let's go back to the slides\ldots..}

\section{Bootstrapping Other Stuff\ldots{}}\label{bootstrapping-other-stuff}

We have so far only bootstrapped the mean. However, the basic principle can be applied to virtually any statistical estimate. So, we can revisit some of our prior analyses, and use the bootstrap method to quantify the uncertainty in the estimates that we previously accepted without really thinking too hard about them.

\subsection{Correlations}\label{correlations}

First, let's revisit our recent correlation analysis of Happiness and GDP per capita.

\begin{verbatim}
## # A tibble: 6 x 4
##   Country        Happiness GDPpc      Pop
##   <chr>              <dbl> <dbl>    <dbl>
## 1 Afghanistan         2.4   1971 38972236
## 2 Albania             5.2  13192  2866850
## 3 Algeria             5.12 10735 43451668
## 4 American Samoa     NA       NA    46216
## 5 Andorra            NA       NA    77723
## 6 Angola             NA     6110 33428490
\end{verbatim}

\begin{verbatim}
##           vars   n        mean           sd     median     trimmed        mad
## Country*     1 249      125.00        72.02     125.00      125.00      91.92
## Happiness    2 153        5.49         1.12       5.53        5.52       1.16
## GDPpc        3 197    20463.88     20717.34   12655.00    17037.01   13338.95
## Pop          4 242 59178643.60 331869505.09 5596196.00 12318073.38 8185922.38
##             min          max        range  skew kurtosis          se
## Country*    1.0 2.490000e+02 2.480000e+02  0.00    -1.21        4.56
## Happiness   2.4 7.820000e+00 5.420000e+00 -0.26    -0.38        0.09
## GDPpc     731.0 1.125570e+05 1.118260e+05  1.58     2.55     1476.05
## Pop       809.0 4.663087e+09 4.663086e+09 11.65   152.44 21333379.77
\end{verbatim}

If we run the same analysis as in Chapter \ref{assoc-rel}, we'll get the same results: Correlation R = 0.75

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-80-1.pdf}}

Now, let's take uncertainty into account, by bootstrapping that correlation and creating some confidence intervals.

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-81-1.pdf}}

\begin{verbatim}
## # A tibble: 1 x 2
##   lower_ci upper_ci
##      <dbl>    <dbl>
## 1    0.689    0.811
\end{verbatim}

\begin{verbatim}
## Response: Happiness (numeric)
## Explanatory: GDPpc (numeric)
## # A tibble: 1 x 1
##    stat
##   <dbl>
## 1 0.745
\end{verbatim}

So, you can see the correlation is 0.75 with a 95\% confidence interval of 0.69 - 0.81

Now, let's extend this to the multiple regression case we have previously used, examining the relationships between smoking, biking, and heart disease.

\begin{verbatim}
## # A tibble: 6 x 4
##    ...1 biking smoking heart.disease
##   <dbl>  <dbl>   <dbl>         <dbl>
## 1     1  30.8    10.9          11.8 
## 2     2  65.1     2.22          2.85
## 3     3   1.96   17.6          17.2 
## 4     4  44.8     2.80          6.82
## 5     5  69.4    16.0           4.06
## 6     6  54.4    29.3           9.55
\end{verbatim}

\begin{verbatim}
##               vars   n   mean     sd median trimmed    mad  min    max  range
## ...1             1 498 249.50 143.90 249.50  249.50 184.58 1.00 498.00 497.00
## biking           2 498  37.79  21.48  35.82   37.71  27.51 1.12  74.91  73.79
## smoking          3 498  15.44   8.29  15.81   15.47  10.86 0.53  29.95  29.42
## heart.disease    4 498  10.17   4.57  10.39   10.18   5.42 0.55  20.45  19.90
##                skew kurtosis   se
## ...1           0.00    -1.21 6.45
## biking         0.07    -1.22 0.96
## smoking       -0.04    -1.12 0.37
## heart.disease -0.03    -0.93 0.20
\end{verbatim}

Here, we need to calculate multiple confidence intervals as we have multiple estimates.

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-83-1.pdf}}

\begin{verbatim}
## # A tibble: 3 x 2
##   term      estimate
##   <chr>        <dbl>
## 1 intercept   15.0  
## 2 smoking      0.178
## 3 biking      -0.200
\end{verbatim}

\begin{verbatim}
## # A tibble: 3 x 3
##   term      lower_ci upper_ci
##   <chr>        <dbl>    <dbl>
## 1 biking      -0.203   -0.197
## 2 intercept   14.8     15.1  
## 3 smoking      0.171    0.186
\end{verbatim}

It's worth reflecting on exactly what these conflidence intervals mean, and to do so, we can move \textbf{back to the slides\ldots{}}

\chapter{T-Tests for Means}\label{t-test}

This Chapter supplements the material on t-tests in the second part of Lecture 6.

In this chapter, I will introduce the t-test, a classic analysis technique that is used to compare two groups together.

\section{Independent Sample T-Tests}\label{independent-sample-t-tests}

We can also use bootstrapping as an entry point to a new analysis situation, where we are comparing two groups. This could be for example in a classic experimental context; treatment and control.

Remember, t-tests can be done in any analysis setting, and it does not require bootstrapping at all. It just so happens that they are nicely explainable at this point.

So, we are going to analyze a set of data from my infamous Ed Sheeran Study\textsuperscript{1} - which would certainly win an Ignobel Prize if I were ever to do it in reality rather than in my fondest imaginings.

The design was discussed in the lecture slides, but in brief we have a two-group `treatment and control' experiment, the classic `randomized control trial' style study.

The first thing to do is read in the data and describe it.

\begin{verbatim}
## # A tibble: 6 x 3
##      ID GROUP ANGER
##   <dbl> <dbl> <dbl>
## 1     1     1     4
## 2     2     2     5
## 3     3     1     2
## 4     4     2     3
## 5     5     2     4
## 6     6     1     2
\end{verbatim}

\begin{verbatim}
##       vars  n  mean   sd median trimmed   mad min max range skew kurtosis   se
## ID       1 30 15.50 8.80   15.5   15.50 11.12   1  30    29 0.00    -1.32 1.61
## GROUP    2 30  1.50 0.51    1.5    1.50  0.74   1   2     1 0.00    -2.07 0.09
## ANGER    3 30  3.33 1.21    3.0    3.33  1.48   1   5     4 0.04    -1.30 0.22
\end{verbatim}

\begin{table}

\caption{\label{tab:unnamed-chunk-87}Data summary}
\centering
\begin{tabular}[t]{l|l}
\hline
Name & ED\_IND\\
\hline
Number of rows & 30\\
\hline
Number of columns & 3\\
\hline
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
\hline
Column type frequency: & \\
\hline
factor & 1\\
\hline
numeric & 2\\
\hline
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
\hline
Group variables & None\\
\hline
\end{tabular}
\end{table}

\textbf{Variable type: factor}

\begin{tabular}{l|r|r|l|r|l}
\hline
skim\_variable & n\_missing & complete\_rate & ordered & n\_unique & top\_counts\\
\hline
GROUP & 0 & 1 & FALSE & 2 & 1: 15, 2: 15\\
\hline
\end{tabular}

\textbf{Variable type: numeric}

\begin{tabular}{l|r|r|r|r|r|r|r|r|r|l}
\hline
skim\_variable & n\_missing & complete\_rate & mean & sd & p0 & p25 & p50 & p75 & p100 & hist\\
\hline
ID & 0 & 1 & 15.50 & 8.80 & 1 & 8.25 & 15.5 & 22.75 & 30 & ▇▇▇▇▇\\
\hline
ANGER & 0 & 1 & 3.33 & 1.21 & 1 & 2.00 & 3.0 & 4.00 & 5 & ▁▇▇▆▇\\
\hline
\end{tabular}

We can see that we have one FACTOR variable, which we need to indicate the group each subject was in (CONTROL being GROUP 1, and ED being GROUP 2).

So, let's run an \emph{independent samples T-Test} with bootstrapped confidence interval.

We use an independent samples test, as the \emph{theory} is these two groups - after participating in the experiment - are no longer the `same'. There is something `different' about the population of people who listen to Ed Sheeran, compared to those who do not. What we are trying to do is assess whether this difference is in \emph{anger.}

Before we get to the code, it's worth pausing on what we're actually bootstrapping, and why it isn't simply the difference in the two group means.

The raw mean difference --- a bit over 1 point on our five-point anger scale --- is perfectly interpretable in its own right: it's a real number in the actual units the scale was measured in. But its size alone tells us nothing about how impressed we should be by it, because that depends entirely on the scale we happened to use and how much natural variation there already is in anger scores. A difference of ``1 point'' is enormous on a scale that barely moves and unremarkable on one that swings wildly.

This is the same problem as the standardised versus unstandardised regression estimates back in Section \ref{assoc-rel}. An unstandardised coefficient is interpretable in real-world units --- cigarettes, miles cycled --- but can't be compared across variables measured on different scales; standardising puts everything onto a common footing. The t-statistic does the same job here: it takes the mean difference and re-expresses it relative to how much variability and how much data we have, which is what lets us judge whether a given difference is impressively large or just noise.

\begin{verbatim}
## # A tibble: 2 x 2
##   GROUP  name
##   <fct> <dbl>
## 1 1      2.8 
## 2 2      3.87
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-88-1.pdf}}

\begin{verbatim}
## Response: ANGER (numeric)
## Explanatory: GROUP (factor)
## # A tibble: 1 x 1
##    stat
##   <dbl>
## 1 -2.65
\end{verbatim}

\begin{verbatim}
## # A tibble: 1 x 2
##   lower_ci upper_ci
##      <dbl>    <dbl>
## 1    -5.49   -0.575
\end{verbatim}

Remember: Group 1 is the control, and Group 2 listened to Ed Sheeran.

Cool, so it seems that Group 2 displayed more anger. The confidence interval for the t-statistic does not contain 0, so it supports the idea that there is a difference here. The interval is quite wide though - because of our small sample size. In a later Chapter we'll return to this issue of what confidence intervals actually mean.

I'll be honest: in a purely bootstrap context like this one, that standardisation step can feel like an unnecessary detour. We didn't need the t to reach our conclusion --- the conclusion was always going to be ``does the confidence interval contain zero or not'', and that would have been exactly as true if we'd bootstrapped the raw mean difference directly instead. The t only really earns its keep once we start relying on known probability distributions rather than brute-force resampling, which is where we're headed in the next chapter. For now, take it as scaffolding for what's coming rather than something bootstrapping strictly requires.

\section{Paired-Sample T-tests}\label{paired-sample-t-tests}

OK, so let's use a different design, using a paired samples t-test. Let me go \emph{back to the slides\ldots{}} to explain this difference.

The same basic process is needed, but with some modifications because of the type of comparison we are doing. And, as such, we have some new data.

\begin{verbatim}
##   ID ANG_T1 ANG_T2
## 1  1      1      4
## 2  2      2      5
## 3  3      3      2
## 4  4      4      3
## 5  5      2      4
## 6  6      1      2
\end{verbatim}

\begin{verbatim}
##        vars  n  mean   sd median trimmed   mad min max range skew kurtosis   se
## ID        1 30 15.50 8.80   15.5   15.50 11.12   1  30    29 0.00    -1.32 1.61
## ANG_T1    2 30  2.00 1.02    2.0    1.88  1.48   1   4     3 0.76    -0.57 0.19
## ANG_T2    3 30  3.33 1.21    3.0    3.33  1.48   1   5     4 0.04    -1.30 0.22
\end{verbatim}

Now, for this bootstrap purpose we actually need to to calculate the \textbf{difference between the two measurements} (here, T1 and T2).

Then, we bootstrap a one-sample t-test with this difference variable. This essentially tests whether the difference is different from zero. If it is, that indicates some effect of the treatment.

Let us first calculate the new variable:

\begin{verbatim}
##   ID ANG_T1 ANG_T2 DIF
## 1  1      1      4   3
## 2  2      2      5   3
## 3  3      3      2  -1
## 4  4      4      3  -1
## 5  5      2      4   2
## 6  6      1      2   1
\end{verbatim}

\begin{verbatim}
##        vars  n  mean   sd median trimmed   mad min max range  skew kurtosis
## ID        1 30 15.50 8.80   15.5   15.50 11.12   1  30    29  0.00    -1.32
## ANG_T1    2 30  2.00 1.02    2.0    1.88  1.48   1   4     3  0.76    -0.57
## ANG_T2    3 30  3.33 1.21    3.0    3.33  1.48   1   5     4  0.04    -1.30
## DIF       4 30  1.33 1.27    1.0    1.38  1.48  -1   4     5 -0.13    -0.62
##          se
## ID     1.61
## ANG_T1 0.19
## ANG_T2 0.22
## DIF    0.23
\end{verbatim}

We can see there is a new `DIF' variable here.

Notice we're bootstrapping the mean of this difference directly, not a t-statistic as we did for the independent-samples design above. It's the same underlying question --- is this far from zero? --- just reached without the standardisation step in between. Nothing is lost by skipping it: with paired data there's a single already-differenced variable rather than two separately-scaled groups to compare, so there's less need to standardise before asking the question.

Next, we bootstrap a confidence interval for the \emph{mean of the difference variable}, to see whether it includes zero:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-91-1.pdf}}

\begin{verbatim}
## Response: DIF (numeric)
## # A tibble: 1 x 1
##    stat
##   <dbl>
## 1  1.33
\end{verbatim}

\begin{verbatim}
## # A tibble: 1 x 2
##   lower_ci upper_ci
##      <dbl>    <dbl>
## 1      0.9     1.73
\end{verbatim}

\begin{verbatim}
## [1] 2
\end{verbatim}

\begin{verbatim}
## [1] 3.333333
\end{verbatim}

We can do this in another way, but instead running a 1-sample t-test on the difference variable, testing whether it is different from zero:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-92-1.pdf}}

\begin{verbatim}
## # A tibble: 1 x 1
##   p_value
##     <dbl>
## 1       0
\end{verbatim}

\begin{verbatim}
## Response: DIF (numeric)
## # A tibble: 1 x 1
##    stat
##   <dbl>
## 1  1.33
\end{verbatim}

\begin{verbatim}
## [1] 2
\end{verbatim}

\begin{verbatim}
## [1] 3.333333
\end{verbatim}

Marvelous. We can see that the results from both variants of this test suggest that after listening to Ed Sheeran, our sample on average reported more anger.

1: Because the 95\% confidence interval does not include 0, I am confident in saying that there is some effect going on here.

2: Because the bootstrapped probability (as expressed by the p-value) of observing the mean difference in anger between T1 and T2 of 1.33 is very low (0 in our results, but the true value will not be exactly zero), I am confident in saying there is an effect here.

Not surprised\ldots{}

\textsuperscript{1}If you are a fan, friend, or relative of, or more importantly a lawyer for, Ed Sheeran, please note that this is not a real study. Furthermore, I am sure Ed Sheeran is a very nice person and I would delight in his company. This is merely a bit of humour.

\chapter{Introduction to Probability}\label{probability}

This Chapter provides examples and additional content for the first part of Lesson 7.

In this lesson, we will learn about the classical theory of probability, and how it can be used to construct measures of uncertainy of our estimates, and from there we can begin to draw inferences from the sample to the population.

\section{Simulating Coin Flips}\label{simulating-coin-flips}

The first thing we'll do is simulate 5000 fair coin flips.

Remember, this is another random process, so results will differ each time slightly

\begin{verbatim}
##   Heads Trial Cum_Heads Pct_Heads
## 1     1     1         1 1.0000000
## 2     1     2         2 1.0000000
## 3     0     3         2 0.6666667
## 4     0     4         2 0.5000000
## 5     1     5         3 0.6000000
## 6     0     6         3 0.5000000
\end{verbatim}

Below, we'll plot the results of this simulation for ease of interpretation

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-97-1.pdf}}

The thing to notice (in combination with the table of results above the plot) is that eventually the proportion of heads versus tails approaches 50\%, \emph{but it does not start out that way}.

In other words, for a fair coin toss sequence, the trials (tosses) are \emph{independent}, which means that for any given toss of the coin, the chance of a head or tail is 50\%. But, that's not the same as saying that you'll get equal numbers of heads or tails for every (or any) particular sequence of multiple tosses - it's not `self-correcting' in any other way than sheer weight of numbers. So, \textbf{eventually} over enough trials, the sequence should start to look like 50/50 heads and tails. But, that is not the tosses `self-correcting', simply that you are tossing a lot of coins. This is at the root of a number of fallacies about predicting random events, such as the Gambler's fallacy.

\section{Premier League Goals and the Poisson Distribution}\label{premier-league-goals-and-the-poisson-distribution}

Note, much of the inspiration and code for this section comes from: \url{https://bookdown.org/theqdata/honors_thesis/goal-scoring-and-the-poisson-process.html}

The data comes from: \url{https://www.football-data.co.uk/englandm.php} and is the EPL results for 21-22 Season

\begin{verbatim}
## # A tibble: 6 x 107
##   Div   Date                Time                HomeTeam   AwayTeam   FTHG  FTAG
##   <chr> <dttm>              <dttm>              <chr>      <chr>     <dbl> <dbl>
## 1 E0    2021-08-13 00:00:00 1899-12-31 20:00:00 Brentford  Arsenal       2     0
## 2 E0    2021-08-14 00:00:00 1899-12-31 12:30:00 Man United Leeds         5     1
## 3 E0    2021-08-14 00:00:00 1899-12-31 15:00:00 Burnley    Brighton      1     2
## 4 E0    2021-08-14 00:00:00 1899-12-31 15:00:00 Chelsea    Crystal ~     3     0
## 5 E0    2021-08-14 00:00:00 1899-12-31 15:00:00 Everton    Southamp~     3     1
## 6 E0    2021-08-14 00:00:00 1899-12-31 15:00:00 Leicester  Wolves        1     0
## # i 100 more variables: TOTG <dbl>, FTR <chr>, HTHG <dbl>, HTAG <dbl>,
## #   HTR <chr>, Referee <chr>, HS <dbl>, AS <dbl>, HST <dbl>, AST <dbl>,
## #   HF <dbl>, AF <dbl>, HC <dbl>, AC <dbl>, HY <dbl>, AY <dbl>, HR <dbl>,
## #   AR <dbl>, B365H <dbl>, B365D <dbl>, B365A <dbl>, BWH <dbl>, BWD <dbl>,
## #   BWA <dbl>, IWH <dbl>, IWD <dbl>, IWA <dbl>, PSH <dbl>, PSD <dbl>,
## #   PSA <dbl>, WHH <dbl>, WHD <dbl>, WHA <dbl>, VCH <dbl>, VCD <dbl>,
## #   VCA <dbl>, MaxH <dbl>, MaxD <dbl>, MaxA <dbl>, AvgH <dbl>, AvgD <dbl>, ...
\end{verbatim}

Next, let's see a few important bits of descriptive data. First, let's calculate the total number of games in a season:

\begin{verbatim}
##    Length     Class      Mode 
##       380 character character
\end{verbatim}

Next, how many goals in the season were there?

\begin{verbatim}
## [1] 1071
\end{verbatim}

And, what was the mean number of goals per game?

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   2.000   3.000   2.818   4.000   9.000
\end{verbatim}

OK, so now we have some idea of the goals per game, let's plot the distribution of goals.

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-102-1.pdf}}

If you've ever seen a Poisson distribution, you'll recognise this!

Let's check this out. First, let's create a table of all the matches with different numbers of goals.

\begin{verbatim}
## # A tibble: 9 x 2
##    TOTG ActualMatches
##   <dbl>         <int>
## 1     0            22
## 2     1            65
## 3     2            88
## 4     3            81
## 5     4            60
## 6     5            43
## 7     6            17
## 8     7             3
## 9     9             1
\end{verbatim}

Let's pull some stats of the Total Goals variable which well help us in a second.

\begin{verbatim}
##  min Q1 median Q3 max     mean       sd   n missing
##    0  2      3  4   9 2.818421 1.626359 380       0
\end{verbatim}

Importantly, because the Poisson distribution is described only by its mean, the first and most basic check we can do is whether the mean and the variance of the variable are the same (or at least very close). We already have the mean above (2.82), but what is the variance?

\begin{verbatim}
## [1] 2.645042
\end{verbatim}

This is not exactly the same, but good enough to be going on with.

So, it seems to me at least that we can use the Poisson distribution to at least somewhat accurately describe the probability of occurance of a given number of total goals scored in a premier league game, for this season at least.

The first thing I am going to do with that information is build a figure which compares the \emph{actual} numbers of goals scored in games with the \emph{predicted} numbers which would be scored if the goals scored were a perfect Poisson distribution.

Ideally, we would build the Poisson probabilities for 0-9 goals (which is the maximum number scored in 21-22). However, if you do this, you will find that the two tables (actual and predicted goals) will have different numbers of rows. This is because there were no games with 8 goals scored in 21-22, but one with 9.

This is a bit annoying, but not a big issue. What we do is build a Poisson probability distribution for 0-8 goals, and treat the final probability as that for `8 or more' goals, for the purposes of drawing our figure. This isn't strictly correct, because we have not collected up our actual goal data into that category, but we could do that if we wanted to.

Later, we'll break this down properly, but for our showy graph here we don't really need to do it.

\begin{verbatim}
##      PoisProb
## 1 0.059700132
## 2 0.168260108
## 3 0.237113915
## 4 0.222762284
## 5 0.156959477
## 6 0.088475579
## 7 0.041560239
## 8 0.016733465
## 9 0.005895244
\end{verbatim}

So, this table of probabilities, based on the Poisson distribution, allows us to make some predictions of what we could expect.

Remembering again that there are 380 games in a season, we can see that there is a 0.16 chance (i.e.~16\%) of seeing 4 goals in a game, which equates to 380 x 0.16 = 60.8 games we would expect to see in a season with 4 goals.

We can check this out by creating a new table comparing \textbf{actual} with \textbf{predicted} values\ldots{}

\begin{verbatim}
## # A tibble: 9 x 3
##    TOTG ActualMatches ExpectedMatches
##   <dbl>         <int>           <dbl>
## 1     0            22              23
## 2     1            65              64
## 3     2            88              90
## 4     3            81              85
## 5     4            60              60
## 6     5            43              34
## 7     6            17              16
## 8     7             3               6
## 9     9             1               2
\end{verbatim}

Remember, as you can see above, the row for `8' is missing, and it goes straight to 9. So, to repeat, just take (for simplicity's sake here) the final row of Expected Matches as meaning `2 games with 8 or more goals'

Anyway, it's pretty scarily close! E.g. in 21-22 there were 60 matches with 4 goals, and that is identical to the predicted amount (the difference with the predicted 60.8 from the probability distribution is likely a rounding error).

Let's plot this for the big payoff:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-109-1.pdf}}

Wow, that is pretty accurate! Remember, the `expected' figures are purely drawn from the \emph{entirely theoretical} Poisson distribution with a mean of 2.82. They very closely match the actual data.

To be honest though, that graph is really just a bit of show, but what we want is the `dough' (I had an old friend who was a golfer who always said 'drive for show, putt for dough\ldots). In other words, what could we do with this information?

Well, there is a lot of money spent on sports betting. We could use this information to help us decide whether we should place a bet that \textbf{there will be a game in the 22-23 season with 10 goals?} - assuming that this is originally being written before the 22-23 season (which is true).

Remember, there were 380 games in 21-22, none of which contained 10 goals. So, for ease of thinking about this, let's make the assumption that the PL started in 2021, and there were no games before to count (in reality, we would go back to the last time 10 goals were scored and count from there, but let's go with this in the first instance, and we'll expand later on, promise).

So, first, we need to calculate a new set of probabilities out to 10 goals.

\begin{verbatim}
##        PoisProb
## 1  0.0597001317
## 2  0.1682601080
## 3  0.2371139154
## 4  0.2227622837
## 5  0.1569594775
## 6  0.0884755792
## 7  0.0415602392
## 8  0.0167334647
## 9  0.0058952437
## 10 0.0018461421
## 11 0.0005203206
## 12 0.0001333166
\end{verbatim}

So, the number we want is the second-last probability: 0.00052.

This is because the table starts from the probability of 0 goals.

This means we can expect a game with 10 goals to happen every 1923 games

Calculate this by dividing 1 by the probability.

So, given there are 380 games per season, you would expect a game with 10 goals to happen once every 5 seasons.

So, if I started counting from the 21-22 season, the answer is NO, I would not bet on there being a game with 10 goals in the 22-23 Premier League season.

But, let's add some (pretty obvious) further context, as of November 2022, there have been 5 games in the history of the Premier League where 10 goals have been scored (and 1 with 11).

The Premier League has been going since 1992, and so far in Nov 22 there have been\ldots30 seasons. So, we are probably due one.

AND, the last game with 10 goals was in 2013 (Man Utd 5, West Brom 5)

So, I reckon we are \emph{definitely-maybe-probably} due one.

By the way, as of the start of the 22-23 season, there had been 21 matches with 9 goals. We would expect given our Poisson distribution that a game with 9 goals should happen every 1.4 seasons, meaning over 30 seasons we would expect\ldots. 21.

\subsection{2023 Update}\label{update}

So, the above example is \emph{totally unchanged} (other than some typo corrections and nicer wording) from when I originally coded it in 2022. The million dollar question: \emph{was there a game with 10 goals in the 22-23 season\ldots?}

The answer is no, there wasn't. But there were two with 9! Luckily I am not a betting man. I do think we are due one, so this season (2023-2024) is probably a good bet, but as of January 20th 2024, we still haven't had one\ldots{} Unless of course you think something has fundamentally changed about the premier league in recent years, changing the probability of goals (and thus suggesting recent seasons are drawn from a \emph{Poisson distribution with different characteristics} than past ones), which is in fact an interesting question in its own right\ldots{}

\subsection{2024 Update}\label{update-1}

Did we get one in 2023-2024\ldots again, no. The highest in fact this season was 8 - and there were 3 games with 8 goals in.

This is interesting. At this point (30 September, 2025) I find it tempting to put on a bet for a 10 goal game. I might do that, even though I am not much of a gambler. Here's why:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  The probabilities suggest we are well overdue one, unless there has been something fundamentally changing about the distribution of premier league goal.
\item
  The sort of change would logically need to be a reduction of average goals scored per game, which would change the mean of the Poisson distribution, reducing the probabilities of a 9-goal game.
\item
  However, the average goals per game is actually \textbf{\emph{increasing}}, according to the statistics - and you can check out the following to confirm this: \url{https://www.premierleague.com/news/4016793}
\item
  So, one could also draw the conclusion that the Poisson distribution is no longer a good fit - but this could be checked, and I would guess this isn't the case (you can check yourself).
\end{enumerate}

Interesting.

\chapter{Introduction to Statistics}\label{statistics}

This Chapter builds on the material in the second part of Lesson 7. Here, we begin to apply our probability concepts to the task of statistical inference in the `classical' way.

The theory explained and demonstrated here is the foundation of the (very large) majority of the quantitative business and management research you will read and use. Almost any time someone refers to a finding being \textbf{(statistically) significant} or to a \textbf{p-value}, they are using this idea. However, a major weakness in many social science fields - business and management being one - is that a rather large proportion of researchers don't actually understand the core principles of statistical inference, and are instead often just copying what other people have written, or told them to do.

So, if you can get your head around the next 3-4 chapters, you'll be in a strong position to work with what's already out there, and also to do your own solid research, if you wish.

\section{The Distribution of Sample Means, and the Central Limit Theorem}\label{the-distribution-of-sample-means-and-the-central-limit-theorem}

The first thing to cover is an extension of the ideas in the last chapter about sampling distributions. It's called the \emph{Central Limit Theorem}, and is often the source of much angst in statistics students (including myself). However, here I am actually going to demonstrate how it works, and show how is actually quite amazing.

To do so, I will use a synthetic data set of monthly incomes from 20 people. Let us treat this data set as the \textbf{population}.

\begin{verbatim}
## # A tibble: 6 x 2
##   Person Income
##   <chr>   <dbl>
## 1 A        5600
## 2 B        6000
## 3 C        6400
## 4 D        6800
## 5 E        7200
## 6 F        7600
\end{verbatim}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    5600    7500    9400    9400   11300   13200
\end{verbatim}

\begin{verbatim}
## [1] 2366.432
\end{verbatim}

Above, you'll see the important descriptive statistics, including the standard deviation of 2366.432. Let's plot the frequency distribution, and once we do so we will find that it is essentially uniform - every value occurs once and only once in the population.

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-114-1.pdf}}

Now, what I am going to do is take a \emph{single random sample of 2} from that population. This sample is taken `without replacement', if you are wondering, and so it is in essence exactly as if a researcher went into the field and took a sample from this population.

\begin{verbatim}
## [1] "One Random Combination of 2 of the 20 Income Values"
\end{verbatim}

\begin{verbatim}
## [1] 12800 11600
\end{verbatim}

Let's take the mean of the sample:

\begin{verbatim}
##    res1
## 1 12800
## 2 11600
\end{verbatim}

\begin{verbatim}
## [1] 12200
\end{verbatim}

The mean of the random sample of 2 will of course be different each time the sample is taken (e.g.~when writing this text, the mean was 10600, but this may not be the same in the version you are reading!)

Just for reference, the mean of the population (remember, the 20 people) was 9400

So, let's now do that for \textbf{every possible combination of 2 values} from this population.

Given there are n=20 values in the population, there are k=190 possible combinations of two values.

Note: This is not the same as bootstrapping - we are \emph{not} sampling with replacement here. We are instead taking combinations. The thing to think about is that this is the equivalent of taking every single possible sample of 2 that you could take from this population.

Remember the ping-pong balls I used in class to demonstrate!

Let's do it:

\begin{verbatim}
## [1] "Every Possible Combination of the 20 Income Values"
\end{verbatim}

\begin{verbatim}
##         [,1]  [,2]
##   [1,]  5600  6000
##   [2,]  5600  6400
##   [3,]  5600  6800
##   [4,]  5600  7200
##   [5,]  5600  7600
##   [6,]  5600  8000
##   [7,]  5600  8400
##   [8,]  5600  8800
##   [9,]  5600  9200
##  [10,]  5600  9600
##  [11,]  5600 10000
##  [12,]  5600 10400
##  [13,]  5600 10800
##  [14,]  5600 11200
##  [15,]  5600 11600
##  [16,]  5600 12000
##  [17,]  5600 12400
##  [18,]  5600 12800
##  [19,]  5600 13200
##  [20,]  6000  6400
##  [21,]  6000  6800
##  [22,]  6000  7200
##  [23,]  6000  7600
##  [24,]  6000  8000
##  [25,]  6000  8400
##  [26,]  6000  8800
##  [27,]  6000  9200
##  [28,]  6000  9600
##  [29,]  6000 10000
##  [30,]  6000 10400
##  [31,]  6000 10800
##  [32,]  6000 11200
##  [33,]  6000 11600
##  [34,]  6000 12000
##  [35,]  6000 12400
##  [36,]  6000 12800
##  [37,]  6000 13200
##  [38,]  6400  6800
##  [39,]  6400  7200
##  [40,]  6400  7600
##  [41,]  6400  8000
##  [42,]  6400  8400
##  [43,]  6400  8800
##  [44,]  6400  9200
##  [45,]  6400  9600
##  [46,]  6400 10000
##  [47,]  6400 10400
##  [48,]  6400 10800
##  [49,]  6400 11200
##  [50,]  6400 11600
##  [51,]  6400 12000
##  [52,]  6400 12400
##  [53,]  6400 12800
##  [54,]  6400 13200
##  [55,]  6800  7200
##  [56,]  6800  7600
##  [57,]  6800  8000
##  [58,]  6800  8400
##  [59,]  6800  8800
##  [60,]  6800  9200
##  [61,]  6800  9600
##  [62,]  6800 10000
##  [63,]  6800 10400
##  [64,]  6800 10800
##  [65,]  6800 11200
##  [66,]  6800 11600
##  [67,]  6800 12000
##  [68,]  6800 12400
##  [69,]  6800 12800
##  [70,]  6800 13200
##  [71,]  7200  7600
##  [72,]  7200  8000
##  [73,]  7200  8400
##  [74,]  7200  8800
##  [75,]  7200  9200
##  [76,]  7200  9600
##  [77,]  7200 10000
##  [78,]  7200 10400
##  [79,]  7200 10800
##  [80,]  7200 11200
##  [81,]  7200 11600
##  [82,]  7200 12000
##  [83,]  7200 12400
##  [84,]  7200 12800
##  [85,]  7200 13200
##  [86,]  7600  8000
##  [87,]  7600  8400
##  [88,]  7600  8800
##  [89,]  7600  9200
##  [90,]  7600  9600
##  [91,]  7600 10000
##  [92,]  7600 10400
##  [93,]  7600 10800
##  [94,]  7600 11200
##  [95,]  7600 11600
##  [96,]  7600 12000
##  [97,]  7600 12400
##  [98,]  7600 12800
##  [99,]  7600 13200
## [100,]  8000  8400
## [101,]  8000  8800
## [102,]  8000  9200
## [103,]  8000  9600
## [104,]  8000 10000
## [105,]  8000 10400
## [106,]  8000 10800
## [107,]  8000 11200
## [108,]  8000 11600
## [109,]  8000 12000
## [110,]  8000 12400
## [111,]  8000 12800
## [112,]  8000 13200
## [113,]  8400  8800
## [114,]  8400  9200
## [115,]  8400  9600
## [116,]  8400 10000
## [117,]  8400 10400
## [118,]  8400 10800
## [119,]  8400 11200
## [120,]  8400 11600
## [121,]  8400 12000
## [122,]  8400 12400
## [123,]  8400 12800
## [124,]  8400 13200
## [125,]  8800  9200
## [126,]  8800  9600
## [127,]  8800 10000
## [128,]  8800 10400
## [129,]  8800 10800
## [130,]  8800 11200
## [131,]  8800 11600
## [132,]  8800 12000
## [133,]  8800 12400
## [134,]  8800 12800
## [135,]  8800 13200
## [136,]  9200  9600
## [137,]  9200 10000
## [138,]  9200 10400
## [139,]  9200 10800
## [140,]  9200 11200
## [141,]  9200 11600
## [142,]  9200 12000
## [143,]  9200 12400
## [144,]  9200 12800
## [145,]  9200 13200
## [146,]  9600 10000
## [147,]  9600 10400
## [148,]  9600 10800
## [149,]  9600 11200
## [150,]  9600 11600
## [151,]  9600 12000
## [152,]  9600 12400
## [153,]  9600 12800
## [154,]  9600 13200
## [155,] 10000 10400
## [156,] 10000 10800
## [157,] 10000 11200
## [158,] 10000 11600
## [159,] 10000 12000
## [160,] 10000 12400
## [161,] 10000 12800
## [162,] 10000 13200
## [163,] 10400 10800
## [164,] 10400 11200
## [165,] 10400 11600
## [166,] 10400 12000
## [167,] 10400 12400
## [168,] 10400 12800
## [169,] 10400 13200
## [170,] 10800 11200
## [171,] 10800 11600
## [172,] 10800 12000
## [173,] 10800 12400
## [174,] 10800 12800
## [175,] 10800 13200
## [176,] 11200 11600
## [177,] 11200 12000
## [178,] 11200 12400
## [179,] 11200 12800
## [180,] 11200 13200
## [181,] 11600 12000
## [182,] 11600 12400
## [183,] 11600 12800
## [184,] 11600 13200
## [185,] 12000 12400
## [186,] 12000 12800
## [187,] 12000 13200
## [188,] 12400 12800
## [189,] 12400 13200
## [190,] 12800 13200
\end{verbatim}

\begin{verbatim}
## [1] "Number of combinations without repetition"
\end{verbatim}

\begin{verbatim}
## [1] 190
\end{verbatim}

That was a rather long exhibit up there, but I wanted to show you that this was actually really done properly, and we have 190 combinations.

Next, let us create the means of each of the 190 combinations

\begin{verbatim}
##     X1   X2 MDIST
## 1 5600 6000  5800
## 2 5600 6400  6000
## 3 5600 6800  6200
## 4 5600 7200  6400
## 5 5600 7600  6600
## 6 5600 8000  6800
\end{verbatim}

That's just the first 6 (the head of the data set), but you can rest assured that there are 190 means created here.

OK, so here is the kicker. Let's plot a histogram of these 190 means.

Remember, a histogram is a frequency distribution:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-119-1.pdf}}

Well well well!

Even though the original population was a completely uniform distribution with a mean of 9400, the distribution of all of the sample means looks quite a lot like a normal distribution / bell curve!

Let's overlay one on it as well to make the point\ldots{}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-120-1.pdf}}

Further, let's take the mean of those means\ldots{}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    5800    8200    9400    9400   10600   13000
\end{verbatim}

Hello! It turns out, the mean of those means is the \emph{population mean!!!}

This, in a demonstration, is \emph{the central limit theorem.}

Let's \textbf{move back to the slides} to talk about this some more.

\section{Demonstrating Confidence Intervals}\label{conf}

Below I will demonstrate the idea of confidence intervals as a measure of precision, and at the same time help to really lock in the correct interpretation of what a confidence interval really means.

To do so, I will continue the in-class example of WBS Ph.D.~graduate salaries. However, here, I will \textbf{simulate} the population distribution that we have sampled from. Let's recap:

Sample size (N) = 42

Sample mean = 170,000

Sample SD = 46617.4

I will simulate a population distribution that this sample could quite conceivably have come from. It will have the following features:

Population mean = 165,000

Population SD = 40000

I will also assume that the population distribution is \emph{normal}. That is, the distribution of all business and management Ph.D.~starting salaries is shaped like a bell curve - the normal distribution (remember birth weights from the last chapter). This is a reasonable assumption in my view, given the features of the phenomena we are investigating.

The important thing to remember is not really the population distribution of salaries (which is just used here to simulate the population), but the \emph{sampling distribution of the means}. Remember, the central limit theorem shows us that \textbf{whatever the shape of the population distribution we are sampling from}, the sampling distribution of the means will take the form of a normal distribution, with a mean of the population mean.

So, below, I will simulate the population, and then calculate 100 confidence intervals for 4 different sample sizes (5, 10, 42, 100), to demonstrate two things:

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  How confidence intervals get more precise as sample size increases, and
\item
  How to interpret your specific confidence interval as simply one possibility of many.
\end{enumerate}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-123-1.pdf}} \pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-123-2.pdf}} \pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-123-3.pdf}} \pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-123-4.pdf}}

So, you can see that the confidence intervals for each of the 100 samples at a given sample size all cluster around the mean, but are wider as sample size is lower. That makes sense intuitively.

Looking specifically at our example N of 42, we can estimate which one of the 100 that might be, and see how the CI for sample means of about that size does include the real population mean of 165. You can also see there are a number of coloured CIs which do \textbf{not} include the sample mean. This shows how to interpret a CI.

Specifically, \textbf{your actual sample} is one of a very large amount of possible samples from the population (here we took 100 but we could have taken many more). The CI calculation essentially creates a CI with the width so that, out of 100 random samples, approximately 95 will actually contain the \emph{true population mean}.

As such, we can see how it is clearly a measure of the \textbf{precision} of the estimate. For a compelling visualization of this, look how wide the CIs for N=5 are.

One thing to remember though is the `law of large numbers' here. You might notice that not all of the CI plots contain exactly 5 intervals that do not contain the mean. This is analagous to the idea of coin flipping - it's just probability over very large numbers of trials, not saying that `out of every 100, exactly 5 will not include the population mean'. But, over a very large number of trials, we can expect the amount of intervals that do not include the mean to tend towards 5\%, in the same way that over a large number of coin flips, the proportion of heads tends towards 50\%.

\section{Rate of Change in Football Goals per Season}\label{rate-of-change-in-football-goals-per-season}

In this example, I'll build on the idea of confidence intervals, to show how we can test hypotheses about the world. I'll continue on with my football goals example. Here, I'm using data from \url{https://www.footballhistory.org/league/premier-league-statistics.html}

I hand-entered this into a spreadsheet, and calculated the additional stuff.

\begin{verbatim}
## # A tibble: 6 x 7
##   Season  Games Goals   GPG    SE Lower95CI Upper95CI
##   <chr>   <dbl> <dbl> <dbl> <dbl>     <dbl>     <dbl>
## 1 1995-96   380   988  2.6   31.4      926.     1050.
## 2 1996-97   380   970  2.55  31.1      909.     1031.
## 3 1997-98   380  1019  2.68  31.9      956.     1082.
## 4 1998-99   380   959  2.52  31.0      898.     1020.
## 5 1999-00   380  1060  2.79  32.6      996.     1124.
## 6 2000-01   380   992  2.61  31.5      930.     1054.
\end{verbatim}

You can see here I have calculated the standard errors from the yearly goal totals (which represent that year's underlying rate of goal occurrence), then used that to calculate the 95\% Confidence Interval limits

We can use these to create a nifty chart with the error bars\ldots drawing from the code used by Spiegelhalter in his book for Figure 9.4 available on his github (linked in the code).

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-125-1.pdf}}

From this chart, and looking at the data itself, we can see that the 95\% Intervals overlap, so it is hard to conclude that the underlying rate of goals has changed significantly year on year. Yes, even in the pandemic.

The closest we get in fact is between the 2008-2009 and 2009-10 season. Interestingly, this corresponds to when Man City were bought, and it is evident that the top teams scored a lot more that year.

In fact, you could add data for the next few seasons, to directly test the conclusion that the Premier League drew in the article I referenced in Chapter \ref{probability}: \url{https://www.premierleague.com/news/4016793}

This is a stringent test however, and the ONS suggest that you can also test the change by using a Z-test, which \emph{directly tests the hypothesis} that the change is zero, using the assumption that the events are Poisson distributed (we agree) and also that when the number of events are large (generally over 20), we can use an approximation to the normal distribution.

See: \url{https://www.ons.gov.uk/peoplepopulationandcommunity/crimeandjustice/compendium/focusonviolentcrimeandsexualoffences/yearendingmarch2016/homicide\#statistical-interpretation-of-trends-in-homicides}

The z-test is simply explained in the linked article from the BMJ: \url{https://www.bmj.com/content/332/7552/1256}

It links us nicely to the next lesson, because it is aiming to test a \emph{specific hypothesis} that the difference is zero\ldots{}

If you open the data file below, you can see I have calculated the z-test results for the difference between each season, year-on-year.

\begin{verbatim}
## # A tibble: 6 x 9
##   Season  Games Goals   GPG    SE Lower95CI Upper95CI Change      Z
##   <chr>   <dbl> <dbl> <dbl> <dbl>     <dbl>     <dbl>  <dbl>  <dbl>
## 1 1995-96   380   988  2.6   31.4      926.     1050.     NA NA    
## 2 1996-97   380   970  2.55  31.1      909.     1031.    -18 -0.407
## 3 1997-98   380  1019  2.68  31.9      956.     1082.     49  1.10 
## 4 1998-99   380   959  2.52  31.0      898.     1020.    -60 -1.35 
## 5 1999-00   380  1060  2.79  32.6      996.     1124.    101  2.25 
## 6 2000-01   380   992  2.61  31.5      930.     1054.    -68 -1.50
\end{verbatim}

The `Z' column is what we are interested in, and we are looking for a z-value greater than + or - 1.96 for a 95\% test (analogous to the 95\% intervals we've been dealing with so far).

A simple way to visualize this is to plot the z-values for each season, and include `control lines' which represent the + or -1.96 z value, beyond which we consider there to be a significant difference

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-127-1.pdf}}

So, we can see that the 1999-2000 season, and the 2009-10 seasons exceed our z values, making them significantly different from the seasons before.

Of course, we could do z-tests for any combination of two seasons, if we had a good reason. You can see on the ONS website they do this for different years' murder rates to make a point.

\chapter{Classical Statistical Hypothesis Testing}\label{H-testing}

This Chapter relates to the first part of Lecture 8, and contains some (re)worked examples from earlier chapters / lessons, focusing specifically on the hypothesis testing aspect of them.

\section{Testing a Real Hypothesis: Are WBS PhD Salaries Different?}\label{salary-ztest}

Back in Section \ref{conf} we used the WBS PhD graduate salary data --- 42 graduates, mean starting salary \$170,000, standard deviation \$46,617.4 --- to build a confidence interval. That was useful, but it didn't actually answer the question I cared about when I started looking at this data: can I claim, in the PhD program prospectus, that WBS graduates earn more than graduates elsewhere?

A confidence interval alone doesn't let me say that. It tells me something about precision, not about a comparison. To make a comparison I need a number to compare against, and I need to state, in advance, how different my sample would have to be before I'm willing to call it a real difference rather than the ordinary noise you'd expect from any sample of 42 people.

That comparison number is my null hypothesis, and I didn't invent it out of thin air. The American Marketing Association runs a doctoral special interest group, and every year they survey new marketing PhD graduates about starting salary and send me the results --- mostly, I suspect, to depress me about what I earned in my first job. The most recent figure was US\$145,000. It's not a perfect number (a proper job would involve going round every PhD director in the business school and averaging across fields), but it's a real, defensible estimate of ``what graduates elsewhere earn'', which is exactly what a null hypothesis needs to be.

\begin{itemize}
\tightlist
\item
  \textbf{Null hypothesis:} the average starting salary of WBS PhD graduates is not different from US\$145,000.
\item
  \textbf{Sample:} 42 WBS graduates, sample mean \$170,000, sample SD \$46,617.4 --- the same sample as Section \ref{conf}.
\end{itemize}

Before doing any calculation, there's a decision to make, and it's the decision that usually gets made by accident, halfway through the arithmetic, once everyone's attention is already used up. Did I hypothesize a direction? I could have framed the alternative as directional --- WBS graduates earn \emph{more} than \$145,000 --- or non-directional --- WBS graduates earn a \emph{different} amount, which could be more or less. A directional hypothesis is the stronger claim, and it has to be committed to in advance, not read off the result after the fact.

Here's the honest version: privately, of course I was expecting WBS graduates to earn more. But my null hypothesis, as written, was ``not different from \$145,000'', which commits me to the non-directional alternative whatever I was quietly hoping. I didn't encode the direction I actually believed in, so I don't get to use it. That's not me being pedantic about my own case for the sake of the example --- it's the actual mechanism. A lot of people hypothesize a direction in their head and then run a two-tailed test anyway, mostly because no one ever made them sit down and decide properly. Here, the test is two-tailed.

With that settled, the arithmetic is almost an anticlimax. What I want to know is: if the population mean really is \$145,000, how far away --- in standardised units --- is my observed sample mean of \$170,000?

\begin{verbatim}
## [1] 3.475495
\end{verbatim}

Same standardisation logic as everywhere else in this book: take what I observed, subtract what I'd expect under the null, divide by how much variation sampling alone would produce. The effect is to redraw the whole problem on a scale where the null sits at zero, and my sample mean lands wherever it lands. A z of around 3.5 means my sample mean is roughly three and a half standard errors out from where the null says it should be --- well beyond the 1.96 we've used as our 95\% cutoff elsewhere.

\begin{verbatim}
## [1] 0.0005099124
\end{verbatim}

That p-value --- somewhere around 0.0005, about 1 in 2,000 --- means: \emph{if} the null is true, the probability of drawing a sample of 42 with a mean this far out, in either direction, is about 1 in 2,000. It does not mean there's a 1-in-2,000 chance the null is true. A p-value says nothing about the probability of any hypothesis. It's a statement about how surprising the data would be under an assumption, not a verdict on the assumption.

So, do I reject the null? This is a judgement, not a law of nature. Nothing about this p-value compels a conclusion --- I could, in principle, decide this is just an unusually extreme sample from a population that really does average \$145,000, and nothing in the maths would stop me. What I actually do, like almost everyone else, is apply a cutoff --- conventionally p \textless{} 0.05 --- and treat anything below it as evidence against the null. That cutoff exists because people like rules, not because 0.05 has any special status in nature. Here the data are miles past any conventional threshold, so the call is easy. It won't always be, and when it isn't, the arithmetic still won't make the decision for you.

\textbf{Directional vs non-directional, side by side:}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
One-tailed (directional)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Two-tailed (non-directional)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Alternative hypothesis & States a direction --- e.g.~``bigger than \$145,000'' & States only ``different from \$145,000'' \\
Must be decided & Before looking at the data & Before looking at the data \\
Relationship between the p-values & Half the two-tailed p, for the same z & Double the one-tailed p, for the same z \\
This example & Not what I actually committed to & What I actually committed to \\
\end{longtable}
}

\section{Premier League Goals and the Poisson Distribution}\label{premier-league-goals-and-the-poisson-distribution-1}

In this section, we are not really worried about the \emph{actual} goals or anything like that. What we are concerned about is formally testing the hypothesis that Premier League goals per game actually do follow a Poisson distribution. To do this, we will use what is called a \textbf{chi-square} test, which uses the chi-square statistic.

Chi-square is a fantastically versatile statistic, which is often used to compare tables of observations. Commonly, we compare a table of observed events with a table of events that we would expect if the null hypothesis were true in the population. The chi-square value is the measure of the difference between observed and expected counts in the table. We can use it here to compare the amount of goals we actually did observe in the 21-22 season, with those that we would \emph{expect} to observe if the goals per game really do follow a Poisson distribution.

Again, much of the idea and code for this section comes from: \url{https://bookdown.org/theqdata/honors_thesis/goal-scoring-and-the-poisson-process.html}

The data comes from: \url{https://www.football-data.co.uk/englandm.php} and is the EPL results for 21-22 Season, with a new column of Total Goals (TOTG) created by me in Excel.

\begin{verbatim}
## # A tibble: 6 x 107
##   Div   Date                Time                HomeTeam   AwayTeam   FTHG  FTAG
##   <chr> <dttm>              <dttm>              <chr>      <chr>     <dbl> <dbl>
## 1 E0    2021-08-13 00:00:00 1899-12-31 20:00:00 Brentford  Arsenal       2     0
## 2 E0    2021-08-14 00:00:00 1899-12-31 12:30:00 Man United Leeds         5     1
## 3 E0    2021-08-14 00:00:00 1899-12-31 15:00:00 Burnley    Brighton      1     2
## 4 E0    2021-08-14 00:00:00 1899-12-31 15:00:00 Chelsea    Crystal ~     3     0
## 5 E0    2021-08-14 00:00:00 1899-12-31 15:00:00 Everton    Southamp~     3     1
## 6 E0    2021-08-14 00:00:00 1899-12-31 15:00:00 Leicester  Wolves        1     0
## # i 100 more variables: TOTG <dbl>, FTR <chr>, HTHG <dbl>, HTAG <dbl>,
## #   HTR <chr>, Referee <chr>, HS <dbl>, AS <dbl>, HST <dbl>, AST <dbl>,
## #   HF <dbl>, AF <dbl>, HC <dbl>, AC <dbl>, HY <dbl>, AY <dbl>, HR <dbl>,
## #   AR <dbl>, B365H <dbl>, B365D <dbl>, B365A <dbl>, BWH <dbl>, BWD <dbl>,
## #   BWA <dbl>, IWH <dbl>, IWD <dbl>, IWA <dbl>, PSH <dbl>, PSD <dbl>,
## #   PSA <dbl>, WHH <dbl>, WHD <dbl>, WHA <dbl>, VCH <dbl>, VCD <dbl>,
## #   VCA <dbl>, MaxH <dbl>, MaxD <dbl>, MaxA <dbl>, AvgH <dbl>, AvgD <dbl>, ...
\end{verbatim}

\begin{verbatim}
##    Length     Class      Mode 
##       380 character character
\end{verbatim}

The above is a quick way of calculating / checking the total number of games if you don't know already.

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   2.000   3.000   2.818   4.000   9.000
\end{verbatim}

\begin{verbatim}
## [1] 1071
\end{verbatim}

First, let's create a table of all the matches with different numbers of goals, just as we did in Chapter \ref{probability}.

\begin{verbatim}
## # A tibble: 9 x 2
##    TOTG ActualMatches
##   <dbl>         <int>
## 1     0            22
## 2     1            65
## 3     2            88
## 4     3            81
## 5     4            60
## 6     5            43
## 7     6            17
## 8     7             3
## 9     9             1
\end{verbatim}

Here, we have a problem. The chi-square test has a condition that the expected values in every column will be greater than 5, and as we go down the Poisson probabilities (i.e.~for higher total goals), it is clear that this will start to become a problem for us.

The solution is simple, we combine the numbers for larger numbers of goals into a single `x and above' variable. Here, let's do it for 6 goals and above.

To do so, we first need to create a new table, where the values for 6 and above are combined into a new row.

\begin{verbatim}
## # A tibble: 7 x 2
##   TOTG      ActualMatches
##   <chr>             <int>
## 1 0                    22
## 2 1                    65
## 3 2                    88
## 4 3                    81
## 5 4                    60
## 6 5                    43
## 7 6 or more            21
\end{verbatim}

Now we can create the Poisson distribution for the relevant mean, which means we first need to create the stats\ldots{}

\begin{verbatim}
##  min Q1 median Q3 max     mean       sd   n missing
##    0  2      3  4   9 2.818421 1.626359 380       0
\end{verbatim}

Below is some code which will help us to create the distributions and also check them.

\begin{verbatim}
## [1] 2.818421
\end{verbatim}

\begin{verbatim}
## [1] 2.645042
\end{verbatim}

As we saw in Chapter \ref{probability}, while for a Poisson distribution these should be exactly the same, we decided that they were good enough to be going on with.

So, let's actually check this formally with the Chi-square test.

We do so by first creating a table of the Poisson probabilities for x or fewer goals, for the Poisson with a mean of 2.818 (i.e.~the variable MeanGoals)

\begin{verbatim}
##     PoisProb
## 1 0.05970013
## 2 0.16826011
## 3 0.23711392
## 4 0.22276228
## 5 0.15695948
## 6 0.08847558
## 7 0.04156024
\end{verbatim}

This allows us to make some predictions of what we could expect.

Remembering again that there are 380 games in a season, we can see that there is a 0.16 chance of seeing 4 goals in a game, which equates to 380 x 0.16 = 60.8 games we would expect to see in a season with 4 goals.

We can check this out by creating a new table comparing actual with predicted values\ldots{}

\begin{verbatim}
##        TOTG ActualMatches   PoisProb ExpectedMatches
## 1         0            22 0.05970013              23
## 2         1            65 0.16826011              64
## 3         2            88 0.23711392              90
## 4         3            81 0.22276228              85
## 5         4            60 0.15695948              60
## 6         5            43 0.08847558              34
## 7 6 or more            21 0.04156024              16
\end{verbatim}

This looks quite frighteningly close up until you get to the 5 row. It will be interesting to see how we go with a formal chi-square test.

\begin{verbatim}
## 
##  Chi-squared test for given probabilities
## 
## data:  NewGoalsTable$ActualMatches
## X-squared = 4.2244, df = 6, p-value = 0.6463
\end{verbatim}

The P-value here is actually 0.64. This suggests that there is not a significant difference between the distribution of the actual goals, and that which would be expected if they did follow a Poisson distribution.

\section{Correlation Significance Tests}\label{correlation-significance-tests}

Here, we revisit our correlation between GDP per capita, and Happiness metrics, which I pulled from Our Word in Data:

\begin{verbatim}
##    Country            Happiness         GDPpc             Pop           
##  Length:249         Min.   :2.400   Min.   :   731   Min.   :8.090e+02  
##  Class :character   1st Qu.:4.670   1st Qu.:  4917   1st Qu.:4.153e+05  
##  Mode  :character   Median :5.530   Median : 12655   Median :5.596e+06  
##                     Mean   :5.492   Mean   : 20464   Mean   :5.918e+07  
##                     3rd Qu.:6.260   3rd Qu.: 30100   3rd Qu.:2.421e+07  
##                     Max.   :7.820   Max.   :112557   Max.   :4.663e+09  
##                     NA's   :96      NA's   :52       NA's   :7
\end{verbatim}

\begin{verbatim}
## # A tibble: 6 x 4
##   Country        Happiness GDPpc      Pop
##   <chr>              <dbl> <dbl>    <dbl>
## 1 Afghanistan         2.4   1971 38972236
## 2 Albania             5.2  13192  2866850
## 3 Algeria             5.12 10735 43451668
## 4 American Samoa     NA       NA    46216
## 5 Andorra            NA       NA    77723
## 6 Angola             NA     6110 33428490
\end{verbatim}

Let's not worry about plotting the data, and go straight to the correlation:

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  x and y
## t = 13.502, df = 146, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6636288 0.8092331
## sample estimates:
##      cor 
## 0.745184
\end{verbatim}

Here are our results. The estimate is a correlation, and we test that using the \textbf{t statistic}. The \emph{t-value} is simply the estimate divided by the standard error (which we can't see in this output), and is interpreted essentially as `how far from 0 is the estimate, in standard errors'.

The \emph{p}-value for t is very very small, and obviously less than 0.05.

Conclusion - reject null hypothesis, accept alternative hypothesis (as always, pending better evidence).

Importantly, this does not mean that the \textbf{true correlation in the population} is 0.745, simply that it is \emph{very unlikely to be zero}.

We can then look at our estimate of 0.745, and - even better - our confidence interval (see Section \ref{conf} for information on how to interpret confidence intervals), to gain some indication of the likely true correlation in the population.

\section{Regression Significance Tests}\label{regression-significance-tests}

The process to asses the significance of regression estimates is very very similar to that for correlations. Let's revisit the heart disease data set we used earlier.

\begin{verbatim}
##       ...1           biking          smoking        heart.disease    
##  Min.   :  1.0   Min.   : 1.119   Min.   : 0.5259   Min.   : 0.5519  
##  1st Qu.:125.2   1st Qu.:20.205   1st Qu.: 8.2798   1st Qu.: 6.5137  
##  Median :249.5   Median :35.824   Median :15.8146   Median :10.3853  
##  Mean   :249.5   Mean   :37.788   Mean   :15.4350   Mean   :10.1745  
##  3rd Qu.:373.8   3rd Qu.:57.853   3rd Qu.:22.5689   3rd Qu.:13.7240  
##  Max.   :498.0   Max.   :74.907   Max.   :29.9467   Max.   :20.4535
\end{verbatim}

\begin{verbatim}
## # A tibble: 6 x 4
##    ...1 biking smoking heart.disease
##   <dbl>  <dbl>   <dbl>         <dbl>
## 1     1  30.8    10.9          11.8 
## 2     2  65.1     2.22          2.85
## 3     3   1.96   17.6          17.2 
## 4     4  44.8     2.80          6.82
## 5     5  69.4    16.0           4.06
## 6     6  54.4    29.3           9.55
\end{verbatim}

Let's go straight to the multiple regression model.

\begin{verbatim}
## 
## Call:
## lm(formula = heart.disease ~ biking + smoking, data = Heart)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.1789 -0.4463  0.0362  0.4422  1.9331 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 14.984658   0.080137  186.99   <2e-16 ***
## biking      -0.200133   0.001366 -146.53   <2e-16 ***
## smoking      0.178334   0.003539   50.39   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.654 on 495 degrees of freedom
## Multiple R-squared:  0.9796, Adjusted R-squared:  0.9795 
## F-statistic: 1.19e+04 on 2 and 495 DF,  p-value: < 2.2e-16
\end{verbatim}

We interpret these just as we did the correlation significance tests.

The t-value is large, and the \emph{p}-value (two-tailed) is small.

Interestingly, here we are given `stars' for the different levels of significance, so to some extent the software is doing some decision making for you. To be honest, I always caution against relying solely on looking for `stars' (it's actually a bit of a running joke amongst the people who have known me a long time that I once told an entire class in the 1990s to `just look for the stars'). That's because the actual significance or not decision is based on the critical value and one- or two-tailed decision. The software often makes an assumption of 0.05 critical value for \emph{p}, two-tailed, and calculates the `stars' based on that. Sometimes that can conflict with the decision you have made yourself about what should be significant or not. That can trip you up if you didn't know to change these values in the software package.

Further, it also sort of entrenches the idea that things can be `more' or `less' statistically significant. Take a look at the results above, you'll see 3 stars represents a significance of `0', and 2 stars represents `0.001', boring old `0.05' only gets a single star, and `0.1' gets a dot. I'm not a fan here because this encourages the analyst to post-hoc make decisions about `marginally' significant, or `very' significant. These concepts do not actually exist in real statistical theory. Instead, you decide your critical value \textbf{\emph{a priori}}, and you either pass or fail it. As Yoda may have said if he was a statistician, ``Pass or do not pass. There is no marginally significant''.

Am I perfect? No.~Specifically, do any of my papers use the language of `marginal' significance? Sure, I bet you could find them. I am never a fan though, and I can promise you I argued about it at the time!

\chapter{ANOVA}\label{ANOVA}

This Chapter provides analysis and examples related to the second part of Lecture 8.

Here, I'll demonstrate the basic application of ANOVA on the simple 3-group case of the Ed Sheeran Study, and go from there to introduce some classic `concerns' with the statistical hypothesis testing methodology.

\begin{verbatim}
##        ID     GROUP      ANGER      
##  Min.   : 1   1:15   Min.   :1.000  
##  1st Qu.:12   2:15   1st Qu.:2.000  
##  Median :23   3:15   Median :3.000  
##  Mean   :23          Mean   :3.222  
##  3rd Qu.:34          3rd Qu.:4.000  
##  Max.   :45          Max.   :5.000
\end{verbatim}

\begin{verbatim}
## # A tibble: 6 x 3
##      ID GROUP ANGER
##   <dbl> <fct> <dbl>
## 1     1 1         2
## 2     2 2         5
## 3     3 1         2
## 4     4 3         3
## 5     5 2         4
## 6     6 3         2
\end{verbatim}

Let's create a quick table of the group means, and visualize it with a simple boxplot of the groups.

\begin{verbatim}
## # A tibble: 3 x 5
##   GROUP variable     n  mean    sd
##   <fct> <fct>    <dbl> <dbl> <dbl>
## 1 1     ANGER       15  2.33 0.816
## 2 2     ANGER       15  4.27 0.704
## 3 3     ANGER       15  3.07 1.03
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-152-1.pdf}}

Interesting picture. Group 1 is the control group, Group 2 is those who heard Ed Sheeran, Group 3 is those who heard other music. This is what we might call `model-free' analysis. We are just looking at the data to see if intuitively it looks like we expect it to.

Let's run an ANOVA now, which places a statistical model on it, and tests whether or not the data supports the model.

\begin{verbatim}
## ANOVA Table (type II tests)
## 
##   Effect DFn DFd      F        p p<.05   ges
## 1  GROUP   2  42 19.235 1.17e-06     * 0.478
\end{verbatim}

Results here suggest there is a significant effect (p-value is very small). We also have an \emph{effect size} measure (`ges', or generalized eta-squared) which is very useful to us, and suggests the effect is quite large. This can be interpreted similarly to a regression coefficient (which is also an effect size measure), and is the amount of variance in the dependent variable (Anger) that is explained by group membership.

However, ANOVA only tests the \emph{general effect} of the treatment / group. We don't know whether this is because of the difference between \textbf{all of the groups}, or only \textbf{some}. E.g., is it that there is an effect of music in general (i.e.~between Control and Ed, and Control and Music, but not between Ed and Music), or that Ed specifically is anger-inducing (in which case we would see an effect between Ed and Music, and Ed and Control, and not between Music and Control).

\section{Post-Hoc Testing}\label{post-hoc-testing}

We can investigate this using \textbf{post-hoc tests}, which compare the difference between each pair of groups. There are many different types of post-hoc test for ANOVA, but the most typical one to use is the Tukey's test, which is what we will do here.

\begin{verbatim}
## # A tibble: 3 x 9
##   term  group1 group2 null.value estimate conf.low conf.high       p.adj
## * <chr> <chr>  <chr>       <dbl>    <dbl>    <dbl>     <dbl>       <dbl>
## 1 GROUP 1      2               0    1.93    1.17       2.70  0.000000734
## 2 GROUP 1      3               0    0.733  -0.0313     1.50  0.0625     
## 3 GROUP 2      3               0   -1.2    -1.96      -0.435 0.00126    
## # i 1 more variable: p.adj.signif <chr>
\end{verbatim}

We can actually plot these results in a really effective way:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-155-1.pdf}}

This very clearly tells us that it is the \emph{Ed Sheeran group (2)} that is driving these results, and there isn't much to choose between the control group, and the `music' group.

However, this type of post-hoc analysis has the potential for what is known as a \emph{multiple comparisons problem}, which we might need to deal with.

Let's take a look \textbf{back in the slide deck\ldots{}}

Remember, there are many other things that if we were doing ANOVA that we would also look to deal with - such as the various assumptions required of ANOVA, and so forth. But, they are beyond our scope in this class. Suffice to say that this has only scratched the surface of ANOVA so far.

\chapter{Issues with Significance Testing}\label{Issues}

This chapter provides examples and analysis for the third part of Lecture 8, and also parts of Lecture 9.

In this chapter, I'll explore examples of two common `issues' or `debates' regarding statistical significance testing, applied to two of our prior examples.

But first, let's unpack more about the Ed Sheeran Study, and the multiple comparisons problem.

\section{More on the Multiple Comparisons Problem}\label{more-on-the-multiple-comparisons-problem}

In this section, I'll provide some visualizations which can help us to understand the problem with multiple comparisons.

However, it's worth noting that the results depend on a number of assumptions about the research and what the real world actually looks like. The latter for sure we can never know. So, do bear that in mind.

First, let's visualize the situation I just discussed in the slides. We test 100 hypotheses, and in every case, the null is true in the population (remember, we cannot know the true state of the population in reality). Below, each grey box represents a hypothesis we test.

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-158-1.pdf}}

Now, remember, \textbf{even if all null hypotheses are true}, our significance level, or \emph{p} = 0.05, so we have to expect that \emph{on average} we would expect \textbf{5} of these hypotheses tests to return \emph{p}-values \textless{} 0.05, and thus we would reject the null. This is known as a \textbf{false positive}.

You might wonder how we could reduce the chances of false positive to zero. You could do this by setting your required \emph{p} to be exactly zero. Do you see the problem here? You would certainly solve the false positive problem. But, you would also accept \emph{all} null hypotheses. You would never actually find a statistically significant result in your research. Unless the null hypothesis really \emph{was} true in the population in every single case, you would be inevitably missing out on making some discoveries.

Moving on, let's visualize the situation in hand here. Below, the same 100 hypothesis tests (remember, the null is true in all cases), but this time I have marked in red the expected level of false positives.

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-159-1.pdf}}

Now, that is just the \emph{expected} level for every 100 tests. If you remember from the discussion in Section \ref{conf}, it may not be you get \emph{exactly} 5 false positives in 100 tests, just that you would expect the long run average number of false positives to be 5\%, in an all-null world.

So, we can look at it through a different lens. What is the probability that you would get \textbf{at least one false positive} in any given batch of multiple tests.

That is known as the \emph{familywise error rate}, and it applies whenever you can define a cluster or `family' of tests.

It's the same principle as rolling a 6-sided die, and needing to score a `6'. Think of the `6' as the `false positive' here.

In a single die role, the probability of getting a `6' is \(\frac{1}{6}\), and of course the equivalent probability of \emph{not} getting a `6' is \(1-\frac{1}{6}=\frac{5}{6}\).

\emph{But}, what if you get to roll the die 3 times? It's fairly easy to intuit that, even though the probability of getting a `6' on any single roll stays the same, the probability of getting a single `6' in 3 rolls is higher. In fact, we can calculate it.

To do so, we use the probability of \emph{not} getting a 6, as follows:

\emph{P}(no 6)=\((\frac{5}{6})^{3} = 0.579\)

Recalling the laws of probability then\ldots{}

\emph{P}(at least one 6) = 1 - \emph{P}(no 6) = 1 - .579 = .421

So, \emph{now} we have a 42\% probability of at least one 6 in 3 rolls, even though the probability of getting a 6 in any single roll is unchanged.

We can calculate the familywise error rate for any set of multiple comparisons in exactly the same way.

One of the key advantages of ANOVA is that it is a single test, and thus does not fall prey to the multiple comparisons problem. However, in the case of \emph{post-hoc} testing for the Ed Sheeran study, we are doing 3 pairwise comparisons (i.e.~3 tests) across the 3 groups, with a stated significance level of 0.05.

For 1 test, the false positive rate is \(1 - 0.95 = .05\)

But, for 3 tests, the false positive rate is \(1-0.95^{3}=0.14\)

We are `rolling the dice' multiple times.

In fact, below is a nice little calculator that demonstrates how the familywise error rate changes, based on the number of tests, and the chosen significance level. It was created by Dr Daniel Roelfs, during his time at the Norwegian Centre for Mental Disorders Research (NORMENT) in Oslo, and he kindly allowed me to use it here. Check out his website: \url{https://danielroelfs.com/about/}

What you could do is adjust the sliders to check the above calculations - what is the familywise error rate for 3 comparisons and a 0.05 significance level?

When you adjust the slides, it feels kind of scary right? There are many ways to deal with the problem, but they pretty much all amount to making some correction to the required significance level, making it more stringent, in order to reduce the false positives.

For example, in the Ed Sheeran post-hoc tests above, we used Tukey's test, which uses a correction for multiple comparisons. Another method dealt with below is the \emph{Bonferoni Correction}, which is generally the most well-known of them.

\section{The Bonferroni Correction: Rate of Change in Football Goals per Season}\label{the-bonferroni-correction-rate-of-change-in-football-goals-per-season}

Here, I will expand on the football goals rate-of-change example from Chapter \ref{statistics}, to incorporate corrections for the multiple comparisons problem. Again, I'm using data from \url{https://www.footballhistory.org/league/premier-league-statistics.html}

I'm building on the z-test table from the end of Chapter \ref{statistics}. But here, using the z-scores in the data file, I have calculated the p-value (2 tailed as we do not hypothesize a direction for the difference) for the z-scores for the difference between each season, year-on-year.

\begin{verbatim}
##     Season              Games         Goals             GPG       
##  Length:27          Min.   :380   Min.   : 931.0   Min.   :2.450  
##  Class :character   1st Qu.:380   1st Qu.: 981.5   1st Qu.:2.583  
##  Mode  :character   Median :380   Median :1018.0   Median :2.679  
##                     Mean   :380   Mean   :1013.9   Mean   :2.668  
##                     3rd Qu.:380   3rd Qu.:1056.5   3rd Qu.:2.780  
##                     Max.   :380   Max.   :1072.0   Max.   :2.821  
##                                                                   
##        SE          Lower95CI        Upper95CI          Change       
##  Min.   :30.51   Min.   : 871.2   Min.   : 990.8   Min.   :-77.000  
##  1st Qu.:31.33   1st Qu.: 920.1   1st Qu.:1042.9   1st Qu.:-35.500  
##  Median :31.91   Median : 955.5   Median :1080.5   Median : -2.000  
##  Mean   :31.84   Mean   : 951.5   Mean   :1076.3   Mean   :  3.192  
##  3rd Qu.:32.50   3rd Qu.: 992.8   3rd Qu.:1120.2   3rd Qu.: 44.750  
##  Max.   :32.74   Max.   :1007.8   Max.   :1136.2   Max.   :111.000  
##                                                    NA's   :1        
##        Z                negged               p2         
##  Min.   :-1.71027   Min.   :-2.48514   Min.   :0.01295  
##  1st Qu.:-0.79795   1st Qu.:-1.30711   1st Qu.:0.19236  
##  Median :-0.04369   Median :-0.83063   Median :0.40618  
##  Mean   : 0.07032   Mean   :-0.88179   Mean   :0.46986  
##  3rd Qu.: 0.97794   3rd Qu.:-0.24627   3rd Qu.:0.80549  
##  Max.   : 2.48514   Max.   :-0.02236   Max.   :0.98216  
##  NA's   :1          NA's   :1          NA's   :1
\end{verbatim}

\begin{verbatim}
## # A tibble: 6 x 11
##   Season  Games Goals   GPG    SE Lower95CI Upper95CI Change      Z negged
##   <chr>   <dbl> <dbl> <dbl> <dbl>     <dbl>     <dbl>  <dbl>  <dbl>  <dbl>
## 1 1995-96   380   988  2.6   31.4      926.     1050.     NA NA     NA    
## 2 1996-97   380   970  2.55  31.1      909.     1031.    -18 -0.407 -0.407
## 3 1997-98   380  1019  2.68  31.9      956.     1082.     49  1.10  -1.10 
## 4 1998-99   380   959  2.52  31.0      898.     1020.    -60 -1.35  -1.35 
## 5 1999-00   380  1060  2.79  32.6      996.     1124.    101  2.25  -2.25 
## 6 2000-01   380   992  2.61  31.5      930.     1054.    -68 -1.50  -1.50 
## # i 1 more variable: p2 <dbl>
\end{verbatim}

Here, we can plot the p-values (2-tailed), and again we see that two seasons seem to have significant differences. In other words, the p-values are less than 0.05 for the test as to whether the number of goals scored differs from the season before

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-163-1.pdf}}

We can see that the 1999-2000 season, and the 2009-10 seasons have p values less than 0.05

The question is \textbf{are we suffering from the multiple comparisons problem}? Should we correct for it?

It's hard to say actually. Of course, we are indeed running multiple tests, 26 in fact. So, the chance of a false positive is high. The Bonferroni correction would immediately reduce the false positive chances, but at what cost?

Let's see how this would work. In order to calculate a Bonferroni correction, you can either adjust the p-value directly that you calculate for each test, or instead simply adjust the `cutoff' value for p, known as the \emph{critical p}, to lower it from 0.05 and make the significance test `harder' to pass. The formula to adjust the cutoff value is simply:

\(\alpha_b = (\frac{\alpha}{n})\)

Where

\(\alpha_b\) = Bonferroni-adjusted critical p value

\(\alpha\) = original critical p value (here this is 0.05)

\emph{n} = number of comparisons (here this is 26)

So, the formula gives us a new Bonferroni-adjusted critical p value of 0.0019

Let's see what happens with this new critical p value:

\pandocbounded{\includegraphics[keepaspectratio]{LFD_files/figure-latex/unnamed-chunk-164-1.pdf}}

We can see that none of our tests now rejects the null. The Bonferroni correction is known as a highly conservative test. That is, it is based on the idea that the \emph{null hypothesis is true} in each case in the population. We can thus consider it as the most stringent and conservative way to correct for the chance of false positives when doing multiple comparisons.

But, as I suggested above, that might not always be the best idea. Indeed, if you want to totally avoid any chance of a false positive, why not simply make the required alpha 0? Then, you would never get a false positive. Of course, you would never detect a \textbf{true positive} either.

What if it is the alternative hypothesis (that is, the H of an effect existing) that is true in all cases? In such cases, there can of course be \emph{no false positives}. Therefore, in such a situation you would be \emph{increasing the chances of a false negative} by reducing the chances of a false positive. So, what are the potential costs of each of these mistakes?

For example, Thomas Perneger's 1998 paper in the BMJ is scathing about the Bonferroni adjustment. Take a look at \url{https://www.bmj.com/content/316/7139/1236.full}

Mind you, I am not saying that's the final word, just that there are multiple perspectives on the issues!

It's never as simple as it seems when making statistical decisions, is it?

\section{Statistical Power: Brief Demonstration}\label{statistical-power-brief-demonstration}

Different types of analysis and research design require different types of power calculation, so it is hard to give a uniform example. But, for simplicity's sake, let's calculate the required sample size for the Ed Sheeran study we conducted earlier.

Remember, really, we should have done this \textbf{before collecting data}.

To calculate power, all we need the parameters of the experiment and analysis design. As such, it is easily possible to do this before collecting data, and to design your studies around it. Really, we should do this a lot more in business and management - it's routine in fields like medicine.

So, we had 3 groups, and used ANOVA

Let's set a significance of 0.05, a required power of 0.8, and assume the effect size is moderate (say 0.25)

\begin{verbatim}
## 
##      Balanced one-way analysis of variance power calculation 
## 
##               k = 3
##               n = 52.3966
##               f = 0.25
##       sig.level = 0.05
##           power = 0.8
## 
## NOTE: n is number in each group
\end{verbatim}

So, we really wanted to have around 50 in each group to have an 80\% chance of detecting a moderate effect presuming the null was true.

You can see that my study (with only 15 in each group) was rather underpowered. However, if I had increased the effect size in the calculation to 0.5 (close to what the experiment suggested) this would have given me a result for n closer to what I actually used. However, you'd have to be VERY confident in the size of your likely effect to actually do that I think.

When creating this book, I have used data from numerous publicly-available sources. I have also sometimes used code from publicly-available repositories and websites.

All sources are cited at the place they are used, within each chapter, rather than being compiled into a single reference list here.

Further, a number of open-access academic papers and other reports are cited or referred to in Chapters.

Weblinks are provided for all sources mentioned above where possible. However, any direct queries can be emailed to me, in case I have missed something, or perhaps a URL no longer works.

\bibliography{book.bib,packages.bib}

\end{document}
