<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 The Normal Distribution | WBS MRes: Learning From Data</title>
  <meta name="description" content="This book contains the examples and notes for the WBS MRes Learning From Data Course." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 The Normal Distribution | WBS MRes: Learning From Data" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This book contains the examples and notes for the WBS MRes Learning From Data Course." />
  <meta name="github-repo" content="profnicklee/MRes_LFD_Book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 The Normal Distribution | WBS MRes: Learning From Data" />
  
  <meta name="twitter:description" content="This book contains the examples and notes for the WBS MRes Learning From Data Course." />
  

<meta name="author" content="Professor Nick Lee" />


<meta name="date" content="2026-09-29" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>
<link rel="next" href="causation.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">WBS MRes: Learning From Data</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction and Orientation</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#how-this-book-works"><i class="fa fa-check"></i><b>1.1</b> How this book works</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#what-this-book-is-for"><i class="fa fa-check"></i><b>1.1.1</b> What this book is for</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#how-it-fits-with-the-lectures"><i class="fa fa-check"></i><b>1.1.2</b> How it fits with the lectures</a></li>
<li class="chapter" data-level="1.1.3" data-path="index.html"><a href="index.html#how-the-chapters-work"><i class="fa fa-check"></i><b>1.1.3</b> How the chapters work</a></li>
<li class="chapter" data-level="1.1.4" data-path="index.html"><a href="index.html#a-note-on-the-numbers"><i class="fa fa-check"></i><b>1.1.4</b> A note on the numbers</a></li>
<li class="chapter" data-level="1.1.5" data-path="index.html"><a href="index.html#reading-the-literature"><i class="fa fa-check"></i><b>1.1.5</b> Reading the literature</a></li>
<li class="chapter" data-level="1.1.6" data-path="index.html"><a href="index.html#further-reading-and-references"><i class="fa fa-check"></i><b>1.1.6</b> Further reading and references</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Describing the World With Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#risk"><i class="fa fa-check"></i><b>2.1</b> When the numbers mislead: relative and absolute risk</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#summarizing-data-with-numbers"><i class="fa fa-check"></i><b>2.2</b> Summarizing Data with Numbers</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#box-plots"><i class="fa fa-check"></i><b>2.3</b> Box Plots</a></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#violin-plots-and-ridge-plots"><i class="fa fa-check"></i><b>2.4</b> Violin Plots and Ridge Plots</a></li>
<li class="chapter" data-level="2.5" data-path="intro.html"><a href="intro.html#transformations"><i class="fa fa-check"></i><b>2.5</b> Transformations</a></li>
<li class="chapter" data-level="2.6" data-path="intro.html"><a href="intro.html#intro-reading"><i class="fa fa-check"></i><b>2.6</b> Reading the literature</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="intro.html"><a href="intro.html#where-youll-meet-this"><i class="fa fa-check"></i><b>2.6.1</b> Where you’ll meet this</a></li>
<li class="chapter" data-level="2.6.2" data-path="intro.html"><a href="intro.html#the-connection-back"><i class="fa fa-check"></i><b>2.6.2</b> The connection back</a></li>
<li class="chapter" data-level="2.6.3" data-path="intro.html"><a href="intro.html#questions-worth-asking"><i class="fa fa-check"></i><b>2.6.3</b> Questions worth asking</a></li>
<li class="chapter" data-level="2.6.4" data-path="intro.html"><a href="intro.html#one-red-flag"><i class="fa fa-check"></i><b>2.6.4</b> One red flag</a></li>
<li class="chapter" data-level="2.6.5" data-path="intro.html"><a href="intro.html#if-you-want-to-read-more"><i class="fa fa-check"></i><b>2.6.5</b> If you want to read more</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="norm-dist.html"><a href="norm-dist.html"><i class="fa fa-check"></i><b>3</b> The Normal Distribution</a>
<ul>
<li class="chapter" data-level="3.1" data-path="norm-dist.html"><a href="norm-dist.html#a-simple-demonstration-of-the-normal-distribution"><i class="fa fa-check"></i><b>3.1</b> A Simple Demonstration of the Normal Distribution</a></li>
<li class="chapter" data-level="3.2" data-path="norm-dist.html"><a href="norm-dist.html#what-actually-is-a-normal-distribution"><i class="fa fa-check"></i><b>3.2</b> What Actually is a Normal Distribution?</a></li>
<li class="chapter" data-level="3.3" data-path="norm-dist.html"><a href="norm-dist.html#norm-dist-reading"><i class="fa fa-check"></i><b>3.3</b> Reading the literature</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="norm-dist.html"><a href="norm-dist.html#where-youll-meet-this-1"><i class="fa fa-check"></i><b>3.3.1</b> Where you’ll meet this</a></li>
<li class="chapter" data-level="3.3.2" data-path="norm-dist.html"><a href="norm-dist.html#the-connection-back-1"><i class="fa fa-check"></i><b>3.3.2</b> The connection back</a></li>
<li class="chapter" data-level="3.3.3" data-path="norm-dist.html"><a href="norm-dist.html#questions-worth-asking-1"><i class="fa fa-check"></i><b>3.3.3</b> Questions worth asking</a></li>
<li class="chapter" data-level="3.3.4" data-path="norm-dist.html"><a href="norm-dist.html#one-red-flag-1"><i class="fa fa-check"></i><b>3.3.4</b> One red flag</a></li>
<li class="chapter" data-level="3.3.5" data-path="norm-dist.html"><a href="norm-dist.html#if-you-want-to-read-more-1"><i class="fa fa-check"></i><b>3.3.5</b> If you want to read more</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="causation.html"><a href="causation.html"><i class="fa fa-check"></i><b>4</b> Causation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="causation.html"><a href="causation.html#confounding"><i class="fa fa-check"></i><b>4.1</b> Confounding</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="causation.html"><a href="causation.html#the-cornfield-test"><i class="fa fa-check"></i><b>4.1.1</b> The Cornfield Test</a></li>
<li class="chapter" data-level="4.1.2" data-path="causation.html"><a href="causation.html#confounding-demo"><i class="fa fa-check"></i><b>4.1.2</b> The Everyday Version</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="causation.html"><a href="causation.html#selection-bias"><i class="fa fa-check"></i><b>4.2</b> Selection Bias</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="causation.html"><a href="causation.html#all-the-data-isnt-all-the-data"><i class="fa fa-check"></i><b>4.2.1</b> All the Data Isn’t All the Data</a></li>
<li class="chapter" data-level="4.2.2" data-path="causation.html"><a href="causation.html#manufacturing-a-relationship-from-nothing"><i class="fa fa-check"></i><b>4.2.2</b> Manufacturing a Relationship from Nothing</a></li>
<li class="chapter" data-level="4.2.3" data-path="causation.html"><a href="causation.html#selection-feels-different"><i class="fa fa-check"></i><b>4.2.3</b> Why selection feels different</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="causation.html"><a href="causation.html#endogeneity"><i class="fa fa-check"></i><b>4.3</b> Endogeneity</a></li>
<li class="chapter" data-level="4.4" data-path="causation.html"><a href="causation.html#the-power-of-randomisation"><i class="fa fa-check"></i><b>4.4</b> The Power of Randomisation</a></li>
<li class="chapter" data-level="4.5" data-path="causation.html"><a href="causation.html#causation-reading"><i class="fa fa-check"></i><b>4.5</b> Reading the literature</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="causation.html"><a href="causation.html#where-youll-meet-this-2"><i class="fa fa-check"></i><b>4.5.1</b> Where you’ll meet this</a></li>
<li class="chapter" data-level="4.5.2" data-path="causation.html"><a href="causation.html#the-connection-back-2"><i class="fa fa-check"></i><b>4.5.2</b> The connection back</a></li>
<li class="chapter" data-level="4.5.3" data-path="causation.html"><a href="causation.html#questions-worth-asking-2"><i class="fa fa-check"></i><b>4.5.3</b> Questions worth asking</a></li>
<li class="chapter" data-level="4.5.4" data-path="causation.html"><a href="causation.html#one-red-flag-2"><i class="fa fa-check"></i><b>4.5.4</b> One red flag</a></li>
<li class="chapter" data-level="4.5.5" data-path="causation.html"><a href="causation.html#if-you-want-to-read-more-2"><i class="fa fa-check"></i><b>4.5.5</b> If you want to read more</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="assoc-rel.html"><a href="assoc-rel.html"><i class="fa fa-check"></i><b>5</b> Associations and Relationships</a>
<ul>
<li class="chapter" data-level="5.1" data-path="assoc-rel.html"><a href="assoc-rel.html#correlations-and-associations"><i class="fa fa-check"></i><b>5.1</b> Correlations and Associations</a></li>
<li class="chapter" data-level="5.2" data-path="assoc-rel.html"><a href="assoc-rel.html#introducing-nonlinear-associations"><i class="fa fa-check"></i><b>5.2</b> Introducing Nonlinear Associations</a></li>
<li class="chapter" data-level="5.3" data-path="assoc-rel.html"><a href="assoc-rel.html#regression"><i class="fa fa-check"></i><b>5.3</b> Regression</a></li>
<li class="chapter" data-level="5.4" data-path="assoc-rel.html"><a href="assoc-rel.html#multiple-regression"><i class="fa fa-check"></i><b>5.4</b> Multiple Regression</a></li>
<li class="chapter" data-level="5.5" data-path="assoc-rel.html"><a href="assoc-rel.html#visualizing-multiple-regression"><i class="fa fa-check"></i><b>5.5</b> Visualizing Multiple Regression</a></li>
<li class="chapter" data-level="5.6" data-path="assoc-rel.html"><a href="assoc-rel.html#assoc-rel-reading"><i class="fa fa-check"></i><b>5.6</b> Reading the literature</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="assoc-rel.html"><a href="assoc-rel.html#where-youll-meet-this-3"><i class="fa fa-check"></i><b>5.6.1</b> Where you’ll meet this</a></li>
<li class="chapter" data-level="5.6.2" data-path="assoc-rel.html"><a href="assoc-rel.html#the-connection-back-3"><i class="fa fa-check"></i><b>5.6.2</b> The connection back</a></li>
<li class="chapter" data-level="5.6.3" data-path="assoc-rel.html"><a href="assoc-rel.html#questions-worth-asking-3"><i class="fa fa-check"></i><b>5.6.3</b> Questions worth asking</a></li>
<li class="chapter" data-level="5.6.4" data-path="assoc-rel.html"><a href="assoc-rel.html#one-red-flag-3"><i class="fa fa-check"></i><b>5.6.4</b> One red flag</a></li>
<li class="chapter" data-level="5.6.5" data-path="assoc-rel.html"><a href="assoc-rel.html#if-you-want-to-read-more-3"><i class="fa fa-check"></i><b>5.6.5</b> If you want to read more</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="uncertainty.html"><a href="uncertainty.html"><i class="fa fa-check"></i><b>6</b> Beginning to Understand Uncertainty</a>
<ul>
<li class="chapter" data-level="6.1" data-path="uncertainty.html"><a href="uncertainty.html#demonstration-sampling-from-a-known-population"><i class="fa fa-check"></i><b>6.1</b> Demonstration: Sampling from a ‘Known’ Population</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="bootstrap.html"><a href="bootstrap.html"><i class="fa fa-check"></i><b>7</b> Introduction to Bootstrapping</a>
<ul>
<li class="chapter" data-level="7.1" data-path="bootstrap.html"><a href="bootstrap.html#bootstrapping-in-the-context-of-previous-examples"><i class="fa fa-check"></i><b>7.1</b> Bootstrapping in the Context of Previous Examples</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="bootstrap.html"><a href="bootstrap.html#bootstrapping-the-original-sample"><i class="fa fa-check"></i><b>7.1.1</b> Bootstrapping the Original Sample</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="bootstrap.html"><a href="bootstrap.html#bootstrapping-other-stuff"><i class="fa fa-check"></i><b>7.2</b> Bootstrapping Other Stuff…</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="bootstrap.html"><a href="bootstrap.html#correlations"><i class="fa fa-check"></i><b>7.2.1</b> Correlations</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="bootstrap.html"><a href="bootstrap.html#bootstrap-reading"><i class="fa fa-check"></i><b>7.3</b> Reading the literature</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="bootstrap.html"><a href="bootstrap.html#where-youll-meet-this-4"><i class="fa fa-check"></i><b>7.3.1</b> Where you’ll meet this</a></li>
<li class="chapter" data-level="7.3.2" data-path="bootstrap.html"><a href="bootstrap.html#the-connection-back-4"><i class="fa fa-check"></i><b>7.3.2</b> The connection back</a></li>
<li class="chapter" data-level="7.3.3" data-path="bootstrap.html"><a href="bootstrap.html#questions-worth-asking-4"><i class="fa fa-check"></i><b>7.3.3</b> Questions worth asking</a></li>
<li class="chapter" data-level="7.3.4" data-path="bootstrap.html"><a href="bootstrap.html#one-red-flag-4"><i class="fa fa-check"></i><b>7.3.4</b> One red flag</a></li>
<li class="chapter" data-level="7.3.5" data-path="bootstrap.html"><a href="bootstrap.html#if-you-want-to-read-more-4"><i class="fa fa-check"></i><b>7.3.5</b> If you want to read more</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="t-test.html"><a href="t-test.html"><i class="fa fa-check"></i><b>8</b> T-Tests for Means</a>
<ul>
<li class="chapter" data-level="8.1" data-path="t-test.html"><a href="t-test.html#the-christmas-music-study"><i class="fa fa-check"></i><b>8.1</b> The Christmas Music Study</a></li>
<li class="chapter" data-level="8.2" data-path="t-test.html"><a href="t-test.html#independent-samples-t-test"><i class="fa fa-check"></i><b>8.2</b> Independent-Samples T-Test</a></li>
<li class="chapter" data-level="8.3" data-path="t-test.html"><a href="t-test.html#paired-sample-t-test"><i class="fa fa-check"></i><b>8.3</b> Paired-Sample T-test</a></li>
<li class="chapter" data-level="8.4" data-path="t-test.html"><a href="t-test.html#t-test-reading"><i class="fa fa-check"></i><b>8.4</b> Reading the literature</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="t-test.html"><a href="t-test.html#where-youll-meet-this-5"><i class="fa fa-check"></i><b>8.4.1</b> Where you’ll meet this</a></li>
<li class="chapter" data-level="8.4.2" data-path="t-test.html"><a href="t-test.html#the-connection-back-5"><i class="fa fa-check"></i><b>8.4.2</b> The connection back</a></li>
<li class="chapter" data-level="8.4.3" data-path="t-test.html"><a href="t-test.html#questions-worth-asking-5"><i class="fa fa-check"></i><b>8.4.3</b> Questions worth asking</a></li>
<li class="chapter" data-level="8.4.4" data-path="t-test.html"><a href="t-test.html#one-red-flag-5"><i class="fa fa-check"></i><b>8.4.4</b> One red flag</a></li>
<li class="chapter" data-level="8.4.5" data-path="t-test.html"><a href="t-test.html#if-you-want-to-read-more-5"><i class="fa fa-check"></i><b>8.4.5</b> If you want to read more</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>9</b> Introduction to Probability</a>
<ul>
<li class="chapter" data-level="9.1" data-path="probability.html"><a href="probability.html#simulating-coin-flips"><i class="fa fa-check"></i><b>9.1</b> Simulating Coin Flips</a></li>
<li class="chapter" data-level="9.2" data-path="probability.html"><a href="probability.html#premier-league-goals-and-the-poisson-distribution"><i class="fa fa-check"></i><b>9.2</b> Premier League Goals and the Poisson Distribution</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="probability.html"><a href="probability.html#update"><i class="fa fa-check"></i><b>9.2.1</b> 2023 Update</a></li>
<li class="chapter" data-level="9.2.2" data-path="probability.html"><a href="probability.html#update-1"><i class="fa fa-check"></i><b>9.2.2</b> 2024 Update</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="statistics.html"><a href="statistics.html"><i class="fa fa-check"></i><b>10</b> Introduction to Statistics</a>
<ul>
<li class="chapter" data-level="10.1" data-path="statistics.html"><a href="statistics.html#the-distribution-of-sample-means-and-the-central-limit-theorem"><i class="fa fa-check"></i><b>10.1</b> The Distribution of Sample Means, and the Central Limit Theorem</a></li>
<li class="chapter" data-level="10.2" data-path="statistics.html"><a href="statistics.html#conf"><i class="fa fa-check"></i><b>10.2</b> Demonstrating Confidence Intervals</a></li>
<li class="chapter" data-level="10.3" data-path="statistics.html"><a href="statistics.html#rate-of-change-in-football-goals-per-season"><i class="fa fa-check"></i><b>10.3</b> Rate of Change in Football Goals per Season</a></li>
<li class="chapter" data-level="10.4" data-path="statistics.html"><a href="statistics.html#statistics-reading"><i class="fa fa-check"></i><b>10.4</b> Reading the literature</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="statistics.html"><a href="statistics.html#where-youll-meet-this-6"><i class="fa fa-check"></i><b>10.4.1</b> Where you’ll meet this</a></li>
<li class="chapter" data-level="10.4.2" data-path="statistics.html"><a href="statistics.html#the-connection-back-6"><i class="fa fa-check"></i><b>10.4.2</b> The connection back</a></li>
<li class="chapter" data-level="10.4.3" data-path="statistics.html"><a href="statistics.html#questions-worth-asking-6"><i class="fa fa-check"></i><b>10.4.3</b> Questions worth asking</a></li>
<li class="chapter" data-level="10.4.4" data-path="statistics.html"><a href="statistics.html#one-red-flag-6"><i class="fa fa-check"></i><b>10.4.4</b> One red flag</a></li>
<li class="chapter" data-level="10.4.5" data-path="statistics.html"><a href="statistics.html#if-you-want-to-read-more-6"><i class="fa fa-check"></i><b>10.4.5</b> If you want to read more</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="H-testing.html"><a href="H-testing.html"><i class="fa fa-check"></i><b>11</b> Classical Statistical Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="11.1" data-path="H-testing.html"><a href="H-testing.html#salary-ztest"><i class="fa fa-check"></i><b>11.1</b> Testing a Real Hypothesis: Are WBS PhD Salaries Different?</a></li>
<li class="chapter" data-level="11.2" data-path="H-testing.html"><a href="H-testing.html#premier-league-goals-and-the-poisson-distribution-1"><i class="fa fa-check"></i><b>11.2</b> Premier League Goals and the Poisson Distribution</a></li>
<li class="chapter" data-level="11.3" data-path="H-testing.html"><a href="H-testing.html#correlation-significance-tests"><i class="fa fa-check"></i><b>11.3</b> Correlation Significance Tests</a></li>
<li class="chapter" data-level="11.4" data-path="H-testing.html"><a href="H-testing.html#regression-significance-tests"><i class="fa fa-check"></i><b>11.4</b> Regression Significance Tests</a></li>
<li class="chapter" data-level="11.5" data-path="H-testing.html"><a href="H-testing.html#H-testing-reading"><i class="fa fa-check"></i><b>11.5</b> Reading the literature</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="H-testing.html"><a href="H-testing.html#where-youll-meet-this-7"><i class="fa fa-check"></i><b>11.5.1</b> Where you’ll meet this</a></li>
<li class="chapter" data-level="11.5.2" data-path="H-testing.html"><a href="H-testing.html#the-connection-back-7"><i class="fa fa-check"></i><b>11.5.2</b> The connection back</a></li>
<li class="chapter" data-level="11.5.3" data-path="H-testing.html"><a href="H-testing.html#questions-worth-asking-7"><i class="fa fa-check"></i><b>11.5.3</b> Questions worth asking</a></li>
<li class="chapter" data-level="11.5.4" data-path="H-testing.html"><a href="H-testing.html#one-red-flag-7"><i class="fa fa-check"></i><b>11.5.4</b> One red flag</a></li>
<li class="chapter" data-level="11.5.5" data-path="H-testing.html"><a href="H-testing.html#if-you-want-to-read-more-7"><i class="fa fa-check"></i><b>11.5.5</b> If you want to read more</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ANOVA.html"><a href="ANOVA.html"><i class="fa fa-check"></i><b>12</b> ANOVA</a>
<ul>
<li class="chapter" data-level="12.1" data-path="ANOVA.html"><a href="ANOVA.html#post-hoc-testing"><i class="fa fa-check"></i><b>12.1</b> Post-Hoc Testing</a></li>
<li class="chapter" data-level="12.2" data-path="ANOVA.html"><a href="ANOVA.html#ANOVA-reading"><i class="fa fa-check"></i><b>12.2</b> Reading the literature</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="ANOVA.html"><a href="ANOVA.html#where-youll-meet-this-8"><i class="fa fa-check"></i><b>12.2.1</b> Where you’ll meet this</a></li>
<li class="chapter" data-level="12.2.2" data-path="ANOVA.html"><a href="ANOVA.html#the-connection-back-8"><i class="fa fa-check"></i><b>12.2.2</b> The connection back</a></li>
<li class="chapter" data-level="12.2.3" data-path="ANOVA.html"><a href="ANOVA.html#questions-worth-asking-8"><i class="fa fa-check"></i><b>12.2.3</b> Questions worth asking</a></li>
<li class="chapter" data-level="12.2.4" data-path="ANOVA.html"><a href="ANOVA.html#one-red-flag-8"><i class="fa fa-check"></i><b>12.2.4</b> One red flag</a></li>
<li class="chapter" data-level="12.2.5" data-path="ANOVA.html"><a href="ANOVA.html#if-you-want-to-read-more-8"><i class="fa fa-check"></i><b>12.2.5</b> If you want to read more</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="Issues.html"><a href="Issues.html"><i class="fa fa-check"></i><b>13</b> Issues with Significance Testing</a>
<ul>
<li class="chapter" data-level="13.1" data-path="Issues.html"><a href="Issues.html#more-on-the-multiple-comparisons-problem"><i class="fa fa-check"></i><b>13.1</b> More on the Multiple Comparisons Problem</a></li>
<li class="chapter" data-level="13.2" data-path="Issues.html"><a href="Issues.html#the-bonferroni-correction-rate-of-change-in-football-goals-per-season"><i class="fa fa-check"></i><b>13.2</b> The Bonferroni Correction: Rate of Change in Football Goals per Season</a></li>
<li class="chapter" data-level="13.3" data-path="Issues.html"><a href="Issues.html#statistical-power-brief-demonstration"><i class="fa fa-check"></i><b>13.3</b> Statistical Power: Brief Demonstration</a></li>
<li class="chapter" data-level="13.4" data-path="Issues.html"><a href="Issues.html#p-hacking-sim"><i class="fa fa-check"></i><b>13.4</b> How to find an effect that isn’t there</a></li>
<li class="chapter" data-level="13.5" data-path="Issues.html"><a href="Issues.html#power-pose"><i class="fa fa-check"></i><b>13.5</b> What happens next: the power pose story</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="Issues.html"><a href="Issues.html#the-finding"><i class="fa fa-check"></i><b>13.5.1</b> The finding</a></li>
<li class="chapter" data-level="13.5.2" data-path="Issues.html"><a href="Issues.html#why-it-was-always-going-to-be-checked"><i class="fa fa-check"></i><b>13.5.2</b> Why it was always going to be checked</a></li>
<li class="chapter" data-level="13.5.3" data-path="Issues.html"><a href="Issues.html#what-happened-next"><i class="fa fa-check"></i><b>13.5.3</b> What happened next</a></li>
<li class="chapter" data-level="13.5.4" data-path="Issues.html"><a href="Issues.html#why-i-tell-this-story-differently-now"><i class="fa fa-check"></i><b>13.5.4</b> Why I tell this story differently now</a></li>
<li class="chapter" data-level="13.5.5" data-path="Issues.html"><a href="Issues.html#what-this-means-when-you-read"><i class="fa fa-check"></i><b>13.5.5</b> What this means when you read</a></li>
<li class="chapter" data-level="13.5.6" data-path="Issues.html"><a href="Issues.html#the-forks-nobody-sees"><i class="fa fa-check"></i><b>13.5.6</b> The forks nobody sees</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="Issues.html"><a href="Issues.html#issues-reading"><i class="fa fa-check"></i><b>13.6</b> Reading the literature</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="Issues.html"><a href="Issues.html#where-youll-meet-this-9"><i class="fa fa-check"></i><b>13.6.1</b> Where you’ll meet this</a></li>
<li class="chapter" data-level="13.6.2" data-path="Issues.html"><a href="Issues.html#the-connection-back-9"><i class="fa fa-check"></i><b>13.6.2</b> The connection back</a></li>
<li class="chapter" data-level="13.6.3" data-path="Issues.html"><a href="Issues.html#questions-worth-asking-9"><i class="fa fa-check"></i><b>13.6.3</b> Questions worth asking</a></li>
<li class="chapter" data-level="13.6.4" data-path="Issues.html"><a href="Issues.html#one-red-flag-9"><i class="fa fa-check"></i><b>13.6.4</b> One red flag</a></li>
<li class="chapter" data-level="13.6.5" data-path="Issues.html"><a href="Issues.html#if-you-want-to-read-more-9"><i class="fa fa-check"></i><b>13.6.5</b> If you want to read more</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="reader-guide.html"><a href="reader-guide.html"><i class="fa fa-check"></i><b>A</b> A Checklist for Reading Quantitative Papers</a>
<ul>
<li class="chapter" data-level="A.1" data-path="reader-guide.html"><a href="reader-guide.html#design-and-sample"><i class="fa fa-check"></i><b>A.1</b> Design and sample</a></li>
<li class="chapter" data-level="A.2" data-path="reader-guide.html"><a href="reader-guide.html#measures"><i class="fa fa-check"></i><b>A.2</b> Measures</a></li>
<li class="chapter" data-level="A.3" data-path="reader-guide.html"><a href="reader-guide.html#descriptives-and-correlations"><i class="fa fa-check"></i><b>A.3</b> Descriptives and correlations</a></li>
<li class="chapter" data-level="A.4" data-path="reader-guide.html"><a href="reader-guide.html#main-results"><i class="fa fa-check"></i><b>A.4</b> Main results</a></li>
<li class="chapter" data-level="A.5" data-path="reader-guide.html"><a href="reader-guide.html#robustness"><i class="fa fa-check"></i><b>A.5</b> Robustness</a></li>
<li class="chapter" data-level="A.6" data-path="reader-guide.html"><a href="reader-guide.html#discussion-and-claims"><i class="fa fa-check"></i><b>A.6</b> Discussion and claims</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">WBS MRes: Learning From Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="norm-dist" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> The Normal Distribution<a href="norm-dist.html#norm-dist" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This chapter supplements the content in Lecture 3.</p>
<div id="a-simple-demonstration-of-the-normal-distribution" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> A Simple Demonstration of the Normal Distribution<a href="norm-dist.html#a-simple-demonstration-of-the-normal-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>First, let’s consider the ‘empirical distribution’, which is the pattern your data set makes.</p>
<p>Let’s consider UK births in 2020 for our example, since they’re a subject close to my heart (my first child was born in 2020).</p>
<p>Looking online, one can pull down the distribution of UK birthweights in 2020, available from the UK ONS website, and which are reported in 500g ‘bins’.</p>
<p>Source: <a href="https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/livebirths/bulletins/birthsummarytablesenglandandwales/2020#births-data" class="uri">https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/livebirths/bulletins/birthsummarytablesenglandandwales/2020#births-data</a></p>
<p>We can use these numbers to create a chart</p>
<p>(please note, the code I use for the demonstrations in this lesson is mostly modified from David Spiegelhalter’s originals, available on his Github page, with some of my own bits and bobs and new data…)</p>
<p>Spiegelhalter’s Github can be found here: <a href="https://github.com/dspiegel29/ArtofStatistics" class="uri">https://github.com/dspiegel29/ArtofStatistics</a></p>
<p>The first thing I want to do is create a data set that accurately reflects the ONS distribution of UK birthweights in 2020. To do that, I use the following code, which in this instance I will display below, with annotations.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="norm-dist.html#cb6-1" tabindex="-1"></a>weights<span class="ot">=</span><span class="fu">c</span>(<span class="dv">1500</span>, <span class="dv">2000</span>, <span class="dv">2500</span>, <span class="dv">3000</span>, <span class="dv">3500</span>, <span class="dv">4000</span>, <span class="dv">4500</span>,<span class="dv">5000</span>,<span class="dv">5500</span>) <span class="co">#modified</span></span>
<span id="cb6-2"><a href="norm-dist.html#cb6-2" tabindex="-1"></a><span class="co">#categories from 2020 UK Data</span></span>
<span id="cb6-3"><a href="norm-dist.html#cb6-3" tabindex="-1"></a>mids<span class="ot">=</span>weights<span class="dv">-250</span> <span class="co"># Note the DS original is +250, but this does not work for UK</span></span>
<span id="cb6-4"><a href="norm-dist.html#cb6-4" tabindex="-1"></a><span class="co">#data as the numbered is the UPPER bound of the weight category in the ONS stats.</span></span>
<span id="cb6-5"><a href="norm-dist.html#cb6-5" tabindex="-1"></a><span class="co">#So the babies in the &#39;2000&#39; bin weigh 1500-1999, so the midpoint is 1750, not</span></span>
<span id="cb6-6"><a href="norm-dist.html#cb6-6" tabindex="-1"></a><span class="co">#2250</span></span>
<span id="cb6-7"><a href="norm-dist.html#cb6-7" tabindex="-1"></a>n<span class="ot">=</span><span class="fu">c</span>(<span class="dv">5015</span>, <span class="dv">7103</span>, <span class="dv">27554</span>, <span class="dv">99220</span>, <span class="dv">218442</span>, <span class="dv">179088</span>, <span class="dv">53530</span>,<span class="dv">6952</span>,<span class="dv">635</span>) <span class="co"># numbers in each</span></span>
<span id="cb6-8"><a href="norm-dist.html#cb6-8" tabindex="-1"></a><span class="co">#bin, UK2020</span></span>
<span id="cb6-9"><a href="norm-dist.html#cb6-9" tabindex="-1"></a>N<span class="ot">=</span><span class="fu">sum</span>(n)  <span class="co"># total number of babies</span></span>
<span id="cb6-10"><a href="norm-dist.html#cb6-10" tabindex="-1"></a>area<span class="ot">=</span>N<span class="sc">*</span><span class="dv">500</span>  <span class="co"># number * binwidth = total area of histogram</span></span>
<span id="cb6-11"><a href="norm-dist.html#cb6-11" tabindex="-1"></a></span>
<span id="cb6-12"><a href="norm-dist.html#cb6-12" tabindex="-1"></a><span class="co">#I think lbw should be sum of groups 1-3 not 1-2 as in the book code. Using 1-3</span></span>
<span id="cb6-13"><a href="norm-dist.html#cb6-13" tabindex="-1"></a><span class="co">#gives a result for the UK of 6.6% which tallies with the official stat given</span></span>
<span id="cb6-14"><a href="norm-dist.html#cb6-14" tabindex="-1"></a><span class="co">#that I remove the &#39;no recorded weight&#39; and &#39;implausible&#39; categories&#39;. I imagine</span></span>
<span id="cb6-15"><a href="norm-dist.html#cb6-15" tabindex="-1"></a><span class="co">#that the DS book data has categories which may be the lower bound not the upper</span></span>
<span id="cb6-16"><a href="norm-dist.html#cb6-16" tabindex="-1"></a><span class="co">#as in the UK data table.</span></span>
<span id="cb6-17"><a href="norm-dist.html#cb6-17" tabindex="-1"></a></span>
<span id="cb6-18"><a href="norm-dist.html#cb6-18" tabindex="-1"></a>lbw   <span class="ot">=</span> <span class="fu">sum</span>(n[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])   <span class="co"># number with low birth weight (less than 2500)</span></span>
<span id="cb6-19"><a href="norm-dist.html#cb6-19" tabindex="-1"></a>lbw.percent<span class="ot">=</span><span class="dv">100</span><span class="sc">*</span>lbw<span class="sc">/</span>N  <span class="co"># % low birth weight</span></span>
<span id="cb6-20"><a href="norm-dist.html#cb6-20" tabindex="-1"></a><span class="co"># 6.6% which tallies with Nuffield stat for 2020.</span></span></code></pre></div>
<p>Remember though, the above just sets up the numbers required to recreate the empirical distribution, it isn’t analysis itself.</p>
<p>Next, I want to summarize the distribution I just created and a few important numbers regarding Low Birthweight that we will need to use for our later discussion.</p>
<p>Displayed below are the total N for the distribution, the number of low birthweight (LBW) babies born, the percentage of LBW babies, the mean, the standard deviation, the skewness, and kurtosis.</p>
<pre><code>## [1] 597539</code></pre>
<pre><code>## [1] 39672</code></pre>
<pre><code>## [1] 6.639232</code></pre>
<pre><code>## [1] 3345.263</code></pre>
<pre><code>## [1] 577.7594</code></pre>
<pre><code>## [1] -0.4955778</code></pre>
<pre><code>## [1] 4.068451</code></pre>
<p>Two of those numbers need a word of explanation, because you’ll meet them in the descriptives of almost every quantitative paper. <em>Skewness</em> measures how lopsided a distribution is. A perfectly symmetrical distribution, like the normal, has a skewness of zero. Birthweights come out at -0.5. That’s negative, meaning the distribution has a longer tail on the left, the lighter side, than on the right. That makes sense: babies born early can be very much lighter than average, while babies much heavier than average are rare. <em>Kurtosis</em> is about the tails, meaning how much of the distribution sits a long way from the mean compared with a normal distribution. The normal distribution has a kurtosis of 3, and ours is 4.07, so birthweights have somewhat heavier tails than a normal distribution would. (Some software reports <em>excess</em> kurtosis instead, which subtracts the 3 so that a normal distribution scores zero, so always check which you’re looking at.) Neither number is dramatic, and as you’ll see in a moment, the normal distribution still does a respectable job of describing these data. But it isn’t a perfect description, and the skewness tells you which way it departs.</p>
<p>Next, I will calculate the estimated proportion of low birthweight babies using a normal distribution approximation, and see if it tallies OK with the figure that is taken from the distribution of 6.6%</p>
<pre><code>## [1] 7.173338</code></pre>
<p>I will also calculate the middle birthweight proportion as a sense check - should be very close to 50%!</p>
<pre><code>## [1] 49.98182</code></pre>
<p>For our reference, we will calculate the 25th, 50th, 75th percentiles</p>
<pre><code>## [1] 2955.57</code></pre>
<pre><code>## [1] 3345.263</code></pre>
<pre><code>## [1] 3734.956</code></pre>
<p>Next I want to calculate the birthweight percentile of Monty, my son.</p>
<pre><code>## [1] 0.8366843</code></pre>
<p>Now, at last, we can do some plots!</p>
<p>First let’s set up the histogram and overlay a normal distribution on to it.</p>
<p>The weight of Monty is overlaid as a red line. We can estimate if this is ‘unusual’ or not by how far away it is from the mean of the distribution.</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-33-1.png" alt="" width="672" /></p>
</div>
<div id="what-actually-is-a-normal-distribution" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> What Actually is a Normal Distribution?<a href="norm-dist.html#what-actually-is-a-normal-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Below, I will chart the normal distribution with Standard Deviations.</p>
<p>Mathematically, around 95% of the area under the chart is between -2 and +2 SDs, and 99.7% between -3 and +3 SDs</p>
<p>Now, another way to think about this is that the area under the normal curve represents 100% of the probability of a given value (here, weight) occuring. So, you could say that it is around 95% probable that any given birthweight (randomly sampled) will occur between -2 and +2 SDs of the mean.</p>
<p>We can calculate this easily, given that the mean is 3345.263, and the SD is 577.7594</p>
<p>So, it is 95% probable that a random baby born in the UK in 2020 will weigh between 2189.745 and 4500.781g</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-34-1.png" alt="" width="672" /></p>
<p>We can calculate how many SDs Monty’s weight was above the mean by calculating the z-score for his weight of 3912g.</p>
<p>To do so, let’s return to the slide deck and see the calculation.</p>
<p><strong><em>Move back to the slides…</em></strong></p>
<p>Next, we can overlay percentiles in 5% increments on the chart, which are also useful ways to describe a distribution like the Normal.</p>
<p>50th is of course the median, and the 25th and 75th percentilies are the quartiles.</p>
<p>Here, the same things we have previously discussed in relation to samples are applied to populations</p>
<p>We can also see that Monty lies on the 83rd percentile, that is 83% of babies born in 2020 weighed less. This tallies with what we were told at the time, and then things are monitored quite closely from that time on in terms of percentiles.</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-35-1.png" alt="" width="672" /></p>
<p>Moving to a discussion of low birthweight. It is medically defined as low if below 2500g. Nuffield reports that 6.6% of babies in 2020 were born at low birthweight, which is fairly good.</p>
<p>This tallies fairly well with the predicted proportion from the normal distribution of 7.2%</p>
<p>What we gain from the grey shaded area is the proportion of the population which is expected to be born at low birthweight, but also an indication of the probability that a randomly-chosen baby born in 2020 would be of low weight.</p>
<p>This concept can easily be transferred to other weights in this population (and by extension to other variables and populations distributed like this)</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-36-1.png" alt="" width="672" /></p>
</div>
<div id="norm-dist-reading" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Reading the literature<a href="norm-dist.html#norm-dist-reading" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Most quantitative papers include a table of descriptive statistics: a mean and a standard deviation for every variable, sometimes with minimums, maximums, medians or skewness. It usually sits alongside the correlations in Table 1, and it’s usually skipped. The normal distribution in this chapter is the benchmark that makes that table readable. A mean and a standard deviation summarise a normal distribution almost perfectly. The further a variable is from normal, the less those two numbers tell you, and the more carefully you need to read them.</p>
<div id="where-youll-meet-this-1" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Where you’ll meet this<a href="norm-dist.html#where-youll-meet-this-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Survey scales.</strong> Many management variables are averages of several Likert items, such as “strongly disagree” (1) to “strongly agree” (7). There’s a long-running argument about whether it’s legitimate to take means of these at all, since the gaps between the response options needn’t be equal. In practice, averages of several items usually behave well enough for the standard methods <span class="citation">(<a href="#ref-norman2010likert">Norman 2010</a>)</span>, but it’s worth reading the numbers in terms of the scale. A mean of 4 on a 1–7 scale could mean that everyone chose the neutral midpoint, or that half the sample strongly agreed and half strongly disagreed, and only the standard deviation will tell you which. Watch for means close to either end of the scale. A mean of 6.3 on a 1–7 scale, with a small standard deviation, means almost everyone gave nearly the same answer. There’s then very little variation for any other variable to explain, and correlations with that variable will be weaker than the underlying relationship because the range is so restricted.</p>
<p><strong>Skewed business variables.</strong> Plenty of the variables in management research are nothing like normal. Firm size, sales, executive pay, patents and citations are typically <em>right-skewed</em>: most firms are small, and a few are enormous. For variables like these the mean is dragged upwards by the largest cases and can be a poor guide to a typical firm. Where a paper reports both the mean and the median, compare them; a mean far above the median is the signature of right skew.</p>
<p><strong>Logged variables.</strong> Because of that skew, papers often analyse the logarithm of a variable, as you’ll see Chapter <a href="assoc-rel.html#assoc-rel">5</a> do with GDP. The log pulls in the long right tail, and it changes what a coefficient means. When the predictor is logged, its coefficient describes the effect of a <em>proportional</em> change: roughly, a 1% increase in X goes with a change of the coefficient divided by 100 in Y. When the outcome is logged too, the coefficient becomes an <em>elasticity</em>: a 1% increase in X goes with a change of roughly the coefficient, in per cent, in Y. So check the variable descriptions for “ln” or “log” before interpreting any coefficient. Also check what was done about zeros, which can’t be logged. Many papers add 1 to every value first, and with count variables full of zeros, that choice can matter.</p>
<p><strong>Normality checks.</strong> Papers sometimes report that variables were tested for normality and found wanting, or not. Two things are worth knowing. First, what ordinary regression actually assumes is roughly normal <em>errors</em> (residuals), not normally distributed variables. A skewed predictor isn’t a problem in itself. Second, in large samples formal tests of normality will flag departures far too small to matter. Skewness and kurtosis figures, or a plot, usually tell you more than a significance test does. Chapter <a href="causation.html#causation">4</a> shows one place where the shape of a distribution matters a great deal: some endogeneity corrections only work if the variable is clearly non-normal.</p>
</div>
<div id="the-connection-back-1" class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> The connection back<a href="norm-dist.html#the-connection-back-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The normal distribution in this chapter isn’t something real data have to follow. It’s a reference point. Birthweights sit close to it, which is why the mean, standard deviation and normal curve described them so well and predicted the low-birthweight proportion reasonably well. Much business data sits far from it. The descriptives table is where you find out which kind of variable you’re dealing with, and therefore how much to trust its mean and standard deviation.</p>
</div>
<div id="questions-worth-asking-1" class="section level3 hasAnchor" number="3.3.3">
<h3><span class="header-section-number">3.3.3</span> Questions worth asking<a href="norm-dist.html#questions-worth-asking-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><strong>Is the mean a sensible summary of this variable?</strong> Compare it with the median, the minimum and maximum, and the scale’s limits.</li>
<li><strong>Is there enough variation for the analysis to find anything?</strong> A scale where everyone answered much the same can’t correlate strongly with anything.</li>
<li><strong>Which variables were logged?</strong> How does that change what their coefficients mean?</li>
<li><strong>When normality is discussed, is it the right thing that’s being checked?</strong></li>
</ol>
</div>
<div id="one-red-flag-1" class="section level3 hasAnchor" number="3.3.4">
<h3><span class="header-section-number">3.3.4</span> One red flag<a href="norm-dist.html#one-red-flag-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Check the descriptives for a standard deviation that’s bigger than the mean, on a variable that can’t be negative, such as revenue, employees or pay. A mean of 450 and a standard deviation of 1,200 means the distribution is extremely right-skewed: a handful of very large cases are pulling both numbers upwards. If the paper then puts that variable into a regression untransformed, those few cases may be driving the results. That’s not necessarily wrong, but the paper should say so, and ideally show what happens without them.</p>
</div>
<div id="if-you-want-to-read-more-1" class="section level3 hasAnchor" number="3.3.5">
<h3><span class="header-section-number">3.3.5</span> If you want to read more<a href="norm-dist.html#if-you-want-to-read-more-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Geoff Norman’s “Likert scales, levels of measurement and the ‘laws’ of statistics” <span class="citation">(<a href="#ref-norman2010likert">Norman 2010</a>)</span> is a short, punchy defence of using ordinary statistical methods on survey data. It takes the arguments against head on, so you can judge for yourself. It’ll equip you for the next time a reviewer, or a supervisor, tells you that you can’t take the mean of a Likert scale.</p>
<p>A condensed version of these questions, combined with those from the other chapters and arranged in the order you’d meet them when reading a paper, is in Appendix <a href="reader-guide.html#reader-guide">A</a>.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-norman2010likert" class="csl-entry">
Norman, Geoff. 2010. <span>“Likert Scales, Levels of Measurement and the <span>‘Laws’</span> of Statistics.”</span> <em>Advances in Health Sciences Education</em> 15 (5): 625–32. <a href="https://doi.org/10.1007/s10459-010-9222-y">https://doi.org/10.1007/s10459-010-9222-y</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="causation.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/profnicklee/MRes_LFD_Book/edit/main/02-Distributions.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["LFD.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
