<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 The Normal Distribution | WBS MRes: Learning From Data</title>
  <meta name="description" content="This book contains the examples and notes for the WBS MrRes Learning from Data Course. It is based on the Bookdown Demo written by Hui. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 The Normal Distribution | WBS MRes: Learning From Data" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This book contains the examples and notes for the WBS MrRes Learning from Data Course. It is based on the Bookdown Demo written by Hui. The output format for this example is bookdown::gitbook." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 The Normal Distribution | WBS MRes: Learning From Data" />
  
  <meta name="twitter:description" content="This book contains the examples and notes for the WBS MrRes Learning from Data Course. It is based on the Bookdown Demo written by Hui. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Professor Nick Lee" />


<meta name="date" content="2024-09-27" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="assoc_rel.html"/>
<link rel="next" href="uncertainty.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">WBS DBA Quantitative Methods</li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction and Orientation</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Describing the World With Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#summarizing-data-with-numbers"><i class="fa fa-check"></i><b>2.1</b> Summarizing Data with Numbers</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#box-plots"><i class="fa fa-check"></i><b>2.2</b> Box Plots</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#violin-plots-and-ridge-plots"><i class="fa fa-check"></i><b>2.3</b> Violin Plots and Ridge Plots</a></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#transformations"><i class="fa fa-check"></i><b>2.4</b> Transformations</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="assoc_rel.html"><a href="assoc_rel.html"><i class="fa fa-check"></i><b>3</b> Associations and Relationships</a>
<ul>
<li class="chapter" data-level="3.1" data-path="assoc_rel.html"><a href="assoc_rel.html#correlations-and-associations"><i class="fa fa-check"></i><b>3.1</b> Correlations and Associations</a></li>
<li class="chapter" data-level="3.2" data-path="assoc_rel.html"><a href="assoc_rel.html#introducing-nonlinear-associations"><i class="fa fa-check"></i><b>3.2</b> Introducing Nonlinear Associations</a></li>
<li class="chapter" data-level="3.3" data-path="assoc_rel.html"><a href="assoc_rel.html#regression"><i class="fa fa-check"></i><b>3.3</b> Regression</a></li>
<li class="chapter" data-level="3.4" data-path="assoc_rel.html"><a href="assoc_rel.html#multiple-regression"><i class="fa fa-check"></i><b>3.4</b> Multiple Regression</a></li>
<li class="chapter" data-level="3.5" data-path="assoc_rel.html"><a href="assoc_rel.html#visualizing-multiple-regression"><i class="fa fa-check"></i><b>3.5</b> Visualizing Multiple Regression</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="norm_dist.html"><a href="norm_dist.html"><i class="fa fa-check"></i><b>4</b> The Normal Distribution</a>
<ul>
<li class="chapter" data-level="4.1" data-path="norm_dist.html"><a href="norm_dist.html#a-simple-demonstration-of-the-normal-distribution"><i class="fa fa-check"></i><b>4.1</b> A Simple Demonstration of the Normal Distribution</a></li>
<li class="chapter" data-level="4.2" data-path="norm_dist.html"><a href="norm_dist.html#what-actually-is-a-normal-distribution"><i class="fa fa-check"></i><b>4.2</b> What Actually is a Normal Distribution?</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="uncertainty.html"><a href="uncertainty.html"><i class="fa fa-check"></i><b>5</b> Beginning to Understand Uncertainty</a>
<ul>
<li class="chapter" data-level="5.1" data-path="uncertainty.html"><a href="uncertainty.html#demonstration-sampling-from-a-known-population"><i class="fa fa-check"></i><b>5.1</b> Demonstration: Sampling from a ‘Known’ Population</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="bootstrap.html"><a href="bootstrap.html"><i class="fa fa-check"></i><b>6</b> Introduction to Bootstrapping</a>
<ul>
<li class="chapter" data-level="6.1" data-path="bootstrap.html"><a href="bootstrap.html#bootstrapping-in-the-context-of-previous-examples"><i class="fa fa-check"></i><b>6.1</b> Bootstrapping in the Context of Previous Examples</a></li>
<li class="chapter" data-level="6.2" data-path="bootstrap.html"><a href="bootstrap.html#bootstrapping-other-stuff"><i class="fa fa-check"></i><b>6.2</b> Bootstrapping Other Stuff…</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="bootstrap.html"><a href="bootstrap.html#correlations"><i class="fa fa-check"></i><b>6.2.1</b> Correlations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="t-test.html"><a href="t-test.html"><i class="fa fa-check"></i><b>7</b> T-Tests for Means</a>
<ul>
<li class="chapter" data-level="7.1" data-path="t-test.html"><a href="t-test.html#independent-sample-t-tests"><i class="fa fa-check"></i><b>7.1</b> Independent Sample T-Tests</a></li>
<li class="chapter" data-level="7.2" data-path="t-test.html"><a href="t-test.html#paired-sample-t-tests"><i class="fa fa-check"></i><b>7.2</b> Paired-Sample T-tests</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>8</b> Introduction to Probability</a>
<ul>
<li class="chapter" data-level="8.1" data-path="probability.html"><a href="probability.html#simulating-coin-flips"><i class="fa fa-check"></i><b>8.1</b> Simulating Coin Flips</a></li>
<li class="chapter" data-level="8.2" data-path="probability.html"><a href="probability.html#premier-league-goals-and-the-poisson-distribution"><i class="fa fa-check"></i><b>8.2</b> Premier League Goals and the Poisson Distribution</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="probability.html"><a href="probability.html#update"><i class="fa fa-check"></i><b>8.2.1</b> 2023 Update</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="probability.html"><a href="probability.html#birth-weight-and-the-normal-distribution-brief-example"><i class="fa fa-check"></i><b>8.3</b> Birth Weight and the Normal Distribution: Brief Example</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="statistics.html"><a href="statistics.html"><i class="fa fa-check"></i><b>9</b> Introduction to Statistics</a>
<ul>
<li class="chapter" data-level="9.1" data-path="statistics.html"><a href="statistics.html#the-distribution-of-sample-means-and-the-central-limit-theorem"><i class="fa fa-check"></i><b>9.1</b> The Distribution of Sample Means, and the Central Limit Theorem</a></li>
<li class="chapter" data-level="9.2" data-path="statistics.html"><a href="statistics.html#conf"><i class="fa fa-check"></i><b>9.2</b> Demonstrating Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="H-testing.html"><a href="H-testing.html"><i class="fa fa-check"></i><b>10</b> Classical Statistical Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="10.1" data-path="H-testing.html"><a href="H-testing.html#correlation-significance-tests"><i class="fa fa-check"></i><b>10.1</b> Correlation Significance Tests</a></li>
<li class="chapter" data-level="10.2" data-path="H-testing.html"><a href="H-testing.html#regression-significance-tests"><i class="fa fa-check"></i><b>10.2</b> Regression Significance Tests</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ANOVA.html"><a href="ANOVA.html"><i class="fa fa-check"></i><b>11</b> ANOVA</a>
<ul>
<li class="chapter" data-level="11.1" data-path="ANOVA.html"><a href="ANOVA.html#post-hoc-testing"><i class="fa fa-check"></i><b>11.1</b> Post-Hoc Testing</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="Issues.html"><a href="Issues.html"><i class="fa fa-check"></i><b>12</b> Issues with Significance Testing</a>
<ul>
<li class="chapter" data-level="12.1" data-path="Issues.html"><a href="Issues.html#more-on-the-multiple-comparisons-problem"><i class="fa fa-check"></i><b>12.1</b> More on the Multiple Comparisons Problem</a></li>
<li class="chapter" data-level="12.2" data-path="Issues.html"><a href="Issues.html#the-bonferroni-correction-rate-of-change-in-football-goals-per-season"><i class="fa fa-check"></i><b>12.2</b> The Bonferroni Correction: Rate of Change in Football Goals per Season</a></li>
<li class="chapter" data-level="12.3" data-path="Issues.html"><a href="Issues.html#statistical-power-brief-demonstration"><i class="fa fa-check"></i><b>12.3</b> Statistical Power: Brief Demonstration</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">WBS MRes: Learning From Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="norm_dist" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> The Normal Distribution<a href="norm_dist.html#norm_dist" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This chapter supplements the content in Lecture 3.</p>
<div id="a-simple-demonstration-of-the-normal-distribution" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> A Simple Demonstration of the Normal Distribution<a href="norm_dist.html#a-simple-demonstration-of-the-normal-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>First, let’s consider the ‘empirical distribution’, which is the pattern your data set makes.</p>
<p>Let’s consider UK births in 2020 for our example, since they’re a subject close to my heart (my first child was born in 2020).</p>
<p>Looking online, one can pull down the distribution of UK birthweights in 2020, available from the UK ONS website, and which are reported in 500g ‘bins’.</p>
<p>Source: <a href="https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/livebirths/bulletins/birthsummarytablesenglandandwales/2020#births-data" class="uri">https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/livebirths/bulletins/birthsummarytablesenglandandwales/2020#births-data</a></p>
<p>We can use these numbers to create a chart</p>
<p>(please note, the code I use for the demonstrations in this lesson is mostly modified from David Spiegelhalter’s originals, available on his Github page, with some of my own bits and bobs and new data…)</p>
<p>Spiegelhalter’s Github can be found here: <a href="https://github.com/dspiegel29/ArtofStatistics" class="uri">https://github.com/dspiegel29/ArtofStatistics</a></p>
<p>The first thing I want to do is create a data set that accurately reflects the ONS distribution of UK birthweights in 2020. To do that, I use the following code, which in this instance I will display below, with annotations.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="norm_dist.html#cb1-1" tabindex="-1"></a>weights<span class="ot">=</span><span class="fu">c</span>(<span class="dv">1500</span>, <span class="dv">2000</span>, <span class="dv">2500</span>, <span class="dv">3000</span>, <span class="dv">3500</span>, <span class="dv">4000</span>, <span class="dv">4500</span>,<span class="dv">5000</span>,<span class="dv">5500</span>) <span class="co">#modified</span></span>
<span id="cb1-2"><a href="norm_dist.html#cb1-2" tabindex="-1"></a><span class="co">#categories from 2020 UK Data</span></span>
<span id="cb1-3"><a href="norm_dist.html#cb1-3" tabindex="-1"></a>mids<span class="ot">=</span>weights<span class="dv">-250</span> <span class="co"># Note the DS original is +250, but this does not work for UK</span></span>
<span id="cb1-4"><a href="norm_dist.html#cb1-4" tabindex="-1"></a><span class="co">#data as the numbered is the UPPER bound of the weight category in the ONS stats.</span></span>
<span id="cb1-5"><a href="norm_dist.html#cb1-5" tabindex="-1"></a><span class="co">#So the babies in the &#39;2000&#39; bin weigh 1500-1999, so the midpoint is 1750, not</span></span>
<span id="cb1-6"><a href="norm_dist.html#cb1-6" tabindex="-1"></a><span class="co">#2250</span></span>
<span id="cb1-7"><a href="norm_dist.html#cb1-7" tabindex="-1"></a>n<span class="ot">=</span><span class="fu">c</span>(<span class="dv">5015</span>, <span class="dv">7103</span>, <span class="dv">27554</span>, <span class="dv">99220</span>, <span class="dv">218442</span>, <span class="dv">179088</span>, <span class="dv">53530</span>,<span class="dv">6952</span>,<span class="dv">635</span>) <span class="co"># numbers in each</span></span>
<span id="cb1-8"><a href="norm_dist.html#cb1-8" tabindex="-1"></a><span class="co">#bin, UK2020</span></span>
<span id="cb1-9"><a href="norm_dist.html#cb1-9" tabindex="-1"></a>N<span class="ot">=</span><span class="fu">sum</span>(n)  <span class="co"># total number of babies</span></span>
<span id="cb1-10"><a href="norm_dist.html#cb1-10" tabindex="-1"></a>area<span class="ot">=</span>N<span class="sc">*</span><span class="dv">500</span>  <span class="co"># number * binwidth = total area of histogram</span></span>
<span id="cb1-11"><a href="norm_dist.html#cb1-11" tabindex="-1"></a></span>
<span id="cb1-12"><a href="norm_dist.html#cb1-12" tabindex="-1"></a><span class="co">#I think lbw should be sum of groups 1-3 not 1-2 as in the book code. Using 1-3</span></span>
<span id="cb1-13"><a href="norm_dist.html#cb1-13" tabindex="-1"></a><span class="co">#gives a result for the UK of 6.6% which tallies with the official stat given</span></span>
<span id="cb1-14"><a href="norm_dist.html#cb1-14" tabindex="-1"></a><span class="co">#that I remove the &#39;no recorded weight&#39; and &#39;implausible&#39; categories&#39;. I imagine</span></span>
<span id="cb1-15"><a href="norm_dist.html#cb1-15" tabindex="-1"></a><span class="co">#that the DS book data has categories which may be the lower bound not the upper</span></span>
<span id="cb1-16"><a href="norm_dist.html#cb1-16" tabindex="-1"></a><span class="co">#as in the UK data table.</span></span>
<span id="cb1-17"><a href="norm_dist.html#cb1-17" tabindex="-1"></a></span>
<span id="cb1-18"><a href="norm_dist.html#cb1-18" tabindex="-1"></a>lbw   <span class="ot">=</span> <span class="fu">sum</span>(n[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])   <span class="co"># number with low birth weight (less than 2500)</span></span>
<span id="cb1-19"><a href="norm_dist.html#cb1-19" tabindex="-1"></a>lbw.percent<span class="ot">=</span><span class="dv">100</span><span class="sc">*</span>lbw<span class="sc">/</span>N  <span class="co"># % low birth weight</span></span>
<span id="cb1-20"><a href="norm_dist.html#cb1-20" tabindex="-1"></a><span class="co"># 6.6% which tallies with Nuffield stat for 2020.</span></span></code></pre></div>
<p>Remember though, the above just sets up the numbers required to recreate the empirical distribution, it isn’t analysis itself.</p>
<p>Next, I want to summarize the distribution I just created and a few important numbers regarding Low Birthweight that we will need to use for our later discussion.</p>
<p>Displayed below are the total N for the distribution, the number of low birthweight (LBW) babies born, the percentage of LBW babies, the mean, the standard deviation, the skewness, and kurtosis.</p>
<pre><code>## [1] 597539</code></pre>
<pre><code>## [1] 39672</code></pre>
<pre><code>## [1] 6.639232</code></pre>
<pre><code>## [1] 3345.263</code></pre>
<pre><code>## [1] 577.7594</code></pre>
<pre><code>## [1] 0</code></pre>
<pre><code>## [1] 1.77</code></pre>
<p>Next, I will calculate the estimated proportion of low birthweight babies using a normal distribution approximation, and see if it tallies OK with the figure that is taken from the distribution of 6.6%</p>
<pre><code>## [1] 7.173338</code></pre>
<p>I will also calculate the middle birthweight proportion as a sense check - should be very close to 50%!</p>
<pre><code>## [1] 49.98182</code></pre>
<p>For our reference, we will calculate the 25th, 50th, 75th percentiles</p>
<pre><code>## [1] 2955.57</code></pre>
<pre><code>## [1] 3345.263</code></pre>
<pre><code>## [1] 3734.956</code></pre>
<p>Next I want to calculate the birthweight percentile of Monty, my son.</p>
<pre><code>## [1] 0.8366843</code></pre>
<p>Now, at last, we can do some plots!</p>
<p>First let’s set up the histogram and overlay a normal distribution on to it.</p>
<p>The weight of Monty is overlaid as a red line. We can estimate if this is ‘unusual’ or not by how far away it is from the mean of the distribution.</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
<div id="what-actually-is-a-normal-distribution" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> What Actually is a Normal Distribution?<a href="norm_dist.html#what-actually-is-a-normal-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Below, I will chart the normal distribution with Standard Deviations.</p>
<p>Mathematically, around 95% of the area under the chart is between -2 and +2 SDs, and 99.8% between -3 and +3 SDs</p>
<p>Now, another way to think about this is that the area under the normal curve represents 100% of the probability of a given value (here, weight) occuring. So, you could say that it is around 95% probable that any given birthweight (randomly sampled) will occur between -2 and +2 SDs of the mean.</p>
<p>We can calculate this easily, given that the mean is 3345.263, and the SD is 577.7594</p>
<p>So, it is 95% probable that a random baby born in the UK in 2020 will weigh between 2189.745 and 4500.781g</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>We can calculate how many SDs Monty’s weight was above the mean by calculating the z-score for his weight of 3912g.</p>
<p>To do so, let’s return to the slide deck and see the calculation.</p>
<p><strong><em>Move back to the slides…</em></strong></p>
<p>Next, we can overlay percentiles in 5% increments on the chart, which are also useful ways to describe a distribution like the Normal.</p>
<p>50th is of course the median, and the 25th and 75th percentilies are the quartiles.</p>
<p>Here, the same things we have previously discussed in relation to samples are applied to populations</p>
<p>We can also see that Monty lies on the 83rd percentile, that is 83% of babies born in 2020 weighed less. This tallies with what we were told at the time, and then things are monitored quite closely from that time on in terms of percentiles.</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Moving to a discussion of low birthweight. It is medically defined as low if below 2500g. Nuffield reports that 6.6% of babies in 2020 were born at low birthweight, which is fairly good.</p>
<p>This tallies fairly well with the predicted proportion from the normal distribution of 7.2%</p>
<p>What we gain from the grey shaded area is the proportion of the population which is expected to be born at low birthweight, but also an indication of the probability that a randomly-chosen baby born in 2020 would be of low weight.</p>
<p>This concept can easily be transferred to other weights in this population (and by extension to other variables and populations distributed like this)</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="assoc_rel.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="uncertainty.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/03-Distributions.rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["LFD.pdf", "LFD.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
