<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 8 Introduction to Statistics | WBS MRes: Learning From Data</title>
  <meta name="description" content="This book contains the examples and notes for the WBS MrRes Learning from Data Course. It is based on the Bookdown Demo written by Hui. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 8 Introduction to Statistics | WBS MRes: Learning From Data" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This book contains the examples and notes for the WBS MrRes Learning from Data Course. It is based on the Bookdown Demo written by Hui. The output format for this example is bookdown::gitbook." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 Introduction to Statistics | WBS MRes: Learning From Data" />
  
  <meta name="twitter:description" content="This book contains the examples and notes for the WBS MrRes Learning from Data Course. It is based on the Bookdown Demo written by Hui. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Professor Nick Lee" />


<meta name="date" content="2024-09-20" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="probability.html"/>
<link rel="next" href="H-testing.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>



<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">WBS DBA Quantitative Methods</li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction and Orientation</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Describing the World With Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#summarizing-data-with-numbers"><i class="fa fa-check"></i><b>2.1</b> Summarizing Data with Numbers</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#box-plots"><i class="fa fa-check"></i><b>2.2</b> Box Plots</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#violin-plots-and-ridge-plots"><i class="fa fa-check"></i><b>2.3</b> Violin Plots and Ridge Plots</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="assoc_rel.html"><a href="assoc_rel.html"><i class="fa fa-check"></i><b>3</b> Associations and Relationships</a>
<ul>
<li class="chapter" data-level="3.1" data-path="assoc_rel.html"><a href="assoc_rel.html#correlations-and-associations"><i class="fa fa-check"></i><b>3.1</b> Correlations and Associations</a></li>
<li class="chapter" data-level="3.2" data-path="assoc_rel.html"><a href="assoc_rel.html#introducing-nonlinear-associations"><i class="fa fa-check"></i><b>3.2</b> Introducing Nonlinear Associations</a></li>
<li class="chapter" data-level="3.3" data-path="assoc_rel.html"><a href="assoc_rel.html#regression"><i class="fa fa-check"></i><b>3.3</b> Regression</a></li>
<li class="chapter" data-level="3.4" data-path="assoc_rel.html"><a href="assoc_rel.html#multiple-regression"><i class="fa fa-check"></i><b>3.4</b> Multiple Regression</a></li>
<li class="chapter" data-level="3.5" data-path="assoc_rel.html"><a href="assoc_rel.html#visualizing-multiple-regression"><i class="fa fa-check"></i><b>3.5</b> Visualizing Multiple Regression</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="uncertainty.html"><a href="uncertainty.html"><i class="fa fa-check"></i><b>4</b> Beginning to Understand Uncertainty</a>
<ul>
<li class="chapter" data-level="4.1" data-path="uncertainty.html"><a href="uncertainty.html#demonstration-sampling-from-a-known-population"><i class="fa fa-check"></i><b>4.1</b> Demonstration: Sampling from a ‘Known’ Population</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="bootstrap.html"><a href="bootstrap.html"><i class="fa fa-check"></i><b>5</b> Introduction to Bootstrapping</a>
<ul>
<li class="chapter" data-level="5.1" data-path="bootstrap.html"><a href="bootstrap.html#bootstrapping-in-the-context-of-previous-examples"><i class="fa fa-check"></i><b>5.1</b> Bootstrapping in the Context of Previous Examples</a></li>
<li class="chapter" data-level="5.2" data-path="bootstrap.html"><a href="bootstrap.html#bootstrapping-other-stuff"><i class="fa fa-check"></i><b>5.2</b> Bootstrapping Other Stuff…</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="bootstrap.html"><a href="bootstrap.html#correlations"><i class="fa fa-check"></i><b>5.2.1</b> Correlations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="t-test.html"><a href="t-test.html"><i class="fa fa-check"></i><b>6</b> T-Tests for Means</a>
<ul>
<li class="chapter" data-level="6.1" data-path="t-test.html"><a href="t-test.html#independent-sample-t-tests"><i class="fa fa-check"></i><b>6.1</b> Independent Sample T-Tests</a></li>
<li class="chapter" data-level="6.2" data-path="t-test.html"><a href="t-test.html#paired-sample-t-tests"><i class="fa fa-check"></i><b>6.2</b> Paired-Sample T-tests</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>7</b> Introduction to Probability</a>
<ul>
<li class="chapter" data-level="7.1" data-path="probability.html"><a href="probability.html#simulating-coin-flips"><i class="fa fa-check"></i><b>7.1</b> Simulating Coin Flips</a></li>
<li class="chapter" data-level="7.2" data-path="probability.html"><a href="probability.html#premier-league-goals-and-the-poisson-distribution"><i class="fa fa-check"></i><b>7.2</b> Premier League Goals and the Poisson Distribution</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="probability.html"><a href="probability.html#update"><i class="fa fa-check"></i><b>7.2.1</b> 2023 Update</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="probability.html"><a href="probability.html#birth-weight-and-the-normal-distribution-brief-example"><i class="fa fa-check"></i><b>7.3</b> Birth Weight and the Normal Distribution: Brief Example</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="statistics.html"><a href="statistics.html"><i class="fa fa-check"></i><b>8</b> Introduction to Statistics</a>
<ul>
<li class="chapter" data-level="8.1" data-path="statistics.html"><a href="statistics.html#the-distribution-of-sample-means-and-the-central-limit-theorem"><i class="fa fa-check"></i><b>8.1</b> The Distribution of Sample Means, and the Central Limit Theorem</a></li>
<li class="chapter" data-level="8.2" data-path="statistics.html"><a href="statistics.html#conf"><i class="fa fa-check"></i><b>8.2</b> Demonstrating Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="H-testing.html"><a href="H-testing.html"><i class="fa fa-check"></i><b>9</b> Classical Statistical Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="9.1" data-path="H-testing.html"><a href="H-testing.html#correlation-significance-tests"><i class="fa fa-check"></i><b>9.1</b> Correlation Significance Tests</a></li>
<li class="chapter" data-level="9.2" data-path="H-testing.html"><a href="H-testing.html#regression-significance-tests"><i class="fa fa-check"></i><b>9.2</b> Regression Significance Tests</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ANOVA.html"><a href="ANOVA.html"><i class="fa fa-check"></i><b>10</b> ANOVA</a>
<ul>
<li class="chapter" data-level="10.1" data-path="ANOVA.html"><a href="ANOVA.html#post-hoc-testing"><i class="fa fa-check"></i><b>10.1</b> Post-Hoc Testing</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="Issues.html"><a href="Issues.html"><i class="fa fa-check"></i><b>11</b> Issues with Significance Testing</a>
<ul>
<li class="chapter" data-level="11.1" data-path="Issues.html"><a href="Issues.html#more-on-the-multiple-comparisons-problem"><i class="fa fa-check"></i><b>11.1</b> More on the Multiple Comparisons Problem</a></li>
<li class="chapter" data-level="11.2" data-path="Issues.html"><a href="Issues.html#the-bonferroni-correction-rate-of-change-in-football-goals-per-season"><i class="fa fa-check"></i><b>11.2</b> The Bonferroni Correction: Rate of Change in Football Goals per Season</a></li>
<li class="chapter" data-level="11.3" data-path="Issues.html"><a href="Issues.html#statistical-power-brief-demonstration"><i class="fa fa-check"></i><b>11.3</b> Statistical Power: Brief Demonstration</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">WBS MRes: Learning From Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistics" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Chapter 8</span> Introduction to Statistics<a href="statistics.html#statistics" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This Chapter builds on the material in Lesson 9.</p>
<p>Here, we begin to apply our probability concepts to the task of statistical inference in the ‘classical’ way.</p>
<p>The theory explained and demonstrated here is the foundation of the (very large) majority of the quantitative business and management research you will read and use. Almost any time someone refers to a finding being <strong>(statistically) significant</strong> or a <strong>p-value</strong>, they are using this idea. However, a major weakness in many social science fields - business and management being one - is that a rather large proportion of researchers don’t actually understand the core principles of statistical inference, and are instead often just copying what other people have written, or told them to do.</p>
<p>So, if you can get your head around the next 3-4 chapters, you’ll be in a strong position to work with what’s already out there, and also do your own solid research.</p>
<div id="the-distribution-of-sample-means-and-the-central-limit-theorem" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> The Distribution of Sample Means, and the Central Limit Theorem<a href="statistics.html#the-distribution-of-sample-means-and-the-central-limit-theorem" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The first thing to cover is an extension of the ideas in the last chapter about sampling distributions. It’s called the <em>Central Limit Theorem</em>, and is often the source of much angst in statistics students (including myself). However, here I am actually going to demonstrate how it works, and show how is actually quite amazing.</p>
<p>To do so, I will use a synthetic data set of monthly incomes from 20 people. Let us treat this data set as the <strong>population</strong>.</p>
<pre><code>## # A tibble: 6 × 2
##   Person Income
##   &lt;chr&gt;   &lt;dbl&gt;
## 1 A        5600
## 2 B        6000
## 3 C        6400
## 4 D        6800
## 5 E        7200
## 6 F        7600</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    5600    7500    9400    9400   11300   13200</code></pre>
<pre><code>## [1] 2366.432</code></pre>
<p>Above, you’ll see the important descriptive statistics, including the standard deviation of 2366.432. Let’s plot the frequency distribution, and once we do so we will find that it is essentially uniform - every value occurs once and only once in the population.</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-96-1.png" width="672" /></p>
<p>Now, what I am going to do is take a <em>single random sample of 2</em> from that population. This sample is taken ‘without replacement’, if you are wondering, and so it is in essence exactly as if a researcher went into the field and took a sample from this population.</p>
<pre><code>## [1] &quot;One Random Combination of 2 of the 20 Income Values&quot;</code></pre>
<pre><code>## [1] 11600  7200</code></pre>
<p>Let’s take the mean of the sample:</p>
<pre><code>##    res1
## 1 11600
## 2  7200</code></pre>
<pre><code>## [1] 9400</code></pre>
<p>The mean of the random sample of 2 will of course be different each time the sample is taken (e.g. when writing this text, the mean was 10600, but this may not be the same in the version you are reading!)</p>
<p>Just for reference, the mean of the population (remember, the 20 people) was 9400</p>
<p>So, let’s now do that for <strong>every possible combination of 2 values</strong> from this population.</p>
<p>Given there are n=20 values in the population, there are k=190 possible combinations of two values.</p>
<p>Note: This is not the same as bootstrapping - we are <em>not sampling with replacement</em> here. We are instead taking combinations. The thing to think about is that this is the equivalent of taking every single possible sample of 2 that you could take from this population.</p>
<p>Remember the ping-pong balls!</p>
<p>Let’s do it:</p>
<pre><code>## [1] &quot;Every Possible Combination of the 20 Income Values&quot;</code></pre>
<pre><code>##         [,1]  [,2]
##   [1,]  5600  6000
##   [2,]  5600  6400
##   [3,]  5600  6800
##   [4,]  5600  7200
##   [5,]  5600  7600
##   [6,]  5600  8000
##   [7,]  5600  8400
##   [8,]  5600  8800
##   [9,]  5600  9200
##  [10,]  5600  9600
##  [11,]  5600 10000
##  [12,]  5600 10400
##  [13,]  5600 10800
##  [14,]  5600 11200
##  [15,]  5600 11600
##  [16,]  5600 12000
##  [17,]  5600 12400
##  [18,]  5600 12800
##  [19,]  5600 13200
##  [20,]  6000  6400
##  [21,]  6000  6800
##  [22,]  6000  7200
##  [23,]  6000  7600
##  [24,]  6000  8000
##  [25,]  6000  8400
##  [26,]  6000  8800
##  [27,]  6000  9200
##  [28,]  6000  9600
##  [29,]  6000 10000
##  [30,]  6000 10400
##  [31,]  6000 10800
##  [32,]  6000 11200
##  [33,]  6000 11600
##  [34,]  6000 12000
##  [35,]  6000 12400
##  [36,]  6000 12800
##  [37,]  6000 13200
##  [38,]  6400  6800
##  [39,]  6400  7200
##  [40,]  6400  7600
##  [41,]  6400  8000
##  [42,]  6400  8400
##  [43,]  6400  8800
##  [44,]  6400  9200
##  [45,]  6400  9600
##  [46,]  6400 10000
##  [47,]  6400 10400
##  [48,]  6400 10800
##  [49,]  6400 11200
##  [50,]  6400 11600
##  [51,]  6400 12000
##  [52,]  6400 12400
##  [53,]  6400 12800
##  [54,]  6400 13200
##  [55,]  6800  7200
##  [56,]  6800  7600
##  [57,]  6800  8000
##  [58,]  6800  8400
##  [59,]  6800  8800
##  [60,]  6800  9200
##  [61,]  6800  9600
##  [62,]  6800 10000
##  [63,]  6800 10400
##  [64,]  6800 10800
##  [65,]  6800 11200
##  [66,]  6800 11600
##  [67,]  6800 12000
##  [68,]  6800 12400
##  [69,]  6800 12800
##  [70,]  6800 13200
##  [71,]  7200  7600
##  [72,]  7200  8000
##  [73,]  7200  8400
##  [74,]  7200  8800
##  [75,]  7200  9200
##  [76,]  7200  9600
##  [77,]  7200 10000
##  [78,]  7200 10400
##  [79,]  7200 10800
##  [80,]  7200 11200
##  [81,]  7200 11600
##  [82,]  7200 12000
##  [83,]  7200 12400
##  [84,]  7200 12800
##  [85,]  7200 13200
##  [86,]  7600  8000
##  [87,]  7600  8400
##  [88,]  7600  8800
##  [89,]  7600  9200
##  [90,]  7600  9600
##  [91,]  7600 10000
##  [92,]  7600 10400
##  [93,]  7600 10800
##  [94,]  7600 11200
##  [95,]  7600 11600
##  [96,]  7600 12000
##  [97,]  7600 12400
##  [98,]  7600 12800
##  [99,]  7600 13200
## [100,]  8000  8400
## [101,]  8000  8800
## [102,]  8000  9200
## [103,]  8000  9600
## [104,]  8000 10000
## [105,]  8000 10400
## [106,]  8000 10800
## [107,]  8000 11200
## [108,]  8000 11600
## [109,]  8000 12000
## [110,]  8000 12400
## [111,]  8000 12800
## [112,]  8000 13200
## [113,]  8400  8800
## [114,]  8400  9200
## [115,]  8400  9600
## [116,]  8400 10000
## [117,]  8400 10400
## [118,]  8400 10800
## [119,]  8400 11200
## [120,]  8400 11600
## [121,]  8400 12000
## [122,]  8400 12400
## [123,]  8400 12800
## [124,]  8400 13200
## [125,]  8800  9200
## [126,]  8800  9600
## [127,]  8800 10000
## [128,]  8800 10400
## [129,]  8800 10800
## [130,]  8800 11200
## [131,]  8800 11600
## [132,]  8800 12000
## [133,]  8800 12400
## [134,]  8800 12800
## [135,]  8800 13200
## [136,]  9200  9600
## [137,]  9200 10000
## [138,]  9200 10400
## [139,]  9200 10800
## [140,]  9200 11200
## [141,]  9200 11600
## [142,]  9200 12000
## [143,]  9200 12400
## [144,]  9200 12800
## [145,]  9200 13200
## [146,]  9600 10000
## [147,]  9600 10400
## [148,]  9600 10800
## [149,]  9600 11200
## [150,]  9600 11600
## [151,]  9600 12000
## [152,]  9600 12400
## [153,]  9600 12800
## [154,]  9600 13200
## [155,] 10000 10400
## [156,] 10000 10800
## [157,] 10000 11200
## [158,] 10000 11600
## [159,] 10000 12000
## [160,] 10000 12400
## [161,] 10000 12800
## [162,] 10000 13200
## [163,] 10400 10800
## [164,] 10400 11200
## [165,] 10400 11600
## [166,] 10400 12000
## [167,] 10400 12400
## [168,] 10400 12800
## [169,] 10400 13200
## [170,] 10800 11200
## [171,] 10800 11600
## [172,] 10800 12000
## [173,] 10800 12400
## [174,] 10800 12800
## [175,] 10800 13200
## [176,] 11200 11600
## [177,] 11200 12000
## [178,] 11200 12400
## [179,] 11200 12800
## [180,] 11200 13200
## [181,] 11600 12000
## [182,] 11600 12400
## [183,] 11600 12800
## [184,] 11600 13200
## [185,] 12000 12400
## [186,] 12000 12800
## [187,] 12000 13200
## [188,] 12400 12800
## [189,] 12400 13200
## [190,] 12800 13200</code></pre>
<pre><code>## [1] &quot;Number of combinations without repetition&quot;</code></pre>
<pre><code>## [1] 190</code></pre>
<p>That was a rather long exhibit up there, but I wanted to show you that this was actually really done properly, and we have 190 combinations.</p>
<p>Next, let us create the means of each of the 190 combinations</p>
<pre><code>##     X1   X2 MDIST
## 1 5600 6000  5800
## 2 5600 6400  6000
## 3 5600 6800  6200
## 4 5600 7200  6400
## 5 5600 7600  6600
## 6 5600 8000  6800</code></pre>
<p>That’s just the first 6 (the head of the data set), but you can rest assured that there are 190 means created here.</p>
<p>OK, so here is the kicker. Let’s plot a histogram of these 190 means.</p>
<p>Remember, a histogram is a frequency distribution:</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-101-1.png" width="672" /></p>
<p>Well well well!</p>
<p>Even though the original population was a completely uniform distribution with a mean of 9400, the distribution of all of the sample means looks quite a lot like a normal distribution / bell curve!</p>
<p>Let’s overlay one on it as well to make the point…</p>
<p><img src="LFD_files/figure-html/unnamed-chunk-102-1.png" width="672" /></p>
<p>Further, let’s take the mean of those means…</p>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    5800    8200    9400    9400   10600   13000</code></pre>
<p>Hello! It turns out, the mean of those means is the <em>population mean!!!</em></p>
<p>This, in a demonstration, is <em>the central limit theorem.</em></p>
<p>Let’s <strong>move back to the slides</strong> to talk about this some more.</p>
</div>
<div id="conf" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Demonstrating Confidence Intervals<a href="statistics.html#conf" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Below I will demonstrate the idea of confidence intervals as a measure of precision, and at the same time help to really lock in the correct interpretation of what a confidence interval really means.</p>
<p>To do so, I will continue the in-class example of WBS Ph.D. graduate salaries. However, here, I will <strong>simulate</strong> the population distribution that we have sampled from. Let’s recap:</p>
<p>Sample size (N) = 42</p>
<p>Sample mean = 170,000</p>
<p>Sample SD = 46617.4</p>
<p>I will simulate a population distribution that this sample could quite conceivably have come from. It will have the following features:</p>
<p>Population mean = 165,000</p>
<p>Population SD = 40000</p>
<p>I will also assume that the population distribution is <em>normal</em>. That is, the distribution of all business and management Ph.D. starting salaries is shaped like a bell curve - the normal distribution (remember birth weights from the last chapter). This is a reasonable assumption in my view, given the features of the phenomena we are investigating.</p>
<p>The important thing to remember is not really the population distribution of salaries (which is just used here to simulate the population), but the <em>sampling distribution of the means</em>. Remember, the central limit theorem shows us that <strong>whatever the shape of the population distribution we are sampling from</strong>, the sampling distribution of the means will take the form of a normal distribution, with a mean of the population mean.</p>
<p>So, below, I will simulate the population, and then calculate 100 confidence intervals for 4 different sample sizes (5, 10, 42, 100), to demonstrate two things:</p>
<ol style="list-style-type: lower-alpha">
<li>How confidence intervals get more precise as sample size increases, and</li>
<li>How to interpret your specific confidence interval as simply one possibility of many.</li>
</ol>
<p><img src="LFD_files/figure-html/unnamed-chunk-105-1.png" width="672" /><img src="LFD_files/figure-html/unnamed-chunk-105-2.png" width="672" /><img src="LFD_files/figure-html/unnamed-chunk-105-3.png" width="672" /><img src="LFD_files/figure-html/unnamed-chunk-105-4.png" width="672" /></p>
<p>So, you can see that the confidence intervals for each of the 100 samples at a given sample size all cluster around the mean, but are wider as sample size is lower. That makes sense intuitively.</p>
<p>Looking specifically at our example N of 42, we can estimate which one of the 100 that might be, and see how the CI for sample means of about that size does include the real population mean of 165. You can also see there are a number of coloured CIs which do <strong>not</strong> include the sample mean. This shows how to interpret a CI.</p>
<p>Specifically, <strong>your actual sample</strong> is one of a very large amount of possible samples from the population (here we took 100 but we could have taken many more). The CI calculation essentially creates a CI with the width so that, out of 100 random samples, approximately 95 will actually contain the <em>true population mean</em>.</p>
<p>As such, we can see how it is clearly a measure of the <strong>precision</strong> of the estimate. For a compelling visualization of this, look how wide the CIs for N=5 are.</p>
<p>One thing to remember though is the ‘law of large numbers’ here. You might notice that not all of the CI plots contain exactly 5 intervals that do not contain the mean. This is analagous to the idea of coin flipping - it’s just probability over very large numbers of trials, not saying that ‘out of every 100, exactly 5 will not include the population mean’. But, over a very large number of trials, we can expect the amount of intervals that do not include the mean to tend towards 5%, in the same way that over a large number of coin flips, the proportion of heads tends towards 50%.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="probability.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="H-testing.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/07-statistics.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["LFD.pdf", "LFD.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
